= Wraith Glossary
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

WARNING: The reference manual is the source of truth for the rules.
If this document differs, it is wrong.

The Wraith Glossary is copyright &copy; 2022 by Michael D Henderson.
Please see the LICENSE file for copying details.

:sectnums:
== Glossary
Common terms for Wraith.

anti-missle unit::
Define this, please.

assault craft unit::
Define this, please.

assault weapon unit::
Define this, please.

asteroid belt::
An _asteroid belt_ is a type of *planet* that is composed of many small, irregular "rocks."
The belt occupies an entire orbit.

automation unit::
Define this, please.

cluster::
The _cluster_ is the *game* area.
It contains many *systems*.
Each system contains one or more *stars*.
Each star contains 11 *orbits*.
Each orbit may be empty, contain a *planet* or *asteroid belt*, or be a nexus to another star in the same system.
Planets and asteroid belts contain *resources* that may be exploited.

construction worker unit::
Define this, please.

consumer goods unit::
Define this, please.

coordinate::
A _coordinate_ is the X, Y, Z location of a *system* in the *cluster*.
Coordinates are relative to the "center" of the cluster.
The X axis points to the motion of the cluster in the galaxy.
The Z axis points to the center of the galaxy.

deposit::
Define this, please.

drone::
Define this, please.

energy weapon unit::
Define this, please.

energy shield unit::
Define this, please.

factory unit::
Define this, please.

factory group::
Define this, please.

farm unit::
Define this, please.

finished product::
Define this, please.

food unit::
A _food_ unit represents a consumable source of energy for *population* units that can be stored and transported.
Food units must be created by *farm* units.

fuel unit::
A _fuel_ unit represents storable, transportable power.
It can be oil, uranium, crystals, etc.
Fuel units must be mined and refined by *mining* units.

game::
Define this, please.

gold unit::
A _gold_ unit represents wealth.
It can be physical assets like precious metals ("gold pressed latinum bars"), crystals (diamonds), as well as intangibles like "credits."
Gold units must be mined and refined by *mining* units.

government::
The _government_ (or the bureaucracy) is the organization which makes and enforces laws for a *nation*.
The government is composed of groups which wield the executive, legislative, and judicial powers for the *state*,
although these may be mixed at the whim of the state.

habitability number::
Define this, please.

hyper-drive::
Define this, please.

labor::
Define this, please.

life support::
Define this, please.

light structural unit::
Define this, please.

metal unit::
A _metal_ unit is a refined metallic ore.
This includes common metals like iron and steel (but never *gold*) and exotic metals like unobtanium and lutyisthebestium.
Metal units can be stored and transported.
Metal units must be mined and refined by *mining* units.

metallic::
_Metallic_ is an alias for *metal* unit.

military robot unit::
Define this, please.

military supply unit::
Define this, please.

mine::
_Mine_ is an alias for *mining* unit.

mining unit::
Define this, please.

mining group::
Define this, please.

missile unit::
Define this, please.

missle launcher unit::
Define this, please.

nation::
A _nation_ is created by people from many *societies* that share a common *homeworld*, language, and history.

non-metal unit::
A _non-metal_ unit is a refined non-metallic ore.
This includes common things like crystals, gases (but never *fuel* units), organic materials like silk (but never *food* units), and exotic materials like trilithium crystals.
Non-metal units can be stored and transported.
Non-metal units must be mined and refined by *mining* units.

non-metallic::
_Non-metallic_ is an alias for *non-metal* unit.

orbit::
An _orbit_ represents something.
Orbits start at 1.
An orbit usually contains a *planet* or *asteroid belt*.

planet::
A _planet_ is a member of a *system* and is identified by the system's *coordinates* and the planet's *orbit*.

player::
The _player_ controls a single *nation* in a *game*.

population unit::
Define this, please.

probe::
Define this, please.

professional unit::
Define this, please.

raw material::
Define this, please.

rebel unit::
Define this, please.

sensor::
Define this, please.

ship::
Define this, please.

shuttle::
_Shuttle_ is an alternative name for a *transport*.

society::
A _society_ in the *game* is a group that shares common language, culture, geography, or religion.
Societies, in their desire for unity and self-determination, come together to create a *nation*.

solar power::
Define this, please.

soldier unit::
Define this, please.

space-drive::
Define this, please.

species::
A _species_ in the *game* is a group that shares a common genetic history.

spy unit::
Define this, please.

starvation::
Define this, please.

state::
A _state_ is a political entity, created by a *nation*,
which is the political organization that holds power in the *government*.
A nation may be ruled by many states in its history.

structural unit::
Define this, please.

system::
A _system_ is a star system that has *orbits*.
All systems are identified by their *coordinates* in the *cluster*.

transport::
Define this, please.

unemployable unit::
An _unemployable_ unit is a type of *population* unit.
It includes those that are not eligble to be members of any other population unit.

unskilled worker unit::
Define this, please.

