= Wraith Glossary
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith Glossary (c) 2022 by Michael D Henderson

Wraith Glossary is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: The reference manual is the source of truth for the rules.
If this document differs, it is wrong.

:sectnums:
== Glossary
Common terms for Wraith.

anti-missle unit::
Define this, please.

assault craft unit::
Define this, please.

assault weapon unit::
Define this, please.

asteroid belt::
An _asteroid belt_ is a type of *planet* that is composed of many small, irregular "rocks."
Asteroids are composed of carbon, silicate, metals, non-metals, and ice.
The asteroid belt occupies an entire orbit.

automation unit::
Define this, please.

bill of materials::
A *bill of materials* (BOM) is a list of material units to be used for building a colony or ship.

BOM::
See *bill of materials*.

C::
_C_ is the prefix for a colony identifier.

cluster::
The _cluster_ is the *game* area.
It contains many *systems*.
Each system contains one or more *stars*.
Each star contains 11 *orbits*.
Each orbit may be empty, contain a *planet* or *asteroid belt*, or be a nexus to another star in the same system.
Planets and asteroid belts contain *resources* that may be exploited.

colony::
A _colony_ is required to establish *control* of a *planet*.
There are three types of _colonies_: *open colonies*, *enclosed colonies*, and *orbiting colonies*.

construction worker::
_Construction worker_ is not a *population* unit;
it is a group of *professional* and *unskilled worker* units that are trained to build things.

consumer goods unit::
Define this, please.

coordinate::
A _coordinate_ is the X, Y, Z location of a *system* in the *cluster*.
Coordinates are relative to the "center" of the cluster.
The X axis points to the motion of the cluster in the galaxy.
The Z axis points to the center of the galaxy.

deposit::
Define this, please.

DP::
_DP_ is the prefix for a deposit identifier.

drone::
Define this, please.

enclosed colony::
An _enclosed colony_ is built on the surface of an uninhabitable *terrestial planet*, a moon of a *gas giant* or on an asteroid in an *asteroid belt*.
Enclosed colonies require *life support* units to sustain *population* units.

energy weapon unit::
Define this, please.

energy shield unit::
Define this, please.

factory unit::
Define this, please.

factory group::
Define this, please.

farm unit::
Define this, please.

FG::
_FG_ is the prefix for a *factory group* identifier.

finished product::
Define this, please.

food unit::
A _food_ unit represents a consumable source of energy for *population* units that can be stored and transported.
Food units must be created by *farm* units.

fuel unit::
A _fuel_ unit represents storable, transportable power.
It can be oil, uranium, crystals, etc.
Fuel units must be mined and refined by *mining* units.

game::
Define this, please.

gas giant planet::
A _gas giant_ is a giant *planet* with an atmosphere of mostly helium and hydrogen.
The surface of the planet can't be reached because of the high mass and temperatures.
*Colonies* may be built on the surface of moons orbiting a gas giant.

gold unit::
A _gold_ unit represents wealth.
It can be physical assets like precious metals ("gold pressed latinum bars"), crystals (diamonds), as well as intangibles like "credits."
Gold units must be mined and refined by *mining* units.

government::
The _government_ (or the bureaucracy) is the organization which makes and enforces laws for a *nation*.
The government is composed of groups which wield the executive, legislative, and judicial powers for the *state*,
although these may be mixed at the whim of the state.

governor::
_Governor_ is an alias for *regent*.

habitable planet::
A _habitable planet_ is a *terrestial planet* with a *habitability number* greater than zero.

habitability number::
Define this, please.

hyper-drive unit::
Define this, please.

ice giant::
An _ice giant_ is a type of *gas giant* that is composed of liquids or gases other than helium and hydrogen.

labor::
Define this, please.

life support::
Define this, please.

light structure unit::
A _light structure unit_ is used to build colonies, ships, and storage.
These units have less mass than the *standard structure unit* but can replace them on a one-for-one basis.

metal unit::
A _metal_ unit is a refined metallic ore.
This includes common metals like iron and steel (but never *gold*) and exotic metals like unobtanium and lutyisthebestium.
Metal units can be stored and transported.
Metal units must be mined and refined by *mining* units.

metallic::
_Metallic_ is an alias for *metal* unit.

MG::
_MG_ is the prefix for a *mining group* identifier.

military robot unit::
Define this, please.

military supply unit::
Define this, please.

mine::
_Mine_ is an alias for *mining* unit.

mining unit::
Define this, please.

mining group::
Define this, please.

missile unit::
Define this, please.

missle launcher unit::
Define this, please.

nation::
A _nation_ is created by people from many *societies* that share a common *homeworld*, language, and history.

non-metal unit::
A _non-metal_ unit is a refined non-metallic ore.
This includes common things like crystals, gases (but never *fuel* units), organic materials like silk (but never *food* units), and exotic materials like trilithium crystals.
Non-metal units can be stored and transported.
Non-metal units must be mined and refined by *mining* units.

non-metallic::
_Non-metallic_ is an alias for *non-metal* unit.

orbit::
An _orbit_ represents something.
Orbits start at 1.
An orbit usually contains a *planet* or *asteroid belt*.

orbiting colony::
An _orbiting colony_ is built in orbit around a planet.
Orbiting colonies may not be built in empty orbits.
Orbiting colonies require *life support* units to sustain *population* units.

open colony::
An _open colony_ is built on the surface of a *habitable planet*.
Open colonies do not require *life support* units to sustain *population* units.

planet::
A _planet_ orbits a *star* in a *system* and is identified by the *coordinates* of the system and the *orbit* of the star.
Planets may be *terrestrial*, *gas giants*, or an *asteroid belt*.

player::
A _player_ controls a single *nation* in a *game*.

population unit::
Define this, please.

probe::
Define this, please.

professional unit::
A _professional_ unit is a type of *population* unit.

raw material::
Define this, please.

rebel::
_Rebel_ is not a *population* unit;
it is the count of the number of people that are include to rebel against the current *government*.

regent::
A _regent_ is a *player* appointed by another player to off-load responsibility for submitting orders for portions of a *nation*.
The player delegates responsibility for one or more *colonies* and/or *ships* to the regent.
If the player controlling the regent drops, the regency dissolves and all units are returned to the original player.
*Planets* controlled by regents count for *victory conditions* if the regent hasn't rebelled.

S::
_S_ is the prefix for a ship identifier.

sensor::
Define this, please.

ship::
Define this, please.

shuttle::
_Shuttle_ is an alternative name for a *transport*.

shortage::
A _shortage_ happens when production units (farms, factories, and mines) don't have all the fuel, labor, or raw materials they need to run at full capacity.

society::
A _society_ in the *game* is a group that shares common language, culture, geography, or religion.
Societies, in their desire for unity and self-determination, come together to create a *nation*.

solar power::
Define this, please.

soldier unit::
A _soldier_ unit is a type of *population* unit.

space-drive unit::
Define this, please.

species::
A _species_ in the *game* is a group that shares a common genetic history.

spy::
_Spy_ is not a *population* unit;
it is a group of *professional* and *soldier* units that are trained to conduct espionage.

star::
A _star_ in the game contains 11 *orbits* where at least one orbit has a *planet*.
If the star is in a *system* with multiple stars, the 11th orbit is a link between the stars in the system.
Otherwise the 11th orbit is empty.

starvation::
_Starvation_ occurs when *population* units do not have enough *food* units in a turn.
Maintenance level is 0.25 units and the minimum needed to prevent starvation is 25% of that (0.0625 units).

state::
A _state_ is a political entity, created by a *nation*,
which is the political organization that holds power in the *government*.
A nation may be ruled by many states in its history.

structural unit::
A _structural unit_ is a measure of how much infrastructure is needed to build a colony, ship, or enclosed storage.
Each structural unit encloses a variable number of mass units (MUs), depending on how and where it is used.
An *open colony* requires 1 standard structural unit to enclose 1 MU.
An *enclosed colony* requires 5 standard structural units to enclose 1 MU.
An *orbiting colony* requires 10 standard structural units to enclose 1 MU.
A *ship* requires 10 standard structural units to enclose 1 MU.

standard structure unit::
A _standard structure unit_ is used to build colonies, ships, and enclosed storage.

super light structure unit::
A _super light structure unit_ is used to build colonies, ships, and enclosed storage.
These units have less mass than the *standard structure unit* but can replace them on a one-for-one basis.

system::
A _system_ contains one or more *stars*.
All systems are identified by their *coordinates* in the *cluster*.

terrestial planet::
A _terrestial_ *planet* is round and large enough to sweep its orbit clear, but is smaller than a gas giant.
It may have an atmosphere and a metal core, or it could be a frozen iceball with no atmosphere.
*Colonies* may be built on the surface of terrestial planets.

transport::
Define this, please.

unemployable unit::
An _unemployable_ unit is a type of *population* unit.
It includes those that are not eligble to be members of any other population unit.

unskilled worker unit::
An _unskilled worker_ unit is a type of *population* unit.

viceroy::
_Viceroy_ is an alias for *regent*.

victory conditions::
Define this, please.