= Wraith Glossary
Michael D Henderson <mdhender@example.com>
v1.0.0, 2022-06-10
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith Glossary (c) 2022 by Michael D Henderson

Wraith Glossary is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: The reference manual is the source of truth for the rules.
If this document differs, it is wrong.

:sectnums:
== Codes
|===
|Unit|Code|Description

|anti-missile|ANM-TL|
|assault-craft|ASC-TL|
|assault-weapon|ASW-TL|
|automation|AUT-TL|
|consumer-goods|CNGD|
|energy-shield|ESH-TL|
|energy-weapon|EWP-TL|
|factory|FCT-TL|
|farm|FRM-TL|
|food|FOOD|
|fuel|FUEL|
|gold|GOLD|
|hyper-drive|HDR-TL|
|life-support|LSP-TL|
|light-structural|LTSU|
|metallics|MTLS|
|military-robots|MLR-TL|
|military-supplies|MLSP|
|mine|MIN-TL|
|missile|MSS-TL|
|missile-launcher|MSL-TL|
|non-metallics|NMTS|
|sensor|SNR-TL|
|space-drive|SDR-TL|
|structural|STUN|
|super-light-structural|SLSU|
|transport|TPT-TL|
|===

== Glossary
Common terms for Wraith.

AF::
_AF_ is the attack factor used in combat.

anti-missile unit::
Define this, please.

assault craft unit::
Define this, please.

assault weapon unit::
Define this, please.

asteroid belt::
An _asteroid belt_ is a type of *planet* that is composed of many small, irregular "rocks."
Asteroids are composed of carbon, silicate, metals, non-metals, and ice.
The asteroid belt occupies an entire orbit.

automation unit::
Define this, please.

bill of materials::
A *bill of materials* (BOM) is a list of material units to be used for building a colony or ship.

BOM::
See *bill of materials*.

C::
_C_ is the prefix for a colony identifier.

CF::
_CF_ is the combat factor used in combat.

cluster::
The _cluster_ is the *game* area.
It contains many *systems*.
Each system contains one or more *stars*.
Each star contains 11 *orbits*.
Each orbit may be empty, contain a *planet* or *asteroid belt*, or be a nexus to another star in the same system.
Planets and asteroid belts contain *resources* that may be exploited.

colony::
A _colony_ is required to establish *control* of a *planet*.
There are three types of _colonies_: *open colonies*, *enclosed colonies*, and *orbiting colonies*.

construction worker::
_Construction worker_ is not a *population* unit;
it is a group of *professional* and *unskilled worker* units that are trained to build things.

consumer goods unit::
Define this, please.

coordinate::
A _coordinate_ is the X, Y, Z location of a *system* in the *cluster*.
Coordinates are relative to the "center" of the cluster.
The X axis points to the motion of the cluster in the galaxy.
The Z axis points to the center of the galaxy.
They are written as `X/Y/Z`.
For planets, an octothorpe and the orbit number are appended: `X/Y/Z#ORBIT`.

deposit::
Define this, please.

DF::
_DF_ is either the distance factor or defense factor.

DIY Kit::
_DIY Kit_ is an alias for *operational unit*.

DP::
_DP_ is the prefix for a deposit identifier.

drone::
Define this, please.

enclosed colony::
An _enclosed colony_ is built on the surface of an uninhabitable *terrestial planet*, a moon of a *gas giant*, or on an asteroid in an *asteroid belt*.
Enclosed colonies require *life support* units to sustain *population* units.

energy weapon unit::
Define this, please.

energy shield unit::
Define this, please.

factory unit::
A _factory_ produces all units in the game except for *food*, *fuel*, *gold*, *metal*, and *non-metal* units.
Factory units are the only units that can convert fuel and raw materials into finished goods.
Factory units must be added to a *factory group* before they can produce anything.

factory group::
A _factory group_ is a set of *factory* units assigned to work together as part of a common assembly line.
The factory units do not have to be the same *tech level*.
Due to economy of scale, larger groups need fewer manager and workers per factory unit to operate.

farm unit::
A _farm_ unit produces food for the general population.
Farms can be built on the surface of habitable terrestrial planets, in enclosed and orbital colonies, or on ships.

FG::
_FG_ is the prefix for a *factory group* identifier.

finished product::
A _finished product_ is any unit built by a *factory group*.

food unit::
A _food_ unit represents a consumable source of energy for *population* units that can be stored and transported.
Food units must be created by *farm* units.

fuel unit::
A _fuel_ unit represents storable, transportable power.
It can be oil, uranium, crystals, etc.
Fuel units must be mined and refined by *mining* units.

game::
Define this, please.

gas giant planet::
A _gas giant_ is a giant *planet* with an atmosphere of mostly helium and hydrogen.
The surface of the planet can't be reached because of the high mass and temperatures.
*Colonies* may be built on the surface of moons orbiting a gas giant.

gold unit::
A _gold_ unit represents wealth.
It can be physical assets like precious metals ("gold pressed latinum bars"), crystals (diamonds), as well as intangibles like "credits."
Gold units must be mined and refined by *mining* units.

government::
The _government_ (or the bureaucracy) is the organization which makes and enforces laws for a *nation*.
The government is composed of groups which wield the executive, legislative, and judicial powers for the *state*,
although these may be mixed at the whim of the state.

governor::
_Governor_ is an alias for *regent*.

habitable planet::
A _habitable planet_ is a *terrestial planet* with a *habitability number* greater than zero.

habitability number::
Define this, please.

home planet market::
A _home planet market_ is an open air *market* found only on homeworlds.
The market collects commissions directly, they are not paid to the controlling player.

hudnut::
_Hudnut_ (also known as a DIY Kit) is an item that must be assembled by a construction crew before it can be used.
These units can be disassembled when not in use to save space on a colony or ship.
They must be disassembled to be placed on a *transport*.
(I couldn't find a better term, so I borrowed this https://en.wikipedia.org/wiki/Sniglet[Sniglet].)

hyper-drive unit::
Define this, please.

ice giant::
An _ice giant_ is a type of *gas giant* that is composed of liquids or gases other than helium and hydrogen.

ID::
numerical identifer for colony, ship, group, etc.

independent colony::
An _independent colony_ is not controlled by any player in the game.

independent ship::
An _independent ship_ is not controlled by any player in the game.

labor::
Define this, please.

life support::
Define this, please.

light structure unit::
A _light structure unit_ is used to build colonies, ships, and storage.
These units have less mass than the *standard structure unit* but can replace them on a one-for-one basis.

market::
A _market_ enables trade between players.
The market accepts sell orders, matches them with buy orders, and collects a commision on each exchange.

mass unit::
A _mass_ (abbreviated as MU) is the in-game measurement for "weight" and "volume" of a unit.
The MU determines the number of drives needed to move units.
It also factors into the number of *structural units* needed to store units (see *EMU*).

metal unit::
A _metal_ unit is an alias for *metallic unit*.

metallic unit::
A _metallic_ unit is a refined metallic ore.
This includes common metals like iron and steel (but never *gold*) and exotic metals like unobtanium and lutyisthebestium.
Metallic units can be stored and transported.
Metallic units must be mined and refined by *mining* units.

MG::
_MG_ is the prefix for a *mining group* identifier.

military robot unit::
Define this, please.

military supply unit::
Define this, please.

mine unit::
_Mine_ units extract natural resources by mining, drilling, and even logging.
They refine the raw materials and produce *metallic* and *non-metallic* ores, *fuel*, and *gold* that are used by *factory* units, *colonies*, and *ships*.
Factories use metallic and non-metallic ores to build units.
Fuels, which are any power source, power factories, colonies, and ships.
Gold (any precious substance) is used to pay the population and trade with other nations.

mining unit::
_Mining_ is an alias for *mine* unit.

mining group::
A _mining group_ (abbreviated *MG*) is a group of mines assigned to work a single *deposit*.

missile unit::
Define this, please.

missile launcher unit::
Define this, please.

MU::
_MU_ is an abbrevition for *mass unit*.

nation::
A _nation_ is created by people from many *societies* that share a common *homeworld*, language, and history.

nexus jump point::
The _nexus jump point_ is the 11th orbit around a star.
It is the point where a ship entering the system using its *hyper-drive* engines will arrive.
If there are multiple stars in a single system, the 11th orbit is shared among them.
In this case, ships may use the nexus jump point to travel between the stars in that system.

non-metal unit::
A _non-metal_ unit is an alias for *non-metallic unit*.

non-metallic unit::
A _non-metallic_ unit is a refined non-metallic ore.
This includes common things like crystals, gases (but never *fuel* units), organic materials like silk and timber (but never *food* units), and exotic materials like trilithium crystals.
Non-metallic units can be stored and transported.
Non-metallic units must be mined and refined by *mining* units.

operational unit::
An _operational unit_ is a unit that is ready to be used (it's not disassembled or in *storage*).
Some operational units use fuel every turn they're operational; others only when they're being used.

orbit::
An _orbit_ represents something.
Orbits start at 1 and go up to 11.
The first ten orbits may be empty or contain a *planet*.
The 11th orbit is always empty and is used as the *nexus jump point* for inter-system travel.

orbiting colony::
An _orbiting colony_ is built in orbit around a planet.
Orbiting colonies may not be built in empty orbits.
Orbiting colonies require *life support* units to sustain *population* units.

open colony::
An _open colony_ is built on the surface of a *habitable planet*.
Open colonies do not require *life support* units to sustain *population* units.

planet::
A _planet_ orbits a *star* in a *system* and is identified by the *coordinates* of the system and the *orbit* of the star.
Planets may be *terrestrial*, *gas giants*, or an *asteroid belt*.

player::
A _player_ controls a single *nation* in a *game*.

population unit::
Define this, please.

probe::
Define this, please.

professional unit::
A _professional_ unit is a type of *population* unit.

raw material::
Define this, please.

rebel::
_Rebel_ is not a *population* unit;
it is the count of the number of people that are include to rebel against the current *government*.

regent::
A _regent_ is a *player* appointed by another player to off-load responsibility for submitting orders for portions of a *nation*.
The player delegates responsibility for one or more *colonies* and/or *ships* to the regent.
If the player controlling the regent quits the game,
the regency is automatically dissolved and all units are returned to the original player.
*Planets* controlled by regents count for *victory conditions* if the regent hasn't rebelled.

S::
_S_ is the prefix for a ship identifier.

sensor::
Define this, please.

ship::
Define this, please.

shortage::
A _shortage_ happens when production units (farms, factories, and mines) don't have all the fuel, labor, or raw materials they need to run at full capacity.

shuttle::
_Shuttle_ is an alternative name for a *transport*.

society::
A _society_ in the *game* is a group that shares common language, culture, geography, or religion.
Societies, in their desire for unity and self-determination, come together to create a *nation*.

solar-power::
_Solar-power_ is available to *orbiting colonies* in *orbits* 1 through 5.
These orbiting colonies may use solar-power instead of *fuel* to power certain *farm* and *factory* units.

soldier unit::
A _soldier_ unit is a type of *population* unit.

space-drive unit::
Define this, please.

species::
A _species_ in the *game* is a group that shares a common genetic history.

spy::
_Spy_ is not a *population* unit;
it is a group of *professional* and *soldier* units that are trained to conduct espionage.

star::
A _star_ in the game contains 11 *orbits* where at least one orbit has a *planet*.
If the star is in a *system* with multiple stars, the 11th orbit is a link between the stars in the system.
Otherwise the 11th orbit is empty.

starvation::
_Starvation_ occurs when *population* units do not have enough *food* units in a turn.
Maintenance level is 0.25 units and the minimum needed to prevent starvation is 25% of that (0.0625 units).

state::
A _state_ is a political entity, created by a *nation*,
which is the political organization that holds power in the *government*.
A nation may be ruled by many states in its history.

standard structure unit::
A _standard structure unit_ is used to build colonies, ships, and enclosed storage.

stored unit::
Any item that is powered down and placed in storage is a _stored unit_.
If the unit is a *hudnut*, it may be disassembled before being stowed.
Stowed items are inactive - they do not use fuel and they must be unstowed from storage before they can be used.

stowed unit::
See *stored unit*.

structural unit::
A _structural unit_ is a measure of how much infrastructure is needed to build a colony, ship, or enclosed storage.
Each structural unit encloses a variable number of mass units (MUs), depending on how and where it is used.
An *open colony* requires 1 standard structural unit to enclose 1 MU.
An *enclosed colony* requires 5 standard structural units to enclose 1 MU.
An *orbiting colony* requires 10 standard structural units to enclose 1 MU.
A *ship* requires 10 standard structural units to enclose 1 MU.

super light structure unit::
A _super light structure unit_ is used to build colonies, ships, and enclosed storage.
These units have less mass than the *standard structure unit* but can replace them on a one-for-one basis.

surface colony::
A _surface colony_ is either an open colony or an enclosed colony.
Surface colonies can be built on the surface of a *terrestrial* planet,
large rocks in an *asteroid belt*,
or the moons of a *gas giant*.

system::
A _system_ contains one or more *stars*.
All systems are identified by their *coordinates* in the *cluster*.

terrestial planet::
A _terrestial_ *planet* is round and large enough to sweep its orbit clear, but is smaller than a gas giant.
It may have an atmosphere and a metal core, or it could be a frozen iceball with no atmosphere.
*Colonies* may be built on the surface of terrestial planets.

TF::
_TF_ is the thrust factor produced by all of the *space drive* units on a ship.
The ship's total mass divided by its TF is the maximum distance
(in space combat rings)
that the ship may move in a combat round.

trade station::
A _trade station_ is an *orbital station* built by a player for the express purpose of running a market.
The station may have farms but never factories or mines.

transport::
A _transport_ (or shuttle) is a specialized ship used to ferry people and cargo.
The transport is limited to locations on the planet surface or orbit.
It is not capable of travel between planets or systems.
Transports may be used to quickly move soldiers in combat.
Transports have built in life support units that can support as many people as it it rated to cary.

unemployable unit::
An _unemployable_ unit is a type of *population* unit.
It includes those that are not eligble to be members of any other population unit.

unskilled worker unit::
An _unskilled worker_ unit is a type of *population* unit.

unstowed unit::
Any unit that is not in *storage*.
Unstowed units are considered *operational*.

viceroy::
_Viceroy_ is an alias for *regent*.

victory conditions::
Define this, please.

WIP::
See *work in progress*.

work in progress::
The _work in progress_ is the work that has started in a manufacturing pipeline and has not yet been completed.
Most finished goods take a full year to complete.
For game purposes, the items move through 4 stages in the pipeline.
Stage 1 contains the items that have just started being built.
Stage 2 contains the items that have been in the pipeline for a full turn.
Stage 3 contains the items that have been in the pipeline for two full turns.
Stage 4 contains the items that have been in the pipeline for three full turns.

