= Wraith Glossary
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

WARNING: The reference manual is the source of truth for the rules.
If this document differs, it is wrong.

The Wraith Glossary is copyright &copy; 2022 by Michael D Henderson.
Please see the LICENSE file for copying details.

:sectnums:
== Glossary
Common terms for Wraith.

asteroid belt::
An _asteroid belt_ is a type of *planet* that is composed of many small, irregular "rocks."
The belt occupies an entire orbit.

cluster::
The _cluster_ is the *game* area.
It contains many *systems*.
Each system contains one or more *stars*.
Each star contains 11 *orbits*.
Each orbit may be empty, contain a *planet* or *asteroid belt*, or be a nexus to another star in the same system.
Planets and asteroid belts contain *resources* that may be exploited.

coordinate::
A _coordinate_ is the X, Y, Z location of a *system* in the *cluster*.
Coordinates are relative to the "center" of the cluster.
The X axis points to the motion of the cluster in the galaxy.
The Z axis points to the center of the galaxy.

drone::
Define this, please.

game::
Define this, please.

government::
The _government_ (or the bureaucracy) is the organization which makes and enforces laws for a *nation*.
The government is composed of groups which wield the executive, legislative, and judicial powers for the *state*,
although these may be mixed at the whim of the state.

habitability number::
Define this, please.

missile::
Define this, please.

nation::
A _nation_ is created by people from many *societies* that share a common *homeworld*, language, and history.

orbit::
An _orbit_ represents something.
Orbits start at 1.
An orbit usually contains a *planet* or *asteroid belt*.

planet::
A _planet_ is a member of a *system* and is identified by the system's *coordinates* and the planet's *orbit*.

player::
The _player_ controls a single *nation* in a *game*.

probe::
Define this, please.

ship::
Define this, please.

society::
A _society_ in the *game* is a group that shares common language, culture, geography, or religion.
Societies, in their desire for unity and self-determination, come together to create a *nation*.

species::
A _species_ in the *game* is a group that shares a common genetic history.

state::
A _state_ is a political entity, created by a *nation*,
which is the political organization that holds power in the *government*.
A nation may be ruled by many states in its history.

system::
A _system_ is a star system that has *orbits*.
All systems are identified by their *coordinates* in the *cluster*.
