= Wraith Reference Manual
Michael D Henderson <mdhender@example.com>
v1.0.4, 2022-07-04
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith Reference Manual (c) 2022 by Michael D Henderson

Wraith Reference Manual is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: This document is meant to be concise and definitive.
That makes it a terrible source for learning the game.
The User's Guide is the recommended source for getting started.

NOTE: This reference manual is the source of truth for the rules.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

=== How to start
This reference manual presents the rules with very little explanation.
You may find it helpful to read the <<Units>> section before skimming through the <<a-phase-chart, Phase Chart>>.
That should give you enough background to read the Users Guide.
Use this manual when you have questions.

== Organization
The manual arranges rules in the sequence they would be processed during a game turn.

Charts are presented where they are first used.

The section headings are taken from the Phase Chart:

[[a-phase-chart]]
.Phase Chart
|===
|Phase|Description

|Fuel Allocation|In this phase, fuel is allocated to units.
Fuel allocations are prioritized: life support is first, followed by farms, mines, then factories.
The allocation algorithm is naive and simple.
It attempts to allocate 100% of a unit's needs before moving to the next unit.
It never allocates proportionately.
|Life Support|Population changes due to life support are calculated.
|Farming Production|The farming production phase todo...
|Mining Production|The mining phase is used to extract resources from deposits and refine them into materials that can be used in the manufacturing phase.
|Manufacturing Production|The manufacturing production phase todo...
|Combat|The combat phase is used to project force against other player's assets.
|Set-Up|The Set-Up phase is used to assemble new colonies and ships.
|Disassembly|This phase is used to disassembly operational units and make them ready to put into storage.
|Retool|Change the manufacturing pipeline for existing factory groups.
|Mining Change|The mining change orders phase is used to todo...
|Transfer|Population and cargo are moved between ships and colonies in the same orbit using available transports.
|Assembly|The assembly phase is used to manufacture items, mine resources, and assemble units from storage.
|Trade|The market and trade station phase is used to process trade and barter orders at markets and trade stations.
|Survey|This phase surveys systems, planets, colonies, and ships.
|Survey Reports|This phase produces the probe and sensor reports.
Todo...
|Espionage|The espionage phase todo...
|Ship Movement|This is the only phase in which ships move.
|Draft|This phase applies draft orders to move workers between population unit types todo...
|Pay and Ration|This phase is used to pay the population and distribute food.
Pay is either gold (in the form of credits) or consumer goods.
The player may change the default pay and ration rates.
|Rebellion|Chances for rebel militias to engage in open rebellion are calculated and results checked.
Active militias will engage in combat starting the next turn.
|Control|In this phase, naming and control orders are todo...
|Birth|Population changes due to births are calculated.
|Training|Population changes due to training and apprenticeships are calculated.
|Retirement|Population changes due to retirement are calculated.
|Death|Population changes due to starvation and natural deaths are calculated.
|Research|Changes to the tech level for a colony or ship tech level are determined in this phase.
|Bookkeeping|?
|News|In this phase, reports for the "news services" are created todo...
|===

NOTE: All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued by the player.

== Fuel Allocation Phase
The number of fuel units available to every colony and ship is calculated and updated.

Excess fuel is immediately moved to storage.
If there is not enough storage available on the colony or ship, excess fuel is lost.

Fuel units in storage are available for use in the remaining phases.

WARNING: Fuel units are only produced via mining.
They are not available for use until the turn after they've been mined.

=== Stored vs Operational vs Active
Items that are in storage never consume fuel.

Items that are operational may use fuel every turn or only those turns that they're used.

An operational item that has the required fuel and labor is active and ready to be used.
All other units are inactive.

== Life Support Phase
Life-support units maintain the environment needed to sustain people in an enclosed colony,
orbital colony, or ship.

=== Fuel
Life-support units require fuel to be active.
They do not require labor units.

At the start of this phase, fuel is allocated to all operational life-support units.

NOTE: Players are not allowed to activate only a portion of the life-support units on a colony or ship.

[[a-life-support-fuel-cost-chart]]
.Life Support Fuel Cost
|===
|Unit-TechLevel|Fuel per Unit per Turn

|life-support-1|1
|life-support-2|2
|life-support-3|3
|life-support-4|4
|life-support-5|5
|life-support-6|6
|life-support-7|7
|life-support-8|8
|life-support-9|9
|life-support-10|10
|===

=== Effect
At the start of this phase, the active life-support units are counted.
This number is used to calculate the number of population units each colony or ship can support.

Each active life-support unit will support a number of population units equal to its Tech Level squared.
"Excess population" is the number of people over this value.

TIP: Population in cryo-sleep are not counted towards the life support limit.

[[a-life-support-effect-chart]]
.Life Support Effect
|===
|Unit-TechLevel|Population units supported per Unit per Turn

|life-support-1|1
|life-support-2|4
|life-support-3|9
|life-support-4|16
|life-support-5|25
|life-support-6|36
|life-support-7|49
|life-support-8|64
|life-support-9|81
|life-support-10|100
|===

The excess population are casualties and are removed immediately.
These casualties are distributed uniformly across all population groups on the colony or ship.

WARNING: The excess population checks are made at the end of each phase.
This means that if a colony or ship has too many population units in a later phase, the excess population will become casualties, too.

WARNING: Life-support units must be operational for the entire turn.
If the units are shut down for any reason, the capacity will be recalculated and excess population will immediately become casualties.
This includes sabotage and damage in combat.

== Farming Production Phase
Farm units produce food units to feed the population.

WARNING: Without sufficient food, the population will starve.
Starvation leads to deaths and increases the chance of rebellion.

=== Location
Farm units may be installed in locations per the following chart:

[[a-farm-location-chart]]
.Farm Location
|===
|Unit-TechLevel ^|Orbits ^|Open Colony ^|Enclosed Colony ^|Orbital Colony ^|Ship

|farm-1 ^|1..5 ^|yes ^|no ^|no ^|no
|farm-2 ^|1..5 ^|yes ^|yes ^|yes ^|no
|farm-3 ^|1..5 ^|yes ^|yes ^|yes ^|no
|farm-4 ^|1..5 ^|yes ^|yes ^|yes ^|no
|farm-5 ^|1..5 ^|yes ^|yes ^|yes ^|no
|farm-6 ^|any ^|yes ^|yes ^|yes ^|yes
|farm-7 ^|any ^|yes ^|yes ^|yes ^|yes
|farm-8 ^|any ^|yes ^|yes ^|yes ^|yes
|farm-9 ^|any ^|yes ^|yes ^|yes ^|yes
|farm-10 ^|any ^|yes ^|yes ^|yes ^|yes
|===

=== Fuel
Farm units require fuel or solar-power to be active.
If a farm unit does not have a full allocation of fuel or solar-power, it is inactive for the turn.

[[a-farm-fuel-cost-chart]]
.Farm Fuel Cost
|===
|Unit-TechLevel|Fuel per Unit per Turn

|farm-1 >|0.5
|farm-2 >|1.0
|farm-3 >|1.5
|farm-4 >|2.0
|farm-5 >|2.5
|farm-6 >|6.0
|farm-7 >|7.0
|farm-8 >|8.0
|farm-9 >|9.0
|farm-10 >|10.0
|===

WARNING: Fuel is always allocated before labor.
If there's a labor shortage, it is possible that more fuel will be allocated than can be used.

==== Solar Power
Some farm units that are on orbital colonies in the first five orbits are solar-powered and consume no fuel.

[[a-farm-solar-power-availability-chart]]
.Farm Solar Power Availability
|===
|Unit-TechLevel|Light Source|Can use Solar Power?

|farm-1 >|Sunlight|No
|farm-2 >|Sunlight|Yes, if on Orbital Station in orbits 1..5
|farm-3 >|Sunlight|Yes, if on Orbital Station in orbits 1..5
|farm-4 >|Sunlight|Yes, if on Orbital Station in orbits 1..5
|farm-5 >|Sunlight|Yes, if on Orbital Station in orbits 1..5
|farm-6 >|Lamps|No
|farm-7 >|Lamps|No
|farm-8 >|Lamps|No
|farm-9 >|Lamps|No
|farm-10 >|Lamps|No
|===

If a farm unit can use solar-power, its fuel cost drops to 0 fuel units per turn.

=== Labor
Farm units require labor to be active.
If a farm unit does not have a full allocation of labor, it is inactive for the current turn.

[[a-farm-labor-cost-chart]]
.Farm Labor Cost
|===
|Unit-TechLevel|Professional units per Farm unit|Unskilled-Worker units per Farm unit

|farm-1 >|1 >|3
|farm-2 >|2 >|6
|farm-3 >|3 >|9
|farm-4 >|4 >|12
|farm-5 >|5 >|15
|farm-6 >|6 >|18
|farm-7 >|7 >|21
|farm-8 >|8 >|24
|farm-9 >|9 >|27
|farm-10 >|10 >|30
|===

Unskilled-Worker units may be replaced by automation units.

=== Production
The number of food units produced by active farm units is calculated in this phase.
The food units are moved to local depots for temporary storage.

A farm unit produces no food units if it has not been active for at least two consecutive turns.

A farm unit produces no food units the first turn that it is active.



Farm units will produce food after they have been active for two consecutive turns.
In other words, if the farm unit is active this turn and was active the prior turn,
it will produce food units per the following chart.

[[a-farm-production-chart]]
.Farm Production
|===
|Unit-TechLevel|Production per Unit per Turn

|farm-1|25
|farm-2|10
|farm-3|15
|farm-4|20
|farm-5|25
|farm-6|30
|farm-7|35
|farm-8|40
|farm-9|45
|farm-10|50
|===

=== Shortages
Shortages in labor or fuel result in lost production.

Shortages will be applied to the farm units in Stage 1 before Stage 2.
All food stuck in a stage is lost.

== Mining Production Phase
Mine units extract natural resources by mining, drilling, and even logging.
They refine the raw materials and produce metallic and non-metallic ores, fuels, and gold that are used by factories, colonies, and ships.
Factories use metallic and non-metallic ores to build units.
Fuels, which are any power source, power factories, colonies, and ships.
Gold (any precious substance) is used to pay the population and trade with other nations.

=== Location
Mine units may be installed in locations per the following chart:

[[a-mine-location-chart]]
.Mine Location
|===
|Unit-TechLevel ^|Orbits ^|Open Colony ^|Enclosed Colony ^|Orbital Colony ^|Ship

|mine-1 ^|any ^|yes ^|yes ^|no ^|no
|mine-2 ^|any ^|yes ^|yes ^|no ^|no
|mine-3 ^|any ^|yes ^|yes ^|no ^|no
|mine-4 ^|any ^|yes ^|yes ^|no ^|no
|mine-5 ^|any ^|yes ^|yes ^|no ^|no
|mine-6 ^|any ^|yes ^|yes ^|no ^|no
|mine-7 ^|any ^|yes ^|yes ^|no ^|no
|mine-8 ^|any ^|yes ^|yes ^|no ^|no
|mine-9 ^|any ^|yes ^|yes ^|no ^|no
|mine-10 ^|any ^|yes ^|yes ^|no ^|no
|===

=== Groups
Mine units must be assigned to a mining group before they can be activated.
A mine unit is inactive if is it not assigned to a mining group.

The mining group can have mine units from different tech levels.

One mining group is assigned to each deposit.
Each deposit may be worked by only one mining group.
(This prevents multiple nations from extracting raw materials from the same deposit.)

=== Fuel
Mine units require fuel or solar-power to be active.
If a mine unit does not have a full allocation of fuel or solar-power, it is inactive for the turn.

[[a-mine-fuel-cost-chart]]
.Mine Fuel Cost
|===
|Unit-TechLevel|Fuel per Unit per Turn

|mine-1 >|0.5
|mine-2 >|1.0
|mine-3 >|1.5
|mine-4 >|2.0
|mine-5 >|2.5
|mine-6 >|3.0
|mine-7 >|3.5
|mine-8 >|4.0
|mine-9 >|4.5
|mine-10 >|5.0
|===

WARNING: Fuel is always allocated before labor.
If there's a labor shortage, it is possible that more fuel will be allocated than can be used.

==== Solar Power
Some mine units that are the surface of planets in the first five orbits are solar-powered and consume no fuel.

[[a-mining-solar-power-availability-chart]]
.Mine Solar Power Availability
|===
|Unit-TechLevel|Can use Solar Power?

|mine-1 >|Yes, if on the surface of a planet in orbits 1..5
|mine-2 >|Yes, if on the surface of a planet in orbits 1..4
|mine-3 >|Yes, if on the surface of a planet in orbits 1..3
|mine-4 >|Yes, if on the surface of a planet in orbits 1..2
|mine-5 >|Yes, if on the surface of a planet in orbit 1
|mine-6 >|No
|mine-7 >|No
|mine-8 >|No
|mine-9 >|No
|mine-10 >|No
|===

If a mine unit can use solar-power, its fuel cost drops to 0 fuel units per turn.

=== Labor
Mine units require labor to be active.
If a mine unit does not have a full allocation of labor, it is inactive for the turn.

[[a-mine-labor-cost-chart]]
.Mine Labor Cost
|===
|Unit-TechLevel|Professional units per Mine unit|Unskilled-Worker units per Mine unit

|mine-1 >|1 >|3
|mine-2 >|2 >|6
|mine-3 >|3 >|9
|mine-4 >|4 >|12
|mine-5 >|5 >|15
|mine-6 >|6 >|18
|mine-7 >|7 >|21
|mine-8 >|8 >|24
|mine-9 >|9 >|27
|mine-10 >|10 >|30
|===

Unskilled-Worker units may be replaced by automation units.

=== Production
Mine units will produce refined materials after they have been active for four consecutive turns.
In other words, if the mine unit is active this turn and was active the prior three turns,
it will produce units per the following chart.

[[a-mine-production-chart]]
.Mine Production
|===
|Unit-TechLevel|Production per Unit per Turn

|mine-1 >|25 * Yield% MU
|mine-2 >|50 * Yield% MU
|mine-3 >|75 * Yield% MU
|mine-4 >|100 * Yield% MU
|mine-5 >|125 * Yield% MU
|mine-6 >|150 * Yield% MU
|mine-7 >|175 * Yield% MU
|mine-8 >|200 * Yield% MU
|mine-9 >|225 * Yield% MU
|mine-10 >|250 * Yield% MU
|===

NOTE: The amount of refined materials depends upon the yield of the deposit being worked.
A mine-8 working a deposit with a yield of 10% would produce 20 mass units of refined materials per turn.

=== Shortages
Shortages in labor or fuel result in lost production.
Materials being produced by the mine unit are not lost,
but they do not move to the next stage in the processing pipeline, either.

Shortages will be applied to the mine units in Stage 1, then Stage 2, and finally to Stage 3.

== Factory Production Phase
The amount of finished goods produced by factory groups is calculated in this phase.

Factories produce the following units:

[[a-factory-produced-units-chart]]
.Factory Produced Units
|===
|Unit

|anti-missile
|assault-craft
|assault-weapon
|automation
|consumer-goods
|energy-shield
|energy-weapon
|factory
|farm
|hyper-drive
|life-support
|light-structural
|military-robot
|military-supplies
|mine
|missile
|missile-launcher
|sensor
|space-drive
|structural
|super-light-structural
|transport
|===

NOTE: The tech level of finished goods is determined by the colony's tech level.
The factory unit's tech level is used only to calculate input and output values.

=== Location
Factory units may be installed in locations per the following chart:

[[a-factory-location-chart]]
.Factory Location
|===
|Unit-TechLevel ^|Orbits ^|Open Colony ^|Enclosed Colony ^|Orbital Colony ^|Ship

|factory-1 ^|any ^|yes ^|yes ^|yes ^|no
|factory-2 ^|any ^|yes ^|yes ^|yes ^|no
|factory-3 ^|any ^|yes ^|yes ^|yes ^|no
|factory-4 ^|any ^|yes ^|yes ^|yes ^|no
|factory-5 ^|any ^|yes ^|yes ^|yes ^|no
|factory-6 ^|any ^|yes ^|yes ^|yes ^|no
|factory-7 ^|any ^|yes ^|yes ^|yes ^|no
|factory-8 ^|any ^|yes ^|yes ^|yes ^|no
|factory-9 ^|any ^|yes ^|yes ^|yes ^|no
|factory-10 ^|any ^|yes ^|yes ^|yes ^|no
|===

=== Groups
Factory units must be assigned to a factory group before they can be activated.
A factory unit is inactive if is it not assigned to a factory group.

The factory group can have factory units from different tech levels.
The entire factory group will produce the same item.

=== Fuel
Factory units require fuel or solar-power to be active.
If a factory unit does not have a full allocation of fuel or solar-power, it is inactive for the turn.

[[a-factory-fuel-cost-chart]]
.Factory Fuel Cost
|===
|Unit-TechLevel|Fuel per Unit per Turn

|factory-1 >|0.5
|factory-2 >|1.0
|factory-3 >|1.5
|factory-4 >|2.0
|factory-5 >|2.5
|factory-6 >|6.0
|factory-7 >|7.0
|factory-8 >|8.0
|factory-9 >|9.0
|factory-10 >|10.0
|===

WARNING: Fuel is always allocated before labor.
If there's a labor shortage, it is possible that more fuel will be allocated than can be used.

Note: Inactive factory units never consume fuel.

==== Solar Power
Some factory units that are on orbital colonies in the first five orbits are solar-powered and consume no fuel.

[[a-factory-solar-power-availability-chart]]
.Factory Solar Power Availability
|===
|Unit-TechLevel|Can use Solar Power?

|factory-1 >|Yes, if on Orbital Station in orbits 1..5
|factory-2 >|Yes, if on Orbital Station in orbits 1..4
|factory-3 >|Yes, if on Orbital Station in orbits 1..3
|factory-4 >|Yes, if on Orbital Station in orbits 1..2
|factory-5 >|Yes, if on Orbital Station in orbit 1
|factory-6 >|No
|factory-7 >|No
|factory-8 >|No
|factory-9 >|No
|factory-10 >|No
|===

If a factory unit can use solar-power, its fuel cost drops to 0 fuel units per turn.

=== Labor
Factory units require labor to be active.
The amount of labor is determined by the total number of factory units in the group.
The efficiency of a factory group improves as more factory units are added.

The following chart shows the number of labor units needed based on the total number of factory units in the group:

[[a-factory-group-labor-cost-chart]]
.Factory Group Labor Cost
|===
|Size|Professional units per Factory unit|Unskilled-Worker units per Factory unit

>|1 - 4 factory units|6|18
>|5 - 49 factory units|5|15
>|50 - 499 factory units|4|12
>|500 - 4,999 factory units|3|9
>|5,000 - 49,999 factory units|2|6
>|50,000 - up factory units|1|3
|===

If a factory group does not have a full allocation of labor, it will use the shortage rules for the turn.

TIP: Automation units may replace unskilled-worker units.

=== Production
Production is highly abstracted in this game.
Each factory unit consumes up to 5 mass units (MUs) of refined materials per turn for four turns.
At the end of the fourth turn, the factory unit produces the finished good.

The quantity and type of inputs needed for each finished good is per the following chart:

[[a-factory-production-required-materials-chart]]
.Factory Production Required Materials
|===
|Unit|Metallic units|Non-Metallic units|Gold units|Fuel units

|anti-missile >|2 * TL >|2 * TL >|0 >|0
|assault-craft >|3 * TL >|2 * TL >|0 >|0
|assault-weapon >|1 * TL >|1 * TL >|0 >|0
|automation >|2 * TL >|2 * TL >|0 >|0
|consumer-goods >|0.200 >|0.400 >|0 >|0
|energy-shield >|25 * TL >|25 * TL >|0 >|0
|energy-weapon >|5 * TL >|5 * TL >|0 >|0
|factory >|8 + TL >|4 + TL >|0 >|0
|farm >|4 + TL >|2 + TL >|0 >|0
|hyper-drive >|25 * TL >|20 * TL >|0 >|0
|life-support >|3 * TL >|5 * TL >|0 >|0
|light-structural >|0.010 >|0.040 >|0 >|0
|military-robot >|10 + TL >|10 + TL >|0 >|0
|military-supplies >|0.020 >|0.020 >|0 >|0
|mine >|5 + TL >|5 + TL >|0 >|0
|missile >|2 * TL >|2 * TL >|0 >|0
|missile-launcher >|15 * TL >|10 * TL >|0 >|0
|sensor >|10 * TL >|20 * TL >|0 >|0
|space-drive >|15 * TL >|10 * TL >|0 >|0
|structural >|0.100 >|0.400 >|0 >|0
|super-light-structural >|0.001 >|0.004 >|0 >|0
|transport >|3 * TL >|1 * TL >|0 >|0
|===

NOTE: The quantity of materials needed for most items is based on the tech level of the finished good.

If the FACTORY unit is active this TURN and was active the prior TURN, it will produce finished goods per the production chart.
Otherwise, it will produce nothing.

The tech level of the finished goods is not limited by the factory units in the group.
It is limited by the tech level of the colony.

WARNING: Unless otherwise stated, it takes 4 turns to manufacture a finished good.
Adding more factory units to a factory group will consume more refined materials,
which increases the amount of finished goods;
it will not reduce the amount of time needed to manufacture the finished goods.

=== Shortages
Shortages in labor or fuel result in lost production.
Goods being produced by the factory unit are not lost,
but they do not move to the next stage in the production pipeline, either.

Shortages will be applied to the factory units in Stage 1, then Stage 2, and finally to Stage 3.

== Combat Phase
All orders in the Combat phase are executed in the order that they're entered in the orders file.

Each colony or ship may be given a single combat order per turn.

NOTE: Future change to allow for attacks against multiple targets.

NOTE: Future change to create "fleets" if needed to help with combat orders.

Some units require FUEL to be used in combat.

[[a-combat-factor-chart]]
.Combat Factor Chart
|===
|Unit|Combat Factor

|assault-craft|10 * TL
|assault-weapon|2 * TL
|military-robot|2 * TL
|soldier|1
|===

[[a-combat-fuel-cost-chart]]
.Combat Fuel Cost
|===
|Unit|Fuel use per Unit per Turn|Fuel use per Unit per Combat Round

|assault-craft >|0.1 >|n/a
|energy-shield >|n/a >|4 * TL
|energy-weapon >|n/a >|10 * TL
|space-drive >|n/a >|TL^2^
|===

[[a-combat-thrust-factor-chart]]
.Combat Thrust Factor (TF) Chart
|===
|Unit|Thrust Factor per Unit per Combat Round

|space-drive >|1000 * TL^2^
|===

The total thrust factors (TF) divided by the ship's total mass is the maximum number of space combat rings a ship may move in a single combat round.

The player has no control over any ship's movement in combat.

Soldier and military-robot units consume military-supplies units at a rate of one military-supplies unit per soldier unit per combat round.
If either unit runs out of military-supplies units, it will disengage and return to its origin.
If the unit can't, soldier units will surrender while military-robot units will self-destruct to avoid capture.

Percentage of Commitment is an alias for percentage of units the player will commit to combat with that order.

Colonies and ships will usually participate in only one combat per turn.

The first step in the combat phase is sorting out the combatants in each battle.
The Battle Group (BAG) is the list of all colonies and ships involved in a combat at a location.
It includes the attacking colony or ship and the defending colony or ship.
It also includes all colonies or ships that are supporting either the attacker or the defender.

=== Bombard Order
The `bombard` order commits fuel, energy-weapon, missile, and missile-launcher units to an attack against a colony or ship.
The objective is to destroy the target.

.Combat Bombard Order
[source]
----
ColonyOrShipID bombard SpeciesID ColonyOrShipID Percentage
----

.Combat Bombard Order Examples
[source]
----
S27 bombard SP18 C13 50%
----

[[a-colony-distance-factor-chart]]
.Colony Distance Factor
|===
^|+|Open Colony|Enclosed Colony|Orbital Colony|Ship

|Open Colony|1|1|2|1..100
|Enclosed Colony|1|1|2|1..100
|Orbital Colony|2|2|3|1..100
|Ship|1..100|1..100|1..100|1..100
|===

==== Actions
NOTE: Maximum range for a missile or energy weapon fired from a ship is 10.

=== Invade Order
The `invade` order commits fuel, soldier, military-robot, and transport units to an attack against a colony or ship.
The objective is to destroy the target.

.Combat Invade Order
[source]
----
ColonyOrShipID invade SpeciesID ColonyOrShipID Percentage
----

.Combat Invade Order Examples
[source]
----
S27 invade SP18 C13 50%
----

=== Raid Order
The `raid` order commits fuel, soldier, military-robot, and transport units to an attack against a colony or ship.
The objective is to seize and retrieve an enemy asset.

If successful, the raiders will return with 0.5 mass units (rounded down) of the asset.

.Combat Raid Order
[source]
----
ColonyOrShipID raid SpeciesID ColonyOrShipID PercentCommitted AssetID Percent
----

.Combat Raid Order Examples
[source]
----
S27 raid SP18 C13 assault-weapon-5 10%
----

NOTE: This is a peculiar order because it assumes that there are enough soldiers to carry the asset to the transport and that the transport is large enough to hold the asset.
It also requires you to specify a particular tech level when you have no way of knowing what a colony or ship is carrying.

==== Actions
Military-robot units can replace soldier unit.
Each military-robot unit robot will replace up to TL * 2 soldier units.

. Commit troops (soldiers and robots).
. Load troops onto assault craft (each assault craft requires 1 soldier unit to operate).
. Arm excess troops with assault weapons (each assault weapon requires 1 soldier unit to operate).
. Return excess troops to idler's pool.
. Load armed troops onto transports (remember to use combined mass of assault weapons and troops).
. If not enough transports, disarm and return excess troops to idler's pool.

NOTE: Each assault craft holds one soldier unit, which is 100 people.
That's a really large assault craft.

During combat
. Destroying the soldier unit operating an assault craft destroys the craft.
. Destroying the soldier unit operating an assault weapon destroys the weapon.

NOTE: During combat, a transport can carry a maximum of TL * 3 MU per combat round.
It uses fuel at a rate of TL^2^ * 0.01 per round trip.

=== Sabotage Order
The `sabotage` order commits fuel, soldier, military-robot, and transport units to an attack against a colony or ship.
The objective is to destroy an enemy asset.

If successful, the saboteurs will destroy 0.5 mass units (rounded down) of the asset.

.Combat Sabotage Order
[source]
----
ColonyOrShipID sabotage SpeciesID ColonyOrShipID PercentCommitted AssetID Percent
----

.Combat Sabotage Order Examples
[source]
----
S27 sabotage SP18 C13 hyper-drive-5 10%
----

NOTE: This is a peculiar order because you specify a particular tech level when you have no way of knowing what a colony or ship is carrying.
It should probably be just `S27 sabotage SP18 C13 hyper-drive 10%`.

=== Support Order
The `support` order commits FUEL, SOLDIER, MILITARY ROBOT, and TRANSPORT units to a coordinated attack against a colony or ship.
The objective is to work with another player to achieve an objective.
It can also be used for defending.

.Combat Support Order
[source]
----
ColonyOrShipID support SpeciesID ColonyOrShipID against SpeciesID Percent
ColonyOrShipID support SpeciesID ColonyOrShipID bombard SpeciesID ColonyOrShipID Percent
ColonyOrShipID support SpeciesID ColonyOrShipID invade  SpeciesID ColonyOrShipID Percent
----

NOTE: Using the `against` version of the order commits your units to defending your partner's colony or ship.

.Combat Support Order Examples
[source]
----
S14 support SP12 S83 against SP18     100%
S14 support SP12 S83 bombard SP18 C13 100%
S14 support SP12 S83 invade  SP18 C13 100%
----

== Set-Up Phase
The Set-Up phase is used to build new colonies and ships.

All orders in the Set-Up phase are executed in the order that they're entered in the orders file.

There are limitations on where colonies and ships may be built.
There are also limits on the number of colonies each player may build in a single orbit.

[[a-build-location-chart]]
.Build Location Chart
|===
|Unit|# per Player per Orbit|On Planet Surface|On Asteroid Belt|In Orbit|Life Support Required|Maximum Size

|open-colony >|1 ^|Habitable Terrestrial ^|NO ^|NO ^|NO ^|unlimited
|enclosed-colony >|1 ^|Any Terrestrial ^|YES ^|NO ^|YES ^|unlimited
|orbital-colony >|1 ^|NO ^|NO ^|Any Planet ^|YES ^|unlimited
|ship ^|unlimited ^|NO ^|NO ^|Any Planet ^|YES ^|unlimited
|===

Set up orders are used to assemble a new colony or ship.

The order includes the list of material units for the assembly.
(This list is also known as the "bill of materials", or BOM.)
All materials must be present at the site prior to starting.

This order will span multiple lines since it specifies the list of materials.
The player must use the `end` keyword to terminate the order.

The BOM must include CONSTRUCTION WORKER units.
These units will assemble the colony or ship and will be returned once the assembly is complete.
While working, these units will draw FOOD from the site
(meaning the ship or colony they were transferred from).

The CONSTRUCTION WORKER units will use STRUCTURAL units to build the "hull" of the colony or ship
(actually, it's the combination of external and internal structure, but hull is easier to type).

The BOM must include the structural units for building the hull.
The CONSTRUCTION WORKER units will use the available units to enclose the largest space possible.
The amount should be enough to enclose the total number of Enclosed MASS units (EMUs) planned for the colony or ship.
EMUs don't include the mass of the SUs used to build the colony or ship
(in other words, the hull doesn't count towards enclosed mass, but it does count for engines).
Items in storage are counted as 1/2 their mass for purposes of the EMU.

[[a-structural-unit-summary-chart]]
.Structural Unit Summary
|===
|Unit|Mass per UNIT|Open Colony|Enclosed Colony|Orbital Colony|Ship

|structural >|0.5 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|light-structural >|0.05 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|super-light-structural >|0.005 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|===

Once the structure is complete, the CONSTRUCTION WORKER units will transfer the remainder of the BOM to the colony or ship.
Items like engines, life support, weapons, and sensors will be installed in the colony or ship.
The remaining items, like FOOD and CONSUMER GOODS, will be placed directly in storage or cargo holds.
Unless the orders transfer the construction crew to the new colony or ship, they will return to their original host.

The BOM should include POPULATION units.
These units will establish control of the colony or ship once complete.
(An unpopulated colony or ship can be claimed by any player.)

The BOM should include enough FOOD units to feed the included POPULATION units.
Unlike the CONSTRUCTION WORKER units, the POPULATION units will not draw FOOD from the site.

When designing a ship or colony, it is helpful to prepare a chart like the one below.

|===
|Unit-TechLevel|Quantity|Mass Units (MUs)|Enclosed Mass Units (EMUs)|Structure Units Required

|HULL||||
|structural >|50,000 >|25,000|? >|0
|COMMAND & CONTROL||||
|professional >|5 >|5|? >|50
|life-support-1 >|5 >|40|? >|400
|sensors-1 >|1 >|3,000|? >|30,000
|ENGINES||||
|space-drives-1 >|1 >|25|? >|250
|hyper-drive-1 >|30 >|1,350|? >|13,500
|fuel >|1,000 >|1,000|? >|5,000
|STORAGE||||
|food >|20 >|120|? >|600
|===

=== Build Colony Order
TIP: Use `build colony` to build a new colony.

.Build Colony Order
[source]
----
build colony
  ; bill of materials used to assemble the colony
end
----

=== Build Ship Order
TIP: Use `build ship` to build a new ship.

.Build Ship Order
[source]
----
build ship
  ; bill of materials used to assemble the ship
end
----


== Disassembly orders
All orders in the Disassembly phase are executed in the order that they're entered in the orders file.

=== Unassemble Construction Worker Order
An `unassemble` order disbands CONSTRUCTION WORKER units and returns their PROFESSIONAL and UNSKILLED WORKER units to the population.

Each unassembled CONW unit will return 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit to the idler's pool.

.Unassemble Order
[source]
----
ColonyOrShipID unassemble Quantity construction-worker
----

.Unassemble Order Examples
[source]
----
C13 unassemble 3 construction-worker ; disband 3 CONW by returning 3 PRO and 3 UKSW
----

=== Unassemble Operational Unit Order
An `unassemble` order instructs CONSTRUCTION WORKER units to take a unit apart and prepare it for storage.
This reduces the space required to store and transport the unit.

Only the unit in the <<a-operational-units-chart, Operational Units>> chart can be unassembled.
(You can't unassemble something that was never assembled!)

A CONSTRUCTION WORKER unit can unassemble up to 500 MASS units (MUs) per TURN.
10% of the units taken apart will be scrapped and lost as a result.

.Unassemble Order
[source]
----
ColonyOrShipID unassemble Quantity UnitCodeTL
----

.Unassemble Order Examples
[source]
----
S52 unassemble 200 life-support-3      ; take apart 200 units - 20 will be scrapped
C27 unassemble  71 missile-launcher-2  ; take apart  71 units -  8 will be scrapped
----

=== Unassemble Spy Order
An `unassemble` order disbands SPY units and returns their PROFESSIONAL and SOLDIER units to the population.

Each unassembled SPY unit will return 1 PROFESSIONAL unit and 1 SOLDIER unit to the idler's pool.

.Unassemble Order
[source]
----
ColonyOrShipID unassemble Quantity spy
----

.Unassemble Order Examples
[source]
----
S11 unassemble 16 spy  ; disband 16 SPY by returning 16 PRO and 16 SLDR
----

== Change Orders

== Retool Phase
Use construction worker units to change the manufacturing lines in existing factory groups.
The order may take up to four turns to complete since the crews must wait for all existing WIP to complete.

All orders in the Retool phase are executed in the order that they're entered in the orders file.

=== Retool Order
A `retool` order instructs CONSTRUCTION WORKER units to wait for the *WIP* to complete.
Once the production line is empty, the CONSTRUCTION WORKER units shut down all the factory units in the group.
Then they update the production line to build a new finished good and restart the FACTORY GROUP.
It takes one TURN to update and restart.

WARNING: If there are not enough construction worker units available to complete the update in a single turn,
they will continue the update in future turns until it is completed.
The entire group will be idle until the update has completed.

.Retool Order
[source]
----
ColonyID FactoryGroupID retool UnitID
----

.Retool Order Examples:
[source]
----
C6  FG19 retool research         ; begin research when WIP is complete
C27 FG8  retool energy-weapon-4  ; build energy weapons when WIP is complete
----

Build locations restrictions apply for retool orders.
See <<Assemble Factory Group Order>> for those restrictions.

=== Mining change orders

== Transfer Phase
All orders in the Transfer phase are executed in the order that they're entered in the orders file.

=== Transfer Order
A `transfer` order instructs the crew of a transport to load cargo (people or units) onto a transport,
fly the transport to the destination (which must be in the same orbit),
offload the cargo,
and then return to the origin.

Transports require FUEL and labor to operate.
1 PROFESSIONAL unit may operate up to 10 TRANSPORTS per TURN.
The amount of fuel used per turn depends on the total mass units of cargo.
It is equal to the total mass units times the Fuel Factor.

.Transfer Order
[source]
----
ColonyOrShipID transfer Quantity UnitID ColonyOrShipID
----

.Transfer Order Examples
[source]
----
S22 transfer 50 consumer-goods C29  ; move 50 consumer good units from S22 to C29
S22 transfer 10 spy            C29  ; move 10 spy           units from S22 to C29
----

[[a-transport-crew-chart]]
.Transport Crew Chart
|===
|Unit|Crew

|transport|1 PROFESSIONAL per 10 TRANSPORTS
|===

[[a-transport-operations-chart]]
.Transport Operations Chart
|===
|Unit-TL|MUs transferred per Turn|Fuel Factor

|transport-1 >|200 MU >|0.0005
|transport-2 >|800 MU >|0.0005
|transport-3 >|1800 MU >|0.0005
|transport-4 >|3200 MU >|0.0005
|transport-5 >|5000 MU >|0.0005
|transport-6 >|7200 MU >|0.0005
|transport-7 >|9800 MU >|0.0005
|transport-8 >|12800 MU >|0.0005
|transport-9 >|16200 MU >|0.0005
|transport-10 >|20000 MU >|0.0005
|===

== Assembly Phase
All orders in the Assembly phase are executed in the order that they're entered in the orders file.

=== Assemble Construction Worker Order
An `assemble` order gathers PROFESSIONAL and UNSKILLED WORKER units and assembles them as CONSTRUCTION WORKER units.

Each CONW unit requires 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit.
You may not create CONW units if the required number of PROFESSIONAL and UNSKILLED WORKER units are not available.

.Assemble Order
[source]
----
ColonyOrShipID assemble Quantity construction-worker
----

.Assemble Order Examples
[source]
----
C13 assemble 3 construction-worker ; create 3 CONW by assembling 3 PRO and 3 UKSW
----

=== Assemble Factory Group Order
An `assemble` order creates a new FACTORY GROUP and assigns them a finished good to manufacture.
The factory group number will be displayed on the player's report at the end of the turn.

There are restrictions on where items can be built, per the following chart:

[[a-production-location-chart]]
.Production Location Chart
|===
|Unit|Open Colony|Enclosed Colony|Orbital Colony|Ship

|anti-missile ^|YES ^|YES ^|YES ^|NO
|assault-craft ^|YES ^|YES ^|YES ^|NO
|assault-weapon ^|YES ^|YES ^|YES ^|NO
|automation ^|YES ^|YES ^|YES ^|NO
|consumer-goods ^|YES ^|YES ^|YES ^|NO
|energy-shield ^|YES ^|YES ^|YES ^|NO
|energy-weapon ^|YES ^|YES ^|YES ^|NO
|factory ^|YES ^|YES ^|YES ^|NO
|farm ^|YES ^|YES ^|YES ^|NO
|hyper-drive ^|YES ^|YES ^|YES ^|NO
|life-support ^|YES ^|YES ^|YES ^|NO
|light-structural ^|NO ^|NO ^|YES ^|NO
|military-robot ^|YES ^|YES ^|YES ^|NO
|military-supplies ^|YES ^|YES ^|YES ^|NO
|mine ^|YES ^|YES ^|YES ^|NO
|missile ^|YES ^|YES ^|YES ^|NO
|missile-launcher ^|YES ^|YES ^|YES ^|NO
|research ^|YES ^|YES ^|YES ^|NO
|sensor ^|YES ^|YES ^|YES ^|NO
|space-drive ^|YES ^|YES ^|YES ^|NO
|structural ^|YES ^|YES ^|NO ^|NO
|transport ^|YES ^|YES ^|YES ^|NO
|===

Any order that violates a location restriction will be ignored.

.Assemble Order
[source]
----
ColonyID assemble Quantity FactoryTL UnitID
----

.Assemble Order Examples
[source]
----
C8  assemble  5,000 factory-2 assault-craft-6
C91 assemble 50,000 factory-6 consumer-goods
----

NOTE: This order creates a new factory group using a single tech level of factory.
Orders in later turns can add different tech levels to the group.
Future versions of this order should allow the player to mix the tech levels on creation.

=== Assemble Mining Group Order
An `assemble` order creates a new MINING GROUP and assigns them to work a deposit.
The mining group number will be displayed on the player's report at the end of the turn.

.Assemble Order
[source]
----
ColonyID assemble Quantity MineTL DepositID
----

.Assemble Order Examples
[source]
----
C91 assemble 50,000 mine-3 DP3
----

NOTE: This order creates a new mining group using a single tech level of mine.
Orders in later turns can add different tech levels to the group.
Future versions of this order should allow the player to mix the tech levels on creation.

=== Assemble Operational Unit Order
TODO: Operational is a hard-to-understand phrase.

An `assemble` order instructs CONSTRUCTION WORKER units to take a stored (disassembled) unit and make it operational (put it together).

An "operational item" is a unit that must be assembled to be usable.
Operational items can also be disassembled to save space when transporting them.

A CONSTRUCTION WORKER unit can assemble up to 500 MASS units (MUs) per TURN.

Only the items in the Operational Units chart can be assembled.

[[a-operational-units-chart]]
.Operational Units
|===
|Unit

|automation
|energy-shield
|energy-weapon
|factory
|farm
|hyper-drive
|life-support
|light-structural
|mine
|missile-launcher
|sensor
|space-drive
|structural
|super-light-structural
|===

.Assemble Order
[source]
----
ColonyOrShipID assemble Quantity UnitCodeTL
----

.Assemble Order Examples
[source]
----
C27 assemble 9,750 missile-launcher-2
S52 assemble   200 life-support-3
----

=== Assemble Spy Order
An `assemble` order gathers PROFESSIONAL and SOLDIER units and assembles them as SPY units.

Each SPY unit requires 1 PROFESSIONAL unit and 1 SOLDIER unit.
You may not create SPY units if the required number of PROFESSIONAL and SOLDIER units are not available.

.Assemble Order
[source]
----
ColonyOrShipID assemble Quantity spy
----

.Assemble Order Examples
[source]
----
C78 assemble 16 spy  ; create 16 SPY by assembling 16 PRO and 16 SLDR
----

=== Expand Factory Group Order
An `expand` order adds additional FACTORY units to an existing FACTORY GROUP.

.Expand Order
[source]
----
ColonyID FactoryGroupID expand Quantity FactoryTL
----

.Expand Order Examples
[source]
----
C91 FG2 expand 2,500 factory-2  ; add 2,500 FACT-2 units to the group
C91 FG2 expand 1,800 factory-6  ; add 1,800 FACT-6 units to the group
----

=== Expand Mining Group Order
An `expand` order adds additional MINE units to an existing MINING GROUP.

.Expand Order
[source]
----
ColonyID MiningGroupID expand Quantity MineTL
----

.Expand Order Examples
[source]
----
C91 MG2 expand 2,500 mine-2  ; add 2,500 MINE-2 units to the group
C91 MG2 expand 1,800 mine-6  ; add 1,800 MINE-6 units to the group
----

=== Manufacture Items
A `manufacture` order instructs a FACTORY GROUP to start producing units.
The type of unit and the tech level of the unit are specified in the command.
The number of units is not.

.Manufacture Order
[source]
----
ColonyID FactoryGroupID manufacture Quantity UnitCodeTL
----

.Manufacture Order Examples
[source]
----
C91 FG9 manufacture 50,000 missile-8
----

=== Mine Resources
A `mine` order instructs a MINING GROUP to start mining and refining resources from a deposit.

.Mine Order
[source]
----
ColonyID MiningGroupID mine Quantity DepositID
----

.Mine Order Examples
[source]
----
C16 MG27 mine 25,000 DP19
----

NOTE: This feels wrong.
Why include quantity here?

== Trade Activity Phase
NOTE: The market phase was removed because players abused it.
Is there a way to monitor/prevent that?

All orders in the Trade Activity phase are executed in the order that they're entered in the orders file.

All transactions in a market or trade station require the buyer to pay a 1% commission.
The commission is paid to the controlling player of the trade station or kept by the market for its own use.

NOTE: All players must pay the same commission at markets and trade stations.
There should be a way to charge different commissions in different locations and for different players.

=== Establish Trade Station Order
An `establish` order changes the function of an existing Orbital Colony to Trade Station.
This order is valid only if the colony is an Orbital Colony,
no smaller than 3,000 EMUs,
and has no factories or mines installed.

When a new trade station is established,
all ships from the controlling player's race are granted trade rights.

.Establish Trade Station Order
[source]
----
establish trade-station ColonyID Percentage?
----

The Percentage in the order establishes the base commission rate.
It is optional and defaults to 1% (the standard commission rate).
If included, it must be 1% or the order will be rejected.

.Establish Trade Station Order Examples
[source]
----
establish trade-station S200     ; change S200 to a trade station charging the standard commission
establish trade-station S200 1%  ; change S200 to a trade station charging 1% commission
----

=== Grant Trade Rights Order
A `grant` order allows any ship belonging to a race to engage in trade at a market or trade station.
The permission remains in place until explicitly revoked.

.Grant Trade Rights Order
[source]
----
grant trade-rights SpeciesID ColonyID
----

To grant trade rights to all players, issue the order with "*" as the species identifier.

To grant trade rights to all markets and trade stations, issue the order with "*" as the colony identifier.

.Grant Trade Rights Order Examples
[source]
----
grant trade-rights SP138 S200  ; allow player SP138 to trade at station S200
grant trade-rights SP2   *     ; open up all markets to SP2
grant trade-rights *     S201  ; open up S201 to all players
grant trade-rights *     *     ; open up all markets to all players
----

=== Revoke Trade Rights Order
A `revoke` order prohibits any ship belonging to a race to engage in trade at a market or trade station.
The prohibition remains in place until the controlling player grants trade rights again.

.Revoke Trade Rights Order
[source]
----
revoke trade-rights SpeciesID ColonyID
----

To revoke trade rights from all players, issue the order with "*" as the species identifier.

To revoke trade rights from all markets and trade stations, issue the order with "*" as the colony identifier.

.Revoke Trade Rights Order Examples
[source]
----
revoke trade-rights SP138 S200  ; prohibit player SP138 from trading at station S200
revoke trade-rights SP2   *     ; close all markets to SP2
revoke trade-rights *     S201  ; close S201 to all players
revoke trade-rights *     *     ; close all markets to all players
----

=== Advertise Order
.Advertise Order
[source]
----
SystemID #Orbit advertise QuotedText QuotedText?
----

.Advertise Order Examples
[source]
----
8/4/3  #6 advertise "Stay away from my moons" "Jinsei"
3/7/9A #6 advertise "Fresh moon rocks for sell next turn"
----

=== Sell Order
.Sell Order
[source]
----
SystemID #Orbit sell Quantity UnitTL Number
----

The amount is always in GOLD units.

.Sell Order Examples
[source]
----
8/4/3  #6 sell 4 space drive-3       0.2
3/7/9A #6 sell 1 tech-4        800,000
----

=== Buy Order
.Buy Order
[source]
----
SystemID #Orbit buy Quantity UnitTL Number
----

The amount is always in GOLD units.

.Buy Order Examples
[source]
----
8/4/3  #6 buy 25,000 structural         0.01
3/7/9A #6 buy      1 tech-6     1,000,000
----

== Survey Phase
All orders in the Survey phase are executed in the order that they're entered in the orders file.

=== Probe Order
A `probe` order instructs a ship to conduct a detailed survey of a planet.

Probes are not actual units;
they use the ship's sensors to actively scan and analyze orbits, planets, colonies, and ships.

[[a-probe-chart]]
.Probe Chart
|===
|Unit-TechLevel|Probes per SENSOR unit per TURN|FUEL units used per PROBE per TURN

|sensor-1 >|1 >|0
|sensor-2 >|2 >|0
|sensor-3 >|3 >|0
|sensor-4 >|4 >|0
|sensor-5 >|5 >|0
|sensor-6 >|6 >|0
|sensor-7 >|7 >|0
|sensor-8 >|8 >|0
|sensor-9 >|9 >|0
|sensor-10 >|10 >|0
|===

.Probe Order
[source]
----
ShipID probe #Orbit #Orbit...
----

NOTE: This doesn't allow for systems with multiple stars.
Consider accepting Star#Orbit in those systems.

To probe all planets orbiting the current star
issue the order with "*" as the orbit number.
(This is not the same as "probe all orbits"!)

.Probe Order Examples
[source]
----
S28 probe #6        ; probe the planet in the 6th orbit
S31 probe #2 #4 #5  ; probe the planets in the 2nd, 4th, and 5th orbits
S42 probe *         ; probe all the planets orbiting the current star
----

=== Survey Order
A `survey` order instructs 1 PROFESSIONAL unit to pilot 1 TRANSPORT to undertake a detailed survey of a planet.
The survey takes one turn to complete.

Because the survey requires a transport, it will use fuel.

[[a-survey-fuel-cost-chart]]
.Survey Fuel Cost
|===
|Unit-TechLevel|Fuel units used per Survey per Turn

|transport-1 >|0.1
|transport-2 >|0.4
|transport-3 >|0.9
|transport-4 >|1.6
|transport-5 >|2.5
|transport-6 >|3.6
|transport-7 >|4.9
|transport-8 >|6.4
|transport-9 >|8.1
|transport-10 >|10
|===

.Survey Order
[source]
----
ShipID survey TransportTL #Orbit
----

.Survey Order Examples
[source]
----
S23 survey transport-5 #3  ; ship S23 will survey the planet in the 3rd orbit
----

NOTE: This should probably just automatically use the smallest transport available.

=== Report Step
A probe will report the following information for each planet:

. Habitability Number
. Natural Resource Deposits
.. DepositID
.. Resource Type
.. Approximate quantity
. Open Colonies
.. ColonyID
.. EMU
.. Presence of Market
. Enclosed Colonies
.. ColonyID
.. EMU
. Orbital Colonies
.. ColonyID
.. EMU
.. Presence of Trade Station
. Ships
.. ShipID
.. EMU

The "approximate" mass or quantity is the log~10~ (rounded down) of the true amount.

Each survey will report the following information:

. Natural Resource Deposits
.. DepositID
.. Resource Type
.. Quantity
.. Location
.. Mining Difficulty

== Espionage
All orders in the Espionage phase are executed in the order that they're entered in the orders file.

=== Convert Rebels Order
.Convert Rebels Order
[source]
----
ColonyOrShipID Quantity convert
----

.Convert Rebels Order Examples
[source]
----
C38 110 convert
----

=== Counter Espionage Order
.Counter Espionage Order
[source]
----
ColonyOrShipID counter
----

.Counter Espionage Order Examples
[source]
----
C38 counter
----

=== Incite Rebellion Order
.Incite Rebellion Order
[source]
----
SpeciesID ColonyOrShipID Quantity incite
----

.Incite Rebellion Order Examples
[source]
----
S2 C54 100 incite
----

=== Information Order
.Information Order
[source]
----
SpeciesID ColonyOrShipID Quantity information
----

.Information Order Examples
[source]
----
S2 C54 900 information
----

=== Suppress Foreign Spies Order
.Suppress Foreign Spies Order
[source]
----
ColonyOrShipID Quantity suppress
----

.Suppress Foreign Spies Order Examples
[source]
----
C38 85 suppress
----

=== Surveil Rebels Order
.Surveil Rebels Order
[source]
----
ColonyOrShipID surveil
----

.Surveil Rebels Order Examples
[source]
----
C38 surveil
----

== Ship Movement Phase
All orders in the Ship Movement phase are executed in the order that they're entered in the orders file.
After all orders have been executed, Sensor reports are generated.

There are three types of jumps.
Interplanetary jumps move the ship between orbits around the current star.
Intersystem jumps move the ship between orbits of the stars in the current system.
Interstellar jumps move the ship between systems.
In an interstellar jump, the ship will always arrive in the 11th orbit.
When jumping to a system that has multiple stars, the target coordinates must include the star.

=== Jump Order
A `jump` order instructs a ship to engage its hyper-drive engines and move to a new system or a new orbit around the current star.

The destination must be a system, an orbit around the current star, or an orbit in the current system.

The destination coordinates are specified as #Orbit for an interplanetary jump.
They're specified as StarID#Orbit for an intersystem jump.
And as the SystemID for an interstellar jump.

[[a-hyper-drive-range-chart]]
.Hyper-drive Range
|===
|Unit-TechLevel|Maximum distance per JUMP|Maximum Capacity per UNIT per JUMP

|hyper-drive-1|1 light year|1,000 MUs
|hyper-drive-2|2 light years|2,000 MUs
|hyper-drive-3|3 light years|3,000 MUs
|hyper-drive-4|4 light years|4,000 MUs
|hyper-drive-5|5 light years|5,000 MUs
|hyper-drive-6|6 light years|6,000 MUs
|hyper-drive-7|7 light years|7,000 MUs
|hyper-drive-8|8 light years|8,000 MUs
|hyper-drive-9|9 light years|9,000 MUs
|hyper-drive-10|10 light years|10,000 MUs
|===

When calculating capacity for ships with multiple engines,
use the lowest Tech Level of all engines,
then multiply by the total number of engines.

WARNING: If the total MUs of the ship (including hull and engines!)
exceeds the capacity of the engines,
it will consume the fuel but not move from its current location.
This is borked.

NOTE: The system does not idle engines that are not needed to make a jump.
It should.

[[a-jump-fuel-cost-chart]]
.Jump Fuel Cost
|===
|Kind|FUEL units per UNIT per JUMP

|Interplanetary|4
|Intersystem|8
|Interstellar|40 * distance (in light years) jumped
|===

Intersystem jumps require twice the fuel of interplanetary jumps because the ship must first jump to the 11th orbit before jumping to the final destination.

If the ship is already in the 11th orbit of a system with multiple stars (it just jumped in, for example),
the jump order must be in the intersystem format,
but the fuel will be used at the interplanetary rate.

NOTE: That's not implemented yet.

.Jump Order
[source]
----
jump ShipID Coordinates
jump ShipID #Orbit
jump ShipID StarID#Orbit
----

.Jump Order Examples
[source]
----
jump S79 #6        ; (interplanetary) move S79 to orbit 6 of the current star
jump S81 B#2       ; (intersystem)    move S80 to orbit 2 of star B in the current system
jump S77 4/6/10    ; (interstellar)   move S77 to system 4/6/10, orbit 11
jump S78 8/3/9B    ; (interstellar)   move S78 to system 8/3/9 , orbit 11 of star B
----

=== Sensor Report Step
Active sensors on a ship automatically report some basic information each turn.
The report is generated in this step, which always happens last in the Ship Movement Phase.

Active sensors consume fuel during this step each turn.

[[a-sensor-fuel-cost-chart]]
.Sensor Fuel Cost
|===
|Unit|Fuel units per Unit per survey per Turn

|Sensor >|0.5 * TL
|===

NOTE: There is no way to turn off sensors to save on fuel.

Ship sensors automatically report the following information:

. Orbit and Kind of Planets
. Number of ships in each orbit
.. Approximate mass of each ship
. Number of orbital colonies in each orbit
.. Approximate mass of each orbital colony
.. Approximate production (tonnage) of each orbital colony

The "approximate mass" is the log~10~ (rounded down) of the true quantity.

== Draft Phase
1 PROFESSIONAL unit is required to train up to 100 trainee units.
5% of trainees graduate to ??? each TURN.
TODO: This is not the right phase.

The total number of UNSKILLED WORKER units drafted must not exceed the number of available SOLDIER units.

There is no limit on the number of SOLDIER units that may be disbanded per TURN.

=== Draft Order
.Draft Professionals Order
[source]
----
ColonyOrShipID draft Quantity professional
----

.Draft Professionals Order Examples
[source]
----
S1 draft   3,000 professional
----

.Draft Soldiers Order
[source]
----
ColonyOrShipID draft Quantity soldier
----

.Draft Soldiers Order Examples
[source]
----
C8 draft 16,000 soldier
----

=== Disband Order
.Disband Professionals Order
[source]
----
ColonyOrShipID disband Quantity professional
----

.Disband Professionals Order Examples
[source]
----
C8 disband 6,000 professional
S1 disband     * professional
----

.Disband Soldiers Order
[source]
----
ColonyOrShipID disband Quantity soldier
----

.Disband Soldiers Order Examples
[source]
----
C8 disband 6,000 soldier
S1 disband     * soldier
----

== Pay and Ration Phase
All orders in the Ship Pay and Ration phase are executed in the order that they're entered in the orders file.

=== Pay Order
A `pay` order changes the amount of pay (in consumer goods) each population unit receives per turn.

The base pay for populations units is per the following chart:

[[a-base-pay-chart]]
.Base Pay Chart
|===
|CODE|Pay per UNIT per TURN|Pay when SHIP CREW

|CONSTRUCTION WORKER|0.500 CONSUMER GOODS|N/A
|PROFESSIONAL|0.375 CONSUMER GOODS|0.01 GOLD
|SOLDIER|0.250 CONSUMER GOODS|0.005 GOLD
|SPY|0.625 CONSUMER GOODS|N/A
|UNEMPLOYABLE|0.000 CONSUMER GOODS|N/A
|UNSKILLED WORKER|0.125 CONSUMER GOODS|N/A
|===

Only crew members receive pay when on a ship.
The crew will be paid in gold credits instead of goods.
They will exchange the credits for goods when at a colony controlled by their place or a market where they have trade rights.

WARNING: This can cause gold to transfer to another player unexpectedly.
Unscrupulous merchants will keep over-priced consumer goods on hand to exchange for gold.

Passengers (or cargo if in cryo-sleep) are not paid - they receive food but forfeit their normal pay of consumer goods.

.Pay Order
[source]
----
pay ColonyOrShipID PopulationUnitID Percentage
----

To change the rate for all units, regardless of location, issue the order with "*" as the ColonyOrShipID.

.Pay Order Examples
[source]
----
pay S38 professional 100%  ; reset  pay to base rate
pay  *  soldier       50%  ; change pay for all soldiers
pay S38 unskilled     90%  ; change pay to  90% of base rate
pay C27 unskilled    110%  ; change pay to 110% of base rate
pay S38 spy          115%  ; change pay to 115% of base rate
----

In the example, the player is paying UNSKILLED WORKER units more on colony C27 than she is on ship S38.

==== Ship Population
The crew of a ship consists of PROFESSIONAL and SOLDIER units.
Non-crew are PASSENGERS (or, potentially, cargo if in cryo.)

[[a-ship-crew-pay-chart]]
.Ship Crew Pay
|===
|CODE|Pay per UNIT per TURN|FOOD per UNIT per TURN

|PROFESSIONAL|0.01 GOLD|Per rationing orders
|SOLDIER|0.005 GOLD|Per rationing orders
|PASSENGER|N/A/|Per rationing orders
|===

When the ship docks at its home planet or any trade station,
the crew will exchange their accumulated GOLD for CONSUMER GOODS.

Passengers are never paid while being transported,
but they do receive a ration of FOOD every TURN per the ship's orders.

==== General Population
[[a-general-population-pay-chart]]
.General Population Pay
|===
|CODE|People in UNIT|Pay per UNIT per TURN

|CONSTRUCTION WORKER|200|0.500 CONSUMER GOODS
|PROFESSIONAL|100|0.375 CONSUMER GOODS
|SOLDIER|100|0.250 CONSUMER GOODS
|SPY|200|0.625 CONSUMER GOODS
|UNEMPLOYABLE|100|0.000 CONSUMER GOODS
|UNSKILLED WORKER|100|0.125 CONSUMER GOODS
|===

NOTE: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

=== Ration Order
.Ration Order
[source]
----
ColonyOrShipID ration Percentage
----

[[a-base-ration-chart]]
.Food Ration
|===
|CODE|People in UNIT|Base FOOD per UNIT per TURN|Minimum FOOD per UNIT per TURN

|CONSTRUCTION WORKER|200|0.5 FOOD units|0.125 FOOD units
|PROFESSIONAL|100|0.25 FOOD units|0.0625 FOOD units
|SOLDIER|100|0.25 FOOD units|0.0625 FOOD units
|SPY|200|0.5 FOOD units|0.125 FOOD units
|UNEMPLOYABLE|100|0.25 FOOD units|0.0625 FOOD units
|UNSKILLED WORKER|100|0.25 FOOD units|0.0625 FOOD units
|===

NOTE: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

.Ration Order Examples
[source]
----
S6 ration 50%
----

== Rebellion
REBEL units represent the number of rebels.
They are not treated as a separate group.

The rebel militia consists of 10% of the rebel population.
These are the members that are ready and willing to engage in open rebellion.

== Rebel Increase Step
People become rebels when under-paid and/or starving.

[[a-rebel-quality-of-life-factors-chart]]
.Quality of Life Factors
|===
|Factor|Increase

|Starvation >|30%
|Under Fed >|15%
|Under Paid >|15%
|Foreign Influence|See the spy tables
|===

=== Rebel Decrease Step
Once a rebel, almost always a rebel.

TODO: Add chart showing how to pay off rebels to return to loyal members of the state.

=== Open Rebellion Step
Open rebellion must be checked for every turn using the following chart:

[[a-rebellion-chance-chart]]
.Rebellion Chance
|===
|Ratio of Soldiers to Militia|Chance of open rebellion|Committment of rebellion

|6:1 >|0% >|0%
|5:1 >|5% >|5%
|4:1 >|10% >|10%
|3:1 >|25% >|30%
|2:1 >|50% >|75%
|1:1 >|100% >|90%
|===

A rebellion will end when the ratio of soldier to rebel militia units is greater than 6 to 1 (or vice versa).
(NB - based on the surrender logic in combat.)

NOTE: It is possible for both sides to surrender at the same time?

=== Independence Check Step
The colony or ship will declare its indepedence if the soldiers surrender.

An independent colony, if it has factories or mines, will seek out trade stations to sell their goods and purchase needed raw materials.

An independent ship will support itself via raids or hiring out as mercenaries.

TODO: Details on what becomes of the winners and losers.

== Naming and Control Phase
All orders in the Naming and Control phase are executed in the order that they're entered in the orders file.

=== Control Order
.Control Order
[source]
----
SpeciesID control SystemID #Orbit
----

.Control Order Examples
[source]
----
SP2 control 2/4/6 #9
----

=== Name Order
.Name Order
[source]
----
ColonyID  name                 QuotedString
ShipID    name                 QuotedString
SpeciesID name SystemID #Orbit QuotedString
----

.Name Order Examples
[source]
----
C39 name            "Mudbomb"
S52 name            "Mudflea"
SP9 name 5/10/15 #2 "Mudball"
----

=== Un-Control Order
.Uncontrol Order
[source]
----
SpeciesID uncontrol SystemID #Orbit
----

.Uncontrol Order Examples
[source]
----
SP2 uncontrol 2/4/6 #9
----

=== Grant Colonization Rights Order
A `grant` order allows any ship belonging to a race to set up a colony on the planet.
The permission remains in place until explicitly revoked.
The revocation must happen before the player has started building.

.Grant Colonization Rights Order
[source]
----
grant colonization-rights SpeciesID SystemID #Orbit
----

To grant colonization rights to all players, issue the order with "*" as the species identifier.

.Grant Colonization Rights Order Examples
[source]
----
grant colonization-rights SP138 12/9/8   #1
grant colonization-rights SP2   6/9/8B   #4
grant colonization-rights *     29/19/28 #3
----

=== Revoke Colonization Rights Order
A `revoke` order prohibits any ship belonging to a race from setting up a colony on the planet.
The prohibition remains in place until the controlling play grants colonization rights again.
The revocation must happen before the player has started building.

.Revoke Colonization Rights Order
[source]
----
revoke colonization-rights SpeciesID SystemID #Orbit
----

To revoke colonization rights from all players, issue the order with "*" as the species identifier.

.Revoke Colonization Rights Order Examples
[source]
----
revoke colonization-rights SP138 12/9/8   #1
revoke colonization-rights SP2   6/9/8B   #4
revoke colonization-rights *     29/19/28 #3
----

== Birth Phase
The changes to population due to births are calculated in this phase.

The birth rate ranges from 0.25% to 2.5% of the population.
The exact number is determined by quality of life.
Pay rates, food rations, open spaces, and civil strife are all factored in.

Births are computed each TURN.
The crew and passengers on a ship are ignored when calculating the population increase.
All birth increases accumulate to the UNEMPLOYABLE population.

NOTE: Future rules will consider cloning.
It is not currently an option.

== Training Phase
The changes to population due to training are calculated in this phase.

All orders in the Training phase are executed in the order that they're entered in the orders file.
After all orders have been executed, the Job Corp step is executed.

There are two types of training: training (apprenticeship) and Job Corps.

Attrition happens automatically; the player must issue orders to train workers.

=== Train Order
A `train` order instructs PROFESSIONAL units to begin training UNSKILLED WORKER units.

A PROFESSIONAL unit may train up to 100 UNSKILLED WORKER units per TURN.

The trainees are unavailable for use until they have graduated from training.
They graduate at a rate of 5% per TURN.
After graduation, they are moved to the PROFESSIONAL population.

.Train Professional Order
[source]
----
train ColonyOrShipID Quantity professional
----

.Train Professional Order Examples
[source]
----
train S13 15,400 professional  ; assign 16 PROF units to train 154 UNSK units
----

=== Job Corps Step
The Job Corps trains UNEMPLOYABLE units to become UNSKILLED WORKER units.
The Corps is activated automatically when the percentage of UNEMPLOYABLE units is reaches 30% of the total population.
At the end of each turn that it is active, the Corps will move 2% of the UNEMPLOYABLE units to UNSKILLED WORKER units.

== Retirement Phase
The changes to population due to retirement are calculated in this phase.

5% of SOLDIER units retire each YEAR.
(TODO: convert this to per TURN.)
Upon retirement, SOLDIER units become PROFESSIONAL units.
This happens automatically; the player can not control the number of retirees.

== Death Phase
The changes to population due to deaths from starvation and natural causes are calculated in this phase.

=== Starvation
Deaths from starvation are computed each TURN.

Starvation takes place when the rationed FOOD amount is less than 0.0625 of a FOOD unit per POPULATION unit.
When that happens, the following formula determines how many POPULATION units starve.

    S = (M - R) / M

Where M is the minimum ration from the Food Ration Chart,
R is the actual ration,
and S is the fraction of the population that starves.

TODO: Convert this to use percentages instead of fractions of FOOD units.

=== Natural Causes
Deaths from natural causes are computed each TURN.
They are computed after deaths from starvation.

[[a-natural-death-rate-chart]]
.Natural Death Rate
|===
|CODE|Deaths from Natural Causes per TURN

|CONSTRUCTION WORKER|0.0700%
|PROFESSIONAL|0.0625%
|SOLDIER|0.0750%
|SPY|0.0775%
|UNEMPLOYABLE|0.0625%
|UNSKILLED WORKER|0.0625%
|===

TIP: Soldiering, spying, and construction are dangerous activities;
that's why the death rate is higher for those groups.

== Research Phase
Changes to the tech level for a colony or ship are determined in this phase.

=== Applied Research Step
[[a-research-chart]]
.Research Chart
|===
|Technological Level|Research Points Required|Total Research Points Required
|1|N/A|N/A
|2|100,000|100,000
|3|200,000|300,000
|4|400,000|700,000
|5|800,000|1,500,000
|6|1,600,000|3,100,000
|7|3,200,000|6,300,000
|8|6,400,000|12,700,000
|9|12,800,000|25,500,000
|10|25,600,000|51,100,000
|===

WARNING: Applied Research happens before Transferred Research.

=== Transferred Research Step
In this step, changes to the tech level from research bought or shipped to the colony are applied.

Note that a ship can't transfer research from a higher tech level.
(This is weird.)
A SHIP-4 could transfer TECH-1, TECH-2, TECH-3, or TECH-4.
It could not transfer TECH-5 or higher.

A ship may never gain more than a single tech level in a turn.
It is not allowed to skip tech levels.

A colony may gain multiple tech levels in a single turn,
but it may never skip a level.
For example, a colony with TECH-2 is visited by a ship carrying TECH-4.
The colony will not be able to apply the TECH-4 nor can it store the TECH-4 for future use.

If the same colony were visited by a ship carrying TECH-3 and TECH-4,
it would be able to use the TECH-3 to raise its level,
then use the TECH-4.

== Cleanup Phase
Excess fuel is moved to storage.
If there is not enough storage available on the colony or ship, excess fuel is lost.

== News Service Phase
Each news service is updated with the turn's
* Arrivals
* Departures
* Combat
* Transactions
* Advertisements

The New Service is always available to the controlling player.
Ships that have trading rights with the market may use it only while in the same system.

[appendix]
== Terms

anti-missile::
Anti-missile units are used in combat to destroy transports, assault-craft, and missiles.
The chance of an anti-missile destroying the object depends on the Tech Level of the missile-launcher used.
They can not be taken apart and packed to save space on a ship or colony.

assault-craft::
Assault-craft units are used in combat to attack ground targets (soldiers and military robots) and other assault-craft.
They can not be taken apart and packed to save space on a ship or colony.

assault-weapon::
Assault-weapon units are used by soldiers and military-robots to attack ground targets (soldiers and military robots) and assault-craft.
They can not be taken apart and packed to save space on a ship or colony.

automation::
Automation units are used to replace unskilled workers in factories, mines, and farms.
They may also be used to replace unskilled workers in construction crews.
They can be taken apart and rendered inoperable to save space on a ship or colony.

colony::
A colony is not a unit;
it is an alias for enclosed colony, open colony, or orbital colony.

construction crew::
Construction crew units combine professional units and unskilled worker units into a crew that can assemble and dis-assemble other units.
Construction crew units can also recycle other units.
Recycling converts a percentage of a unit back into metallics units and non-metallics units.

consumer-goods::
Consumer-goods units are used to pay population units and to trade with other nations.
Consumer-goods do not have a Tech Level associated with them.
They can not be taken apart and packed to save space on a ship or colony.

enclosed colony::
An enclosed colony is located on the surface of a non-habitable planet.
The colony requires life-support units to sustain the population units.

energy-shield::
Energy-shield units absorb damage from energy-weapons in combat.
They can be taken apart and rendered inoperable to save space on a ship or colony.

energy-weapon::
Energy-weapon units are used in combat to attack ships and colonies.
They can be taken apart and rendered inoperable to save space on a ship or colony.

factory::
Factory units are used to produce all units in the game, except for food, fuel, gold, metallics, non-metallics, and population.
They can be taken apart and rendered inoperable to save space on a ship or colony.

farm::
Farm units are used to produce all food units in the game.
They can be taken apart and rendered inoperable to save space on a ship or colony.

food::
Food units are used to feed population units.
They are produced only by farm units.
They can not be taken apart and packed to save space on a ship or colony.

fuel::
Fuel units are used to power all units in the game (except for population units).
Fuel units are produced only by mine units.
They can not be taken apart and packed to save space on a ship or colony.

gold::
Gold units are used to pay the crews of ships and to trade with other nations.
Gold units are produced only by mine units.
They can not be taken apart and packed to save space on a ship or colony.

hyper-drive::
Hyper-drive units are used to transport ships between systems.
They are not used to move between the stars in a system with multiple stars.
They can be taken apart and rendered inoperable to save space on a ship or colony.

life-support::
Life-support units are used to sustain population units in enclosed colonies and on ships.
They can be taken apart and rendered inoperable to save space on a ship or colony.

light-structural::
Light-structural units are used to build the hull and/or infrastructure of ships and colonies.
They replace standard structural units on a one-for-one basis in construction.
These units may only be manufactured in an orbital colony or on a ship.
They can be taken apart and rendered inoperable to save space on a ship or colony.

modular-engineering-kit::
Modular-engineering-kit units contain the panels, struts, beams, and other components used to build colonies and ships.
There are three types, the standard (MEK-1), a lower mass version (MEK-2), and an extra low mass version (MEK-3).
They can be taken apart and rendered inoperable to save space on a ship or colony.

WARNING: MEK units are intended to replace structural, light-structural, and super-light-structural units in the future.
They are not currently used because their Tech Level doesn't play well with the current rules.

metallics::
Metallic units are consumed by factories in the manufacturing process.
Metallic units are produced only by mine units.
They can not be taken apart and packed to save space on a ship or colony.

military-robot::
Military-robot units are used in combat to attack ground targets (soldiers and military robots) and assault-craft.
They can not be taken apart and packed to save space on a ship or colony.

military-supply::
Military-supply units are used by soldier units and military robot units in combat.
These units are consumed during each round of combat.
If the soldier unit or military robot unit runs out of military-supply units, it will disengage from combat.
They can not be taken apart and packed to save space on a ship or colony.

mine::
Mine units are used to produce fuel, gold, metallics, and non-metallics units.
All mine units must be assigned to a deposit of natural resources in order to operate.
They will produce according to the characteristics of the deposit (kind and yield).
They can be taken apart and rendered inoperable to save space on a ship or colony.

missile::
Missile units are used in combat to attack ships or colonies.
The chance of a missile striking the target depends on the Tech Level of the missile-launcher used.
Missile units may be destroyed by anti-missile units before they have a chance to damage the target.
They can not be taken apart and packed to save space on a ship or colony.

missile-launcher::
Missile-launcher units are used in combat to launch both missile units and anti-missile units.
They can be taken apart and rendered inoperable to save space on a ship or colony.

open colony::
An open colony is located on the surface of a habitable planet.
The colony does not require life-support units to sustain the population units.

orbital colony::
An orbital colony is located in orbit around a planet.
The colony requires life-support units to sustain the population units.

order::
An order can be issued to any ship or colony that a player controls.

ore::
Ore is not a unit;
it is an alias for metallics units or non-metallics units.

population::
Population units are not units;
they are an alias for are the people of the nation.
They are categorized as professionals, soldiers, unskilled workers, and unemployed.
Population units are not manufactured; increases happen through the birth rules.
They can be destroyed in combat, by starvation, lack of life support, or through natural causes.
They can not be taken apart and packed to save space on a ship or colony.

professional::
Professional units are people that manage factories, farms, mines, colonies, and ships.
They can be trained to lead construction crews and spy teams, too.
Professional units are paid with consumer-goods units when they're in a colony;
when they're crewing a ship they are paid with gold units.
As with all other population units, they use the birth and death rules; they are never "manufactured,"
and they can not be taken apart and packed to save space on a ship or colony.

non-metallics::
Non-metallic units are consumed by factories in the manufacturing process.
Non-metallic units are produced only by mine units.
They can not be taken apart and packed to save space on a ship or colony.

rebel::
Rebel units are a percentage of the population on a ship or colony that is dissatisfied with the current governance.
They may engage in acts of sabotage or open warfare.

sensor::
Sensor units are used to passively scan a system after a hyper-drive jump and also to probe a planet in a system.
They can be taken apart and rendered inoperable to save space on a ship or colony.

soldier::
Soldier units are people that are trained for combat and policing.
They can be trained to work in spy teams, too.
When they retire, they become professional units.
Soldier units are paid with consumer-goods units when they're in a colony;
when they're crewing a ship they are paid with gold units.
As with all other population units, they use the birth and death rules; they are never "manufactured,"
and they can not be taken apart and packed to save space on a ship or colony.

space-drive::
Space-drive units are used to transport ships between planets in a star system.
They are also used to transport ships between stars in a system with multiple stars.
Additionally, the ratio of the space-drive units' thrust to the ship's determines how quickly the ship moves in combat.
They can not be taken apart and packed to save space on a ship or colony.

spy team::
Spy team units combine professional units and soldier units into a team that can perform espionage,
assassinations, convert loyal population units, and incite rebels into open warfare.

structural::
Structural units are used to build the hull and/or infrastructure of ships and colonies.
These units may only be manufactured in an enclosed colony or open colony.
They may not be manufactured on an orbital colony or on a ship.
They can be taken apart and rendered inoperable to save space on a ship or colony.

super-light-structural::
Super-light-structural units are used to build the hull and/or infrastructure of ships and colonies.
They replace standard structural units on a one-for-one basis in construction.
These units may only be manufactured in an orbital colony or on a ship that is Tech Level 6 or higher.
They can be taken apart and rendered inoperable to save space on a ship or colony.

transport::
Transport units are used to transfer cargo or population between ships and/or colonies.
In combat, transport units are used to transfer soldier units and military-robot units between ships and/or colonies.
They can not be taken apart and packed to save space on a ship or colony.

unemployed::
Unemployed units are the people that are not professional, soldier, or unskilled workers.
They're tagged as "unemployed" because the government does not pay them with consumer-goods units as it does with the other population units.
As with all other population units, they use the birth and death rules; they are never "manufactured,"
and they can not be taken apart and packed to save space on a ship or colony.

unskilled worker::
Unskilled worker units are people that do the work in factories, farms, mines, colonies, and ships.
They can be trained to become professional units or work in construction crews.
Unskilled worker units are paid with consumer-goods units when they're in a colony;
when they're crewing a ship they are paid with gold units.
As with all other population units, they use the birth and death rules; they are never "manufactured,"
and they can not be taken apart and packed to save space on a ship or colony.

[appendix]
== Units

=== Population Units
[[a-population-units-summary-chart]]
.Population Units Summary
|===
|Unit|Code|Mass per Unit|Volume Per Unit

|professional|PRO >|1 MU >|1 EMU
|soldier|SOL >|1 MU >|1 EMU
|unskilled worker|USK >|1 MU >|1 EMU
|unemployed|UEM  >|1 MU >|1 EMU
|===

=== Farmed Units
[[a-farmed-units-summary-chart]]
.Farmed Units Summary
|===
|Unit|Code|Mass per Unit|Volume Per Unit|Notes

|food|FOOD >|6 MU >|1 EMU|Used to feed population
|===

=== Mined Units
[[a-mined-units-summary-chart]]
.Mined Units Summary
|===
|Unit|Code|Mass per Unit|Volume Per Unit|Notes

|fuel|FUEL >|1 MU >|1 EMU|Used to power manufactured units
|gold|GOLD >|1 MU >|1 EMU|Used for trade
|metallics|MTLS  >|1 MU >|1 EMU|Consumed in manufacturing; may be extracted from recycled units
|non-metallics|NMTL  >|1 MU >|1 EMU|Consumed in manufacturing; may be extracted from recycled units
|===

=== Manufactured Units
Manufactured units consist of tech units (which have properties that vary with the Tech Level of the unit)
and non-tech units (the properties don't vary and Tech Level isn't tracked for the unit).

==== Non-Tech Units

[[a-non-tech-units-summary-chart]]
.Non-Tech Units Summary
|===
|Unit|Code|Mass per Unit|Volume Per Unit

|consumer-goods|CNGD >|0.6 MU >|1.000 EMU
|military-supply|MLTS >|0.04 MU >|0.04 EMU

|structural|STUN >|0.500 MU >|0.500 EMU
|light-structural|LTSU >|0.050 MU >|0.050 EMU
|super-light-structural|SLSU >|0.005 MU >|0.005 EMU
|===

==== Tech Units
Tech units require the Tech Level of the unit as part of the code and full name in orders.
For example, an `anti-missile` unit with Tech Level 5 (TL-5) has a code of `ANM-5` and a full name of `anti-missile-5`.

The Tech Level ranges from 1 to 10 for these units.

[[a-other-units-summary-chart]]
.Other Units Summary
|===
|Unit|Code|Mass per Unit|Fuel use per Turn

|anti-missile|ANM-TL >|4 * TL MU >|0
|assault-craft|ASC-TL >|5 * TL MU >|See Notes
|assault-weapon|ASW-TL >|2 MU >|0
|automation|AUT-TL >|4 * TL MU >|0
|energy-shield|ESH-TL >|50 * TL MU >|?
|energy-weapon|EWP-TL >|10 * TL MU >|See Notes
|factory|FCT-TL >|? MU >|?
|farm|FRM-TL >|? MU >|?
|hyper-drive|HDR-TL >|45 * TL MU >|See Notes
|life-support|LSP-TL >|8 * TL MU >|1 * TL
|modular-engineering-kit|MEK-TL >|? MU >|?
|military-robots|MLR-TL >|20 + 2 * TL MU >|0
|mine|MIN-TL >|? MU >|?
|missile|MSS-TL >|4 * TL MU >|0
|missile-launcher|MSL-TL >|25 * TL MU >|0
|sensor|SNR-TL >|40 * TL MU >|0.05 * TL
|space-drive|SDR-TL >|25 * TL MU >|See Notes
|transport|TPT-TL >|4 * TL MU >|See Notes
|===

Notes:

1. `assault-craft` units consume fuel only during combat.
They consume 0.1 * TL `fuel` units during each round trip they make in a combat round.
2. `energy-shield` units consume fuel only during combat.
They consume 10 * TL `fuel` units each combat round that they are used.
3. `energy-weapon` units consume fuel only during combat.
They consume 4 * TL `fuel` units each combat round that they are used.
4. `hyper-drive` units consume fuel only when they make a jump between systems.
They consume 40 `fuel` units per light year jumped.
5. `space-drive` units consume fuel only when they move between planets or during combat.
They consume TL^2^ `fuel` units each round of combat that they are used.
6. `transport` units consume fuel only when they are used to move cargo or to transport troops during combat.

[appendix]
== Orders

This section details the *orders* that *players* may issue.

[glossary]
ColonyID:: _ColonyID_ is a unique identifier for a colony.
It must start with the letter "C" followed by an _integer_.
Examples are C1, C50, C100.

ColonyOrShipID:: _ColonyOrShipID_ is either a _ColonyID_ or _ShipID_.
This is only used when the _order_ accepts either a colony or ship.
For example, a player may order S27 to raid S35 or C22.

DepositID:: _DepositID_ is a unique identifier for a resource deposit.
It must start with the letters "DP" followed by an _integer_.
Examples are DP1, DP100, DP10001.

FactoryCodeTL:: _FactoryCodeTL_ is composed of two parts separated by a dash.
The first part is the code for factory units.
The second part is the *TechLevel* of the factory unit.
Examples are FACTORY-1, FACTORY-3, FACTORY-9.

FactoryGroupID:: _FactoryGroupID_ is a unique identifier for a factory group.
It must start with the letters "FG" followed by an _integer_.
Examples are FG1, FG100, FG10001.

Integer:: _Integer_ is a whole number.
Examples are 0, 50, 100.

LootID:: _LootID_ is the name of a resource to target during a raid.
Examples are gold, fuel.

Number:: _Number_ is a real number or a whole number.
Examples are 0, 0.0, 50.2, 100.

MineCodeTL:: _MineCodeTL_ is composed of two parts separated by a dash.
The first part is the code for mining units.
The second part is the *TechLevel* of the mining unit.
Examples are MINE-1, MINE-3, MINE-9.

MiningGroupID:: _MiningGroupID_ is a unique identifier for a mining group.
It must start with the letters "MG" followed by an _integer_.
Examples are MG1, MG100, MG10001.

Percentage:: _Percentage_ is an _integer_ between 0 and 100 followed by a percent sign.
Examples are 0%, 50%, 100%.

PercentCommitted:: _PercentCommitted_ is a _percentage_.
It is TODO...

Quantity:: _Quantity_ is a whole number.
It must be greater than zero.
Examples are 1, 5,000, and 3,000,142.

ShipID:: _ShipID_ is a unique identifier for a ship.
It must start with the letter "S" followed by an _integer_.
Examples are S1, S50, S100.

TargetID:: _TargetID_ is either a _ColonyID_ or _ShipID_.
For example, a player may order S50 to support S27 in its attack against C22.

TechLevel:: _TechLevel_ is an integer in the range of 1..10.

UnitCodeTL:: _UnitCodeTL_ is composed of two parts separated by a dash.
The first part is the code for the unit.
The second part is the *TechLevel* of the unit.
Examples are MISSILE-2, HYPER-DRIVE-3, and ENERGY-SHIELDS-9.

[appendix]
== Charts and Tables

* <<a-base-pay-chart, Base Pay Chart>>
* <<a-base-ration-chart, Food Ration>>
* <<a-build-location-chart, Build Location Chart>>
* <<a-colony-distance-factor-chart, Colony Distance Factor>>
* <<a-combat-factor-chart, Combat Factor Chart>>
* <<a-combat-fuel-cost-chart, Combat Fuel Cost>>
* <<a-combat-thrust-factor-chart, Combat Thrust Factor (TF) Chart>>
* <<a-factory-fuel-cost-chart, Factory Fuel Cost>>
* <<a-factory-group-labor-cost-chart, Factory Group Labor Cost>>
* <<a-factory-location-chart, Factory Location>>
* <<a-factory-produced-units-chart, Factory Produced Units>>
* <<a-factory-production-required-materials-chart, Factory Production Required Materials>>
* <<a-factory-solar-power-availability-chart, Factory Solar Power Availability>>
* <<a-farm-fuel-cost-chart, Farm Fuel Cost>>
* <<a-farm-labor-cost-chart, Farm Labor Cost>>
* <<a-farm-location-chart, Farm Location>>
* <<a-farm-production-chart, Farm Production>>
* <<a-farm-solar-power-availability-chart, Farm Solar Power Availability>>
* <<a-farmed-units-summary-chart, Farmed Units Summary>>
* <<a-general-population-pay-chart, General Population Pay>>
* <<a-hyper-drive-range-chart, Hyper-drive Range>>
* <<a-jump-fuel-cost-chart, Jump Fuel Cost>>
* <<a-life-support-effect-chart, Life Support Effect>>
* <<a-life-support-fuel-cost-chart, Life Support Fuel Cost>>
* <<a-mine-fuel-cost-chart, Mine Fuel Cost>>
* <<a-mine-labor-cost-chart, Mine Labor Cost>>
* <<a-mine-location-chart, Mine Location>>
* <<a-mine-production-chart, Mine Production>>
* <<a-mined-units-summary-chart, Mined Units Summary>>
* <<a-mining-solar-power-availability-chart, Mine Solar Power Availability>>
* <<a-natural-death-rate-chart, Natural Death Rate>>
* <<a-non-tech-units-summary-chart, Non-Tech Units Summary>>
* <<a-operational-units-chart, Operational Units>>
* <<a-other-units-summary-chart, Other Units Summary>>
* <<a-phase-chart, Phase Chart>>
* <<a-population-units-summary-chart, Population Units Summary>>
* <<a-probe-chart, Probe Chart>>
* <<a-production-location-chart, Production Location Chart>>
* <<a-rebel-quality-of-life-factors-chart, Quality of Life Factors>>
* <<a-rebellion-chance-chart, Rebellion Chance>>
* <<a-research-chart, Research Chart>>
* <<a-sensor-fuel-cost-chart, Sensor Fuel Cost>>
* <<a-ship-crew-pay-chart, Ship Crew Pay>>
* <<a-structural-unit-summary-chart, Structural Unit Summary>>
* <<a-survey-fuel-cost-chart, Survey Fuel Cost>>
* <<a-transport-crew-chart, Transport Crew Chart>>
* <<a-transport-operations-chart, Transport Operations Chart>>

[appendix]
== Turn 0
Turn 0 lets players create their initial factory, farm, and mining groups.
This allows players to customize their manufacturing and mining base to their needs.

During Turn 0, players are permitted to issue orders only to the open colony on their home world.
The orders are limited to:

1. assembling factory groups
2. assembling farm groups
3. assembling mine groups

The assembled groups are treated as though they have been operational for a full year.
They will consume the necessary materials and produce a full year's output.

[appendix]
== To Do
1. Ships should have unskilled workers to move cargo and perform routine maintenance.
2. Soldiers should be required to operate energy weapons and missiled.

[index]
== Index
