= Wraith Reference Manual
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-04-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith Reference Manual (c) 2022 by Michael D Henderson

Wraith Reference Manual is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

TIP: This document is meant to be concise and definitive.
That makes it a terrible source for learning the game.
The User's Guide is the recommended source for getting started.

WARNING: This reference manual is the source of truth for the rules.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Organization
The reference manual presents rules in the sequence they would be processed during a game turn.

The chapter headings are the phases from the following chart:

.Phase Chart
|===
|Phase|Description

|Fuel Allocation|In this phase, fuel is allocated to units.
Fuel allocations are prioritized: life support is first, followed by farms, mines, then factories.
The allocation algorithm is naive and simple.
It attempts to allocate 100% of a unit's needs before moving to the next unit.
It never allocates proportionately.
|Life Support|Population changes due to life supoort are calculated.
|Farming Production|The farming production phase todo...
|Mining Production|The mining phase is used to extract resources from deposits and refine them into materials that can be used in the manufacturing phase.
|Manufacturing Production|The manufacturing production phase todo...
|Combat|The combat phase is used to project force against other player's assets.
|Set up|The set up phase is used to assemble new colonies and ships.
|Disassembly|This phase is used to disassembly operational units and make them ready to put into storage.
|Retool|The retool orders phase is used to todo...
|Mining Change|The mining change orders phase is used to todo...
|Transfer|The transfer phase is used to todo...
|Assembly|The assembly phase is used to manufacture items, mine resources, and assemble units from storage.
|Market|The market and trade station phase is used to process trade and barter orders.
|Survey|This phase surveys systems, planets, colonies, and ships.
Reports are todo...
|Survey Reports|This phase produces the probe and sensor reports.
Todo...
|Espionage|The espionage phase todo...
|Ship Movement|This is the only phase in which ships move.
|Draft|This phase applies draft orders to move workers between population unit types todo...
|Pay and Ration|This phase is used to pay the population and distribute food.
Pay is either gold (in the form of credits) or consumer goods.
The player may change the default pay and ration rates.
|Rebellion|This phase todo...
|Rebel Changes|In this phase, the rebel population changes are applied.
Todo...
|Control|In this phase, naming and control orders are todo...
|Birth|Population changes due to births are calculated.
|Training|Population changes due to training and apprenticeships are calculated.
|Retirement|Population changes due to retirement are calculated.
|Death|Population changes due to starvation and natural deaths are calculated.
|News|In this phase, reports for the "news services" are created todo...
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

== Fuel Allocation Phase
The number of FUEL units available to every colony and ship is calculated.

FUEL allocations are prioritized:

. LIFE SUPPORT units
. FARM units
. MINE units
. FACTORY units

Remaining FUEL is immediately moved to STORAGE.
If there are not enough STORAGE available on the colony or ship,
excess FUEL is lost.

FUEL units in STORAGE are available for use in the remaining phases.

TIP: FUEL units are only produced via mining.
They are not available for use until the TURN after they've been mined.
There are some rather complicated exceptions to this rule.

== Life Support Phase
The number of LIFE SUPPORT units that are ACTIVE are counted.

.Life Support Chart
|===
|CODE|FUEL per UNIT per TURN|Population units supported per UNIT per TURN

|LSU-1|1|1
|LSU-2|2|4
|LSU-3|3|9
|LSU-4|4|16
|LSU-5|5|25
|LSU-6|6|36
|LSU-7|7|49
|LSU-8|8|64
|LSU-9|9|81
|LSU-10|10|100
|===

Population that isn't supported is killed off in this phase.
The only exception are units that have been placed into cryo-sleep.

Casualties are distributed uniformly across all population groups.

LSU units must be ACTIVE for the entire turn to support population units.
If the units are shut down for any reason, the capacity will be recalculated and excess population killed off.
This includes sabotage, damage in combat, or a ship taking on too many passengers.

== Farming Production Phase
The number of FOOD units produced by active FARM units is calculated.
The food units are moved to local depots for temporary storage.

A FARM unit produces no FOOD units if it is INACTIVE.

A FARM unit produces no FOOD units the first TURN that it is ACTIVE.

=== Fuel
FARM units require FUEL to be ACTIVE.
If a FARM unit does not have a full allocation of FUEL,
it is INACTIVE for the current TURN.

.Farming Fuel Chart
|===
|CODE|FUEL per UNIT per TURN|Sunlight|Can use Solar Power?

|FARM-1|0.5|Natural|No
|FARM-2|1.0|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-3|1.5|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-4|2.0|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-5|2.5|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-6|6.0|Artificial|No
|FARM-7|7.0|Artificial|No
|FARM-8|8.0|Artificial|No
|FARM-9|9.0|Artificial|No
|FARM-10|10.0|Artificial|No
|===

If the FARM unit can use Solar Power, its FUEL cost drops to 0 FUEL units per TURN.

=== Labor
FARM units require labor to be ACTIVE.
If a FARM unit does not have a full allocation of labor,
it is INACTIVE for the current TURN.

.Farming Labor Chart
|===
|CODE|PROFESSIONAL Units|UNSKILLED WORKER Units

|FARM|1 per FARM unit|3 per FARM unit
|===

Farming automation units may replace a number of UNSKILLED WORKER units equal to their Tech Level.
For example, an AUTO-3 may replace 3 UNSKILLED WORKER units.

=== Shortages
Todo...

=== Production
If the FARM unit is ACTIVE this TURN and was active the prior TURN,
it will produce FOOD per the following chart.

.Farming Production Chart
|===
|CODE|Production per UNIT per YEAR

|FARM-1|100 FOOD
|FARM-2|40 FOOD
|FARM-3|60 FOOD
|FARM-4|80 FOOD
|FARM-5|100 FOOD
|FARM-6|120 FOOD
|FARM-7|140 FOOD
|FARM-8|160 FOOD
|FARM-9|180 FOOD
|FARM-10|200 FOOD
|===

1 FOOD unit will feed 4 population units and has a mass of 6 MASS units (MUs).
TODO: this is the wrong place for this information.

== Mining Phase
A MINE unit produces no raw material units if it is INACTIVE.

A MINE unit produces no raw material units the first TURN that it is ACTIVE.

=== Fuel
MINE units require FUEL to be ACTIVE.
If a MINE unit does not have a full allocation of FUEL,
it is INACTIVE for the current TURN.

.Mining Fuel Chart
|===
|CODE|Fuel per UNIT per TURN|Can use Solar Power?

|MINE|TL * 0.5|No
|===

If the MINE unit can use Solar Power, its FUEL cost drops to 0 FUEL units per TURN.

=== Labor
MINE units require labor to be ACTIVE.
If a MINE unit does not have a full allocation of labor,
it is INACTIVE for the current TURN.

.Mining Labor Chart
|===
|CODE|PROFESSIONAL Units|UNSKILLED WORKER Units

|MINE|1 per MINE unit|3 per MINE unit
|===

Note that mining automation units may replace UNSKILLED WORKER units at a TODO rate.

Mining automation units may replace a number of UNSKILLED WORKER units equal to their Tech Level.
For example, an AUTO-3 may replace 3 UNSKILLED WORKER units.

=== Shortages
Todo...

=== Production
If the MINE unit is ACTIVE this TURN and was active the prior TURN,
it will produce raw materials per the following chart.

.Mining Production Chart
|===
|CODE|Production per UNIT per YEAR

|MINE|100 * TL MASS UNITS (MU) of raw materials
|===

== Manufacturing Phase
The amount of finished goods produced by factory groups is calculated in this phase.

A FACTORY GROUP is a set of of FACTORY units assigned to work together to build a common finished good.

FACTORY units are the only units that can convert fuel and raw materials into finished goods.

A FACTORY unit produces no finished units if it is IDLE or INACTIVE.

FACTORY units that are not assigned to a FACTORY GROUP are INACTIVE (idle) - they will not manufacture any unit.

A FACTORY unit produces finished units the first TURN that it is ACTIVE.

A FACTORY unit produces finished units the last TURN that it is ACTIVE. 

FACTORY units manufacture (produce) all goods except

. Raw Materials -- GOLD, FUEL, METAL, and NON-METALLIC units
. FOOD units
. POPULATION units

If the FACTORY unit is ACTIVE this TURN and was active the prior TURN, it will produce finished goods per the production chart.
Otherwise, it will produce nothing.

=== Location
FACTORY units may be assembled only on COLONY units.
FACTORY units may not be assembled on SHIP units.
Players may not assemble FACTORY units anywhere other than a COLONY.

=== Groups
FACTORY units must be assigned to a FACTORY GROUP before they can be activated.
A FACTORY unit is INACTIVE if is it not assigned to a FACTORY GROUP.

=== Fuel
FACTORY units require fuel to be ACTIVE.
The fuel source may be solar power or FUEL units.

FACTORY units that are on orbiting colonies in orbits 1 through 5 use solar fuel.
These units require no other fuel source to operate at full capacity.

All other FACTORY units must use FUEL units per the following chart.

.Factory Fuel Chart
|===
|CODE|Fuel per UNIT per TURN|Can use Solar Power?

|FACT|TL * 0.5|Yes, if on Orbital Station in orbits 1..5
|===

Note: INACTIVE FACTORY units never consume FUEL units.

If a FACTORY GROUP does not have a full allocation of fuel, it will use the SHORTAGE rules for the current TURN.

=== Labor
FACTORY units require labor to be ACTIVE.
The amount of labor is determined by the total number of units in the FACTORY GROUP.

If a FACTORY GROUP does not have a full allocation of labor, it will use the SHORTAGE rules for the current TURN.

The efficiency of a FACTORY GROUP improves as more FACTORY units are added.
The following chart shows the number of labor units needed based on the total number of FACTORY units in the GROUP.

.Factory Group Labor Chart
|===
|CODE|Size|PROFESSIONAL units|UNSKILLED WORKER units

|FACTORY GROUP|1 - 4 FACTORY units|6 per FACTORY unit|18 per FACTORY unit
|FACTORY GROUP|5 - 49 FACTORY units|5 per FACTORY unit|15 per FACTORY unit
|FACTORY GROUP|50 - 499 FACTORY units|4 per FACTORY unit|12 per FACTORY unit
|FACTORY GROUP|500 - 4,999 FACTORY units|3 per FACTORY unit|9 per FACTORY unit
|FACTORY GROUP|5,000 - 49,999 FACTORY units|2 per FACTORY unit|6 per FACTORY unit
|FACTORY GROUP|50,000 - up FACTORY units|1 per FACTORY unit|3 per FACTORY unit
|===

Note: factory automation units may replace UNSKILLED WORKER units at a TODO rate.

Note: the ratio of UNSKILLED WORKER to PROFESSIONAL units is 3 to 1.

Players may rely on the inverse of this chart.
For example,
if the player allocates 3 PROFESSIONAL units and 9 UNSKILLED WORKER units to a FACTORY GROUP,
up to 4,999 FACTORY units may be activated in the group.
All excess FACTORY units in the group are INACTIVE that TURN.

=== Raw Materials
The manufacturing pipeline is abstracted into MASS units (MU) of raw materials input and finished goods output.
This allows factory groups to produce different goods.

Each FACT in a FACTORY GROUP requires raw materials to produce finished goods.
Every type of finished good requires a set of raw materials per the following chart:

.Production Raw Materials Chart
|===
|CODE|GOLD Units|FUEL Units|METALLIC Units|NON-METALLIC Units

|AMSL|0|0|2 * TL|2 * TL
|ATKC|0|0|3 * TL|2 * TL
|ATKW|0|0|1 * TL|1 * TL
|AUTO|0|0|2 * TL|2 * TL
|CGDS|0|0|.2|.4
|ENSH|0|0|25 * TL|25 * TL
|ENWP|0|0|5 * TL|5 * TL
|FACT|0|0|8 + TL|4 + TL
|FARM|0|0|4 + TL|2 + TL
|HDRV|0|0|25 * TL|20 * TL
|LFSP|0|0|3 * TL|5 * TL
|LSU|0|0|.01|.04
|MILR|0|0|10 + TL|10 + TL
|MILS|0|0|.02|.02
|MINE|0|0|5 + TL|5 + TL
|MSL|0|0|2 * TL|2 * TL
|MSLT|0|0|15 * TL|10 * TL
|SNSR|0|0|10 * TL|20 * TL
|SDRV|0|0|15 * TL|10 * TL
|SSU|0|0|.1|.4
|TRNS|0|0|3 * TL|1 * TL
|===

Each FACT in a FACTORY group can consume up to 5 MASS units (MUs) per TL per TURN in raw materials.

Example:
```
FACT-1 -> 1 TL * 5 MU/TL/turn ->  5 MU/turn
FACT-3 -> 3 TL * 5 MU/TL/turn -> 15 MU/turn
```

The FACTORY GROUP can consume the total of all FACT units in the group.

Example:
```
FG1098 has 123 FACT-1 and 318 FACT-3 units
  FACT-1 -> 123 units *  5 MU/turn/unit ->   615 MU/turn
  FACT-3 -> 318 units * 15 MU/turn/unit -> 4,770 MU/turn
FG1098 can consume a total of              5,385 MU/turn
```

If a FACTORY GROUP does not have a full allocation of raw materials, it will use the SHORTAGE rules for the current TURN.

=== Shortages
A FACTORY GROUP will be unable to produce its full output when there is a shortage of fuel, labor, or raw materials.

The FACTORY GROUP will use as much of its input fuel, labor, or raw materials as it can;
the excess units will be returned to the "central depot" for allocation in future turns.

=== Production
COLONY units are the only UNIT that may install FACT units and manufacture (produce) finished goods.
Players may not activate FACT units anywhere other than a COLONY.

Unless otherwise stated, it takes 4 TURNS (one YEAR) to manufacture a finished good.
Adding more FACT units to a FACTORY GROUP will consume more raw materials, which increases the amount of finished goods;
it will not reduce the amount of time needed to manufacture the finished goods.

== Combat Phase
All orders in the Combat phase are executed in the order that they're entered in the orders file.

Some units require FUEL to be used in combat.

.Combat Fuel Chart
|===
|CODE|FUEL use per UNIT per TURN|FUEL use per UNIT per COMBAT ROUND

|Assault Craft|0.1|N/A
|Energy Shield|N/A|TL * 4
|Energy Weapon|N/A|TL * 10
|Space Drive|N/A|TL^2^
|===

.Combat Thrust Factor (TF) Chart
|===
|CODE|Thrust Factor per UNIT per COMBAT ROUND

|Space Drive|TL^2^ * 1000
|===

The total thrust factors (TF) divided by the ship's total mass is the maximum number of space combat rings a ship may move in a single combat round.

The player has no control over any ship's movement in combat.

=== Bombard
The `bombard` order

```
ColonyOrShipID bombard ColonyID PercentCommitted
```

Examples:

=== Invade
The `invade` order

```
ShipID invade ColonyID PercentCommitted
```

Examples:

=== Raid
The `raid` order

```
ColonyOrShipID raid ColonyOrShipID PercentCommitted LootID
```

Examples:

=== Support
The `support` order

```
ColonyOrShipID support ColonyOrShipID TargetID PercentCommitted
```

Examples:

== Set up Phase
Set up orders are used to assemble a new COLONY or SHIP.

The order includes the list of material units for the assembly.
(This list is also known as the "bill of materials", or BOM.)
All materials must be present at the site prior to starting.

This order will span multiple lines since it specifies the list of materials.
The player must use the `end` keyword to terminate the order.

The BOM must include CONSTRUCTION WORKER units.
These units will assemble the colony or ship and will be returned once the assembly is complete.
While working, these units will draw FOOD from the site
(meaning the ship or colony they were transferred from).

The BOM must include STRUCTURAL (or LIGHT STRUCTURAL) units.
The CONSTRUCTION WORKER units will use the structural units to enclose the largest space possible.
Once the structure is complete, they will transfer the remainder of the BOM.
Unless the orders transfer them to the new colony or ship, they will return to their original host.

The BOM should include POPULATION units.
These units will establish control of the colony or ship once complete.
(An unpopulated colony or ship can be claimed by any player.)

The BOM should include enough FOOD units to feed the included POPULATION units.
Unlike the CONSTRUCTION WORKER units, the POPULATION units will not draw FOOD from the site.

.Set Up Chart
|===
||Open Colonies|Enclosed Colonies|Orbiting Colonies|Ships

|Allowed per player per planet|1|1|1|any number
|Located on planet surface|Habitable terrestrial|Uninhabitable terrestrial|none|none
|Located on asteroid|none|yes|none|none
|Located in orbit|none|none|any planet|any planet
|Life support unit required|no|yes|yes|yes
|Stuctural units necessary per unit of mass|1|5|10|10
|Size limitation|none|none|none|none
|===

All orders in the Set up phase are executed in the order that they're entered in the orders file.


=== Establish New Colony
TIP: Use `assemble-colony` to build a new colony.

```
assemble-colony
  ; bill of materials used to assemble the colony
end
```

=== Build New Ship
TIP: Use `assemble-ship` to build a new ship.

```
assemble-ship
  ; bill of materials used to assemble the ship
end
```


== Disassembly orders
All orders in the Disassembly phase are executed in the order that they're entered in the orders file.

=== Unassemble Construction Worker Units
An `unassemble` order disbands CONSTRUCTION WORKER units and returns their PROFESSIONAL and UNSKILLED WORKER units to the population.

Each unassembled CONW unit will return 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit to the idler's pool.

Format:
```
unassemble ColonyOrShipID Quantity construction-worker
```

Examples:
```
unassemble C13 3 construction-worker ; disband 3 CONW by returning 3 PRO and 3 UKSW
```

=== Unassemble Operational Units
An `unassemble` order instructs CONSTRUCTION WORKER units to take a unit apart and prepare it for storage.
This reduces the space required to store and transport the unit.

Only the items in the Operational Units chart can be unassembled.

You can't unassemble something that was never assembled.

A CONSTRUCTION WORKER unit can unassemble up to 500 MASS units (MUs) per TURN.
10% of the units taken apart will be scrapped and lost as a result.

Format:
```
unassemble ColonyOrShipID Quantity UnitCodeTL
```

Examples:
```
unassemble C27 9,750 MSLT-2  ; take apart 9,750 units - 975 will be scrapped
unassemble S52   200 MSL-3   ; take apart   200 units -  20 will be scrapped
```

=== Assemble Spy Units
An `unassemble` order disbands SPY units and returns their PROFESSIONAL and SOLDIER units to the population.

Each unassembled SPY unit will return 1 PROFESSIONAL unit and 1 SOLDIER unit to the idler's pool.

Format:
```
unassemble ColonyOrShipID Quantity spy
```

Examples:
```
unassemble C78 16 spy  ; disband 16 SPY by returning 16 PRO and 16 SLDR
```

== Change Orders

== Retool Phase
=== Retool orders
A `retool` order instructs CONSTRUCTION WORKER units to wait for the *WIP* to complete.
Once the production line is empty, the CONSTRUCTION WORKER units shut down all the factory units in the group.
Then they update the production line to build a new finished good and restart the FACTORY GROUP.
It takes one TURN to update and restart.

Format:
```
retool ColonyID FactoryGroupID UnitID
```

Examples:
```
  retool C6  FG19 research
  retool C27 FG8  ENWP-4
```

=== Mining change orders

== Transfers
== Assembly Phase
All orders in the Assembly phase are executed in the order that they're entered in the orders file.

=== Add additional Factory units to an existing Factory Group
=== Add additional Mine units to an existing Mining Group
=== Assemble Construction Worker Units
A `assemble` order gathers PROFESSIONAL and UNSKILLED WORKER units and assembles them as CONSTRUCTION WORKER units.

Each CONW unit requires 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit.
You may not create CONW units if the required number of PROFESSIONAL and UNSKILLED WORKER units are not available.

Format:
```
assemble ColonyOrShipID Quantity construction-worker
```

Examples:
```
assemble C13 3 construction-worker ; create 3 CONW by assembling 3 PRO and 3 UKSW
```

=== Assemble Operational Items
TODO: Operational is a hard to understand phrase.

An `assemble` order instructs CONSTRUCTION WORKER units to take a stored (disassembled) unit and make it operational (put it together).

A CONSTRUCTION WORKER unit can assemble up to 500 MASS units (MUs) per TURN.

Only the items in the Operational Units chart can be assembled.

.Operational Units
|===
|CODE

|AUTO
|ENSH
|ENWP
|FACT
|FARM
|HDRV
|LFSP
|LSU
|MINE
|MSLT
|SLSU
|SNSR
|SDRV
|SSU
|SLSU
|===

Format:
```
assemble ColonyOrShipID Quantity UnitCodeTL
```

Examples:
```
assemble C27 9,750 MSLT-2
assemble S52   200 LFSP-3
```

=== Assemble Spy Units
An `assemble` order gathers PROFESSIONAL and SOLDIER units and assembles them as SPY units.

Each SPY unit requires 1 PROFESSIONAL unit and 1 SOLDIER unit.
You may not create SPY units if the required number of PROFESSIONAL and SOLDIER units are not available.

Format:
```
assemble ColonyOrShipID Quantity spy
```

Examples:
```
assemble C78 16 spy  ; create 16 SPY by assembling 16 PRO and 16 SLDR
```

=== Manufacture Items
A `manufacture` order instructs a FACTORY GROUP to start producing units.
The type of unit and the tech level of the unit are specified in the command.
The number of units is not.

```
manufacture ColonyID Quantity FactoryGroupID UnitCodeTL
```

Examples:
```
manufacture C91 50,000 FG1009 MSL-8
```

=== Mine Resources
A `mine` order instructs a MINING GROUP to start mining and refining resources from a deposit.

```
mine Quantity MineCodeTL DepositID
```

Examples:
```
mine 25,000 MG2708 DP1019
```

== Market and Trade Station Activity Phase
WARNING: The market phase was removed because player's abused it.
Is there a way to monitor/prevent that?

== Surveys
=== Probe and Sensor Reports
== Espionage

== Ship Movement Phase
=== Jump Order
A `jump` order instructs a ship to engage its hyper-drive engines and move to a new system or a new orbit around the current star.

The destination must be a system or an orbit around the current star.

To jump between stars in a single system, the ship must first jump to the 11th orbit.
Which is just wrong.
TODO: fix this.

.Hyperdrive Range Chart
|===
|CODE|Maximum distance per JUMP|Maximum Capacity per UNIT per JUMP

|HDRV-1|1 light year|1,000 MUs
|HDRV-2|2 light years|2,000 MUs
|HDRV-3|3 light years|3,000 MUs
|HDRV-4|4 light years|4,000 MUs
|HDRV-5|5 light years|5,000 MUs
|HDRV-6|6 light years|6,000 MUs
|HDRV-7|7 light years|7,000 MUs
|HDRV-8|8 light years|8,000 MUs
|HDRV-9|9 light years|9,000 MUs
|HDRV-10|10 light years|10,000 MUs
|===

When calculating capacity for ships with multiple engines,
use the lowest Tech Level of all engines,
then multiply by the total number of engines.

If the mass of the ship exceeds the capacity of the engines,
it will consume the fuel but not move from its current location.

WARNING: The system does not idle engines that are not needed to make a jump.
It should.

.Jump Fuel Chart
|===
|Kind|FUEL units per UNIT per JUMP

|Interplanetary (between orbits)|4
|Interstellar (between systems)|40 * distance (in light years) jumped
|===

Format:
```
jump ShipID Coordinates
jump ShipID #Orbit
```

Examples:
```
jump S77 4/6/10    ; move S77 to system 4/6/10, orbit 11
jump S79 #6        ; jump S79 to orbit 6 in its current system
```

== Draft orders
1 PROFESSIONAL unit is required to train up to 100 trainee units.
5% of trainees graduate to ??? each TURN.
TODO: This is not the right phase.

The total number of UNSKILLED WORKER units drafted must not exceed the number of available SOLDIER units.

There is no limit on the number of SOLDIER units that may be disbanded per TURN.

== Pay and Ration Phase

=== Pay Order
A `pay` order changes the amount of pay (in consumer goods) each population unit receives per turn.

The base pay for populations units is per the following chart:

.Base Pay Chart
|===
|CODE|Pay per UNIT per TURN|Pay when SHIP CREW

|CONSTRUCTION WORKER|0.500 CONSUMER GOODS|N/A
|PROFESSIONAL|0.375 CONSUMER GOODS|0.01 GOLD
|SOLDIER|0.250 CONSUMER GOODS|0.005 GOLD
|SPY|0.625 CONSUMER GOODS|N/A
|UNEMPLOYABLE|0.000 CONSUMER GOODS|N/A
|UNSKILLED WORKER|0.125 CONSUMER GOODS|N/A
|===

Only crew members receive pay when on a ship.
The crew will be paid in gold credits instead of goods.
They will exchange the credits for goods when in a friendly port.

Passengers (or cargo if in cryo-sleep) are not paid - they receive food but forfeit their normal pay of consumer goods.

Format:
```
pay ColonyOrShipID PopulationUnitID Percentage
```

To change the rate for all units, regardless of location, issue the order with "*" as the ColonyOrShipID.

Examples:
```
pay S38 professional 100%  ; reset  pay to base rate
pay  *  soldier       50%  ; change pay for all soldiers
pay S38 unskilled     90%  ; change pay to  90% of base rate
pay C27 unskilled    110%  ; change pay to 110% of base rate
pay S38 spy          115%  ; change pay to 115% of base rate
```

In the example, the player is paying UNSKILLED WORKER units more on colony C27 than she is on ship S38.

==== Ship Population
The crew of a ship consists of PROFESSIONAL and SOLDIER units.
Non-crew are PASSENGERS (or, potentially, cargo if in cryo.)

.Ship Crew Pay
|===
|CODE|Pay per UNIT per TURN|FOOD per UNIT per TURN

|PROFESSIONAL|0.01 GOLD|Per rationing orders
|SOLDIER|0.005 GOLD|Per rationing orders
|PASSENGER|N/A/|Per rationing orders
|===

When the ship docks at its home planet or any trade station,
the crew will exchange their accumulated GOLD for CONSUMER GOODS.

Passengers are never paid while being transported,
but they do receive a ration of FOOD every TURN per the ship's orders.

==== General Population
.General Population Pay
|===
|CODE|People in UNIT|Pay per UNIT per TURN

|CONSTRUCTION WORKER|200|0.500 CONSUMER GOODS
|PROFESSIONAL|100|0.375 CONSUMER GOODS
|SOLDIER|100|0.250 CONSUMER GOODS
|SPY|200|0.625 CONSUMER GOODS
|UNEMPLOYABLE|100|0.000 CONSUMER GOODS
|UNSKILLED WORKER|100|0.125 CONSUMER GOODS
|===

WARNING: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

=== Ration Order

.Food Ration
|===
|CODE|People in UNIT|Base FOOD per UNIT per TURN|Minimum FOOD per UNIT per TURN

|CONSTRUCTION WORKER|200|0.5 FOOD units|0.125 FOOD units
|PROFESSIONAL|100|0.25 FOOD units|0.0625 FOOD units
|SOLDIER|100|0.25 FOOD units|0.0625 FOOD units
|SPY|200|0.5 FOOD units|0.125 FOOD units
|UNEMPLOYABLE|100|0.25 FOOD units|0.0625 FOOD units
|UNSKILLED WORKER|100|0.25 FOOD units|0.0625 FOOD units
|===

WARNING: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

== Rebellion
== Rebel increases
REBEL units represent the number of rebels.
They are not treated as a separate group.

People become rebels when under-paid and/or starving.
Once a rebel, almost always a rebel.

== Naming and Control orders

== Birth Phase
The changes to population due to births are calculated in this phase.

The birth rate ranges from 0.25% to 2.5% of the population.
The exact number is determined by quality of life.
Pay rates, food rations, open spaces, and civil strife are all factored in.

Births are computed each TURN.
The crew and passengers on a ship are ignored when calculating the population increase.
All birth increases accumulate to the UNEMPLOYABLE population.

NOTE: Future rules will consider cloning.
It is not currently an option.

== Training Phase
The changes to population due to training are calculated in this phase.

There are two types of training: training (apprenticeship) and Job Corps.

Attrition happens automatically; the player must issue orders to train workers.

=== Job Corps
The Job Corps trains UNEMPLOYABLE units to become UNSKILLED WORKER units.
The Corps is activated automatically when the percentage of UNEMPLOYABLE units is reaches 30% of the total population.
At the end of each turn that it is active, the Corps will move 2% of the UNEMPLOYABLE units to UNSKILLED WORKER units.

=== Train Order
A `train` order instructs PROFESSIONAL units to begin training UNSKILLED WORKER units.

A PROFESSIONAL unit may train up to 100 UNSKILLED WORKER units per TURN.

The trainees are unavailable for use until they have graduated from training.
They graduate at a rate of 5% per TURN.
After graduation, they are moved to the PROFESSIONAL population.

Format:
```
train ColonyOrShipID Quantity professional
```

Examples:
```
train S13 15,400 professional  ; assign 16 PROF units to train 154 UNSK units
```

== Retirement Phase
The changes to population due to retirement are calculated in this phase.

5% of SOLDIER units retire each YEAR.
(TODO: convert this to per TURN.)
Upon retirement, SOLDIER units become PROFESSIONAL units.
This happens automatically; the player can not control the number of retirees.

== Death Phase
The changes to population due to deaths from starvation and natural causes are calculated in this phase.

=== Starvation
Deaths from starvation are computed each TURN.

Starvation takes place when the rationed FOOD amount is less than 0.0625 of a FOOD unit per POPULATION unit.
When that happens, the following formula determines how many POPULATION units starve.

    S = (M - R) / M

Where M is the minimum ration from the Food Ration Chart,
R is the actual ration,
and S is the fraction of the population that starves.

TODO: Convert this to use percentages instead of fractions of FOOD units.

=== Natural Causes
Deaths from natural causes are computed each TURN.
They are computed after deaths from starvation.

.Death Rate Chart
|===
|CODE|Deaths from Natural Causes per TURN

|CONSTRUCTION WORKER|0.0700%
|PROFESSIONAL|0.0625%
|SOLDIER|0.0750%
|SPY|0.0775%
|UNEMPLOYABLE|0.0625%
|UNSKILLED WORKER|0.0625%
|===

TIP: Soldiering, spying, and construction are dangerous activities;
that's why the death rate is higher for those groups.

== News Service Reports

== Players

=== Nations

=== States

=== Governments

== Cluster

=== Systems

=== Planets

=== Colonies

[appendix]
== Units

=== Anti-Missile
=== Assault Craft
=== Assault Weapon
=== Automation
AUTO units may replace UNSKILLED WORKER units.
Each AUTO unit may replace up to its TECH LEVEL in UNSKILLED WORKER units.
An AUTO unit may not be split between groups.

.Automation Summary
|===
|CODE|Replacements per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|AUTO|Up to TL UNSKILLED WORKER units|4 * TL MU|0 FUEL units
|===

=== Colony
=== Construction Worker
=== Consumer Goods
.Consumer Goods Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN

|CONSUMER GOODS|0.6 MU|0 FUEL units
|===

=== Energy Shield
=== Energy Weapon
=== Factory
=== Farm
=== Food
.Food Summary
|===
|CODE|Feeds per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|FOOD|4 POPULATION units (400 people)|6 MU|0 FUEL units
|===

=== Hyper-Drive
.Hyper-Drive Summary
|===
|CODE|Range per UNIT|Capacity per UNIT|Mass per UNIT|Fuel per UNIT per JUMP

|HYPERDRIVE|TL light years|1,000 * TL MU|45 * TL MU|40 FUEL units per LY travelled
|===

Jumps between orbits ("interplanetary travel") are treated as 0.1 light years for FUEL.
(In other words, each HYPERDRIVE unit consumes 4 FUEL units jumping in system.)

=== Life Support
LIFE SUPPORT units use FUEL to replenish air and water in ships and colonies.

.Life Support Summary
|===
|CODE|Sustains per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|LIFE SUPPORT|TL^2^ POPULATION units|8 * TL MU|TL FUEL units
|===

=== Light Structural
.Light Structural Summary
|===
|CODE|Mass per UNIT|Capacity

|LIGHT STRUCTURAL|0.05 MU|todo
|===

=== Military Robots
=== Military Supplies
=== Mine
=== Missile
=== Population
=== Probe
See SENSOR.

=== Professional
=== Rebel
=== Sensor
.Sensor Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN

|SENSOR|40 * TL MU|TL / 20 FUEL units
|===

=== Ship
=== Soldier
=== Space-Drive
.Space-Drive Summary
|===
|CODE|THRUST FACTOR per UNIT|Mass per UNIT|Fuel per UNIT per COMBAT ROUND

|SPACEDRIVE|1,000 * TL^2^|25 * TL MU|TL^2^ FUEL units
|===

In combat, the SHIP may move a DISTANCE up to its MASS divided by the total THRUST FACTOR of its SPACEDRIVE units each COMBAT ROUND.

=== Spy
=== Structural
.Structural Summary
|===
|CODE|Mass per UNIT|Capacity

|STRUCTURAL|0.5 MU|todo
|===

=== Transport
.Transport Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN|Capacity

|TRANSPORT|4 * TL MU|TL^2^ / 10 FUEL units|200 * TL^2^ MU
|===

Note: FUEL usage is prorated.
The actual amount used is the percentage derived from cargo mass divided by capacity.

=== Unemployable
=== Unskilled Worker

[appendix]
== Notes
=== Farming Notes
There are three types of farms in the game.

1. Organic Farm units (OFARM) are open air farms and ranches.
These can be built only on habitable planets in orbits 1 through 5.
The maximum number of units is the _habitability number_ (HN) times 100,000.
2. Hydroponic Farm units (HFARM) use natural sunlight to grow grains and proteins in controlled, enclosed areas.
These can be built only on planets or orbital colonies in orbits 1 through 5.
3. Vat Farm units (VFARM) use artificial sunlight to grow grains and proteins in controlled, enclosed areas.

Each farming unit requires 3 Unskilled Worker units (UNW) and 1 Professional Worker unit (PWU) to be productive.

Unskilled Worker units may be replaced by Farming Automation units (AUFARM).

.Farming Production
|===
|Farm Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Organic Farm|OFARM|TL2|100.0 * TL FOOD units|6.0 + TL MU|0.5 * TL FUEL units
|Hydroponic Farm|HFARM|TL5|IF(TL<2,0,20*TL) FOOD units|6.0 + TL MU|0.5 * TL FUEL units
|Vat Farm|VFARM|TL10|IF(TL<6,0,20*TL) FOOD units|6.0 + TL MU|1.0 * TL FUEL units
|===

Exception: HFARM units in orbiting colonies use solar power, so their Fuel Use Per TURN is 0.0.

.Farm Chart
|===
|CODE|Production per UNIT per YEAR|Mass per UNIT|Fuel per UNIT per TURN|Location|Orbits|Solar Power

|FARM-1|100 FOOD|7 MU|0.5 FUEL|Planets with HN > 0|1..5|No
|FARM-2|40 FOOD|8 MU|1.0 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-3|60 FOOD|9 MU|1.5 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-4|80 FOOD|10 MU|2.0 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-5|100 FOOD|11 MU|2.5 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-6|120 FOOD|12 MU|6.0 FUEL|Any, including Ships|Any|No
|FARM-7|140 FOOD|13 MU|7.0 FUEL|Any, including Ships|Any|No
|FARM-8|160 FOOD|14 MU|8.0 FUEL|Any, including Ships|Any|No
|FARM-9|180 FOOD|15 MU|9.0 FUEL|Any, including Ships|Any|No
|FARM-10|200 FOOD|16 MU|10.0 FUEL|Any, including Ships|Any||No
|===

=== Manufacturing Notes
Factory (FACTORY) units process the raw materials created by Mining (MINE) units and turn them into finished goods such as star drives, robots, weapons, and consumer goods.
Essentially, FACTORY units produce everything except population, fuel, gold, and food.

To allow factories to produce different goods, the production pipeline is abstracted into Mass Units (MUs) of raw materials input and finished goods output.

.Factory Production
|===
|Factory Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Factory|FACTORY|TL10|20.0 * TL MASS Units|12.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

Exception: FACTORY units in orbiting colonies in orbits 1 through 5 use solar power, so their Fuel Use Per TURN is 0.0.

The amount of raw materials that can be processed by a factory unit in

The MUs produced are divided by the MUs of the good is the number of units of the good produced (all results are rounded down).

Examples needed here.

=== Mining Notes
Assigning MINE units to a DEPOSIT establishes CONTROL of that DEPOSIT.

Raw resources are found on planets, moons, and asteroid belts.
Resources are extracted from deposits by Mining (MINE) units.
MINE units are capable of mining, drilling, quarrying, and refining the raw resources.
For game purposes, we'll call all of those "mining."
The mined resources are also known as "raw materials."

There are two types of resources that may be mined in the game - ores and fuels.
Ores can contain precious metals and crystals (GOLD), non-precious metals (METL) or non-precious minerals (MNRL).

MINE units are not allowed to be installed on orbiting colonies;
they must be installed only on surface colonies.

.Mining Production
|===
|Mining Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Mining Unit|MINE|TL10|100.0 * TL MU|10.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

.Mining Production Chart
|===
|CODE|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|MINE|100.0 * TL MU|10.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

=== Population Notes
. Ration orders: Limit food consumption of a ship/colony.
. Pay orders: Set pay rates, which remain constant until changed, for a ship/colony.
. Draft orders: Recruit soldiers or trainees.
. Assembly orders: Form construction or spy units. (Assembly orders have other functions as well.)

=== Weapon Notes
.Weapons Chart
|===
|UNIT|CODE|DESCRIPTION|FUEL USE PER UNIT|MASS UNITS PER UNIT

|ASSAULT WEAPONS||Assault weapons are used by soldiers on the surface of a planet.|0|2
|ASSAULT CRAFT||Assault craft are land/space vehicles used to invade colonies of ships.|.1 fuel unit per turn|5 * TL
|MILITARY ROBOTS||Military robots can be used to replace soldier units.
The number of soldier units that can be replaced is equal to the military robot unit's TL * 2.|0|(2 * TL) + 20
|MISSILES||Missile can be used in any kind of combat; they are not as accurate as energy weapons.|0|4 * TL
|MISSILE LAUNCHERS||Missile launchers launch the missiles; the accuracy of a missile depends on the T.L. of the missile launcher.|0|25 * TL
|ANTI-MISSILES||Anti-missiles are launched by missile launchers also and destroy attacking missiles.
The % of missiles destroyed depends on the TL of the anti-missile.|0|4 * TL
|ENERGY WEAPONS||Energy weapons can be used in all combat situations except that of a surface colony to destroy a surface colony.
An energy weapon projects a powerful beam of concentrated energy.|4 * TL per COMBAT ROUND (CR)|10 * TL
|ENERGY SHIELDS||Energy shields deflect energy beams.
The amount of energy deflected depends on the TL of the shields.|10 * TL per CR|50 * TL
|MILITARY SUPPLIES||Military supplies consist of ammunition, medicines, etc., used up during combat.|0|.04 per unit
|===

[appendix]
== Tech Levels

|===
|Technological Level|Research Points Required|Total Research Points Required
|1|N/A|N/A
|2|100,000|100,000
|3|200,000|300,000
|4|400,000|700,000
|5|800,000|1,500,000
|6|1,600,000|3,100,000
|7|3,200,000|6,300,000
|8|6,400,000|12,700,000
|9|12,800,000|25,500,000
|10|25,600,000|51,100,000
|===

[appendix]
== Orders

This section details the *orders* that *players* may issue.

[glossary]
ColonyID:: _ColonyID_ is a unique identifier for a colony.
It must start with the letter "C" followed by an _integer_.
Examples are C1, C50, C100.

ColonyOrShipID:: _ColonyOrShipID_ is either a _ColonyID_ or _ShipID_.
This is only used when the _order_ accepts either a colony or ship.
For example, a player may order S27 to raid S35 or C22.

DepositID:: _DepositID_ is a unique identifier for a resource deposit.
It must start with the letters "DP" followed by an _integer_.
Examples are DP1, DP100, DP10001.

FactoryCodeTL:: _FactoryCodeTL_ is composed of two parts separated by a dash.
The first part is the code for factory units.
The second part is the *TechLevel* of the factory unit.
Examples are FACTORY-1, FACTORY-3, FACTORY-9.

FactoryGroupID:: _FactoryGroupID_ is a unique identifier for a factory group.
It must start with the letters "FG" followed by an _integer_.
Examples are FG1, FG100, FG10001.

Integer:: _Integer_ is a whole number.
Examples are 0, 50, 100.

LootID:: _LootID_ is the name of a resource to target during a raid.
Examples are gold, fuel.

Number:: _Number_ is a real number or a whole number.
Examples are 0, 0.0, 50.2, 100.

MineCodeTL:: _MineCodeTL_ is composed of two parts separated by a dash.
The first part is the code for mining units.
The second part is the *TechLevel* of the mining unit.
Examples are MINE-1, MINE-3, MINE-9.

MiningGroupID:: _MiningGroupID_ is a unique identifier for a mining group.
It must start with the letters "MG" followed by an _integer_.
Examples are MG1, MG100, MG10001.

Percentage:: _Percentage_ is an _integer_ between 0 and 100 followed by a percent sign.
Examples are 0%, 50%, 100%.

PercentCommitted:: _PercentCommitted_ is a _percentage_.
It is TODO...

Quantity:: _Quantity_ is a whole number.
It must be greater than zero.
Examples are 1, 5,000, and 3,000,142.

ShipID:: _ShipID_ is a unique identifier for a ship.
It must start with the letter "S" followed by an _integer_.
Examples are S1, S50, S100.

TargetID:: _TargetID_ is either a _ColonyID_ or _ShipID_.
For example, a player may order S50 to support S27 in its attack against C22.

TechLevel:: _TechLevel_ is an integer in the range of 1..10.

UnitCodeTL:: _UnitCodeTL_ is composed of two parts separated by a dash.
The first part is the code for the unit.
The second part is the *TechLevel* of the unit.
Examples are MISSILE-2, HYPERDRIVE-3, and ENERGYSHIELDS-9.

[index]
== Index

