= Wraith Reference Manual
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-04-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith Reference Manual (c) 2022 by Michael D Henderson

Wraith Reference Manual is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

TIP: This document is meant to be concise and definitive.
That makes it a terrible source for learning the game.
The User's Guide is the recommended source for getting started.

NOTE: This reference manual is the source of truth for the rules.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Organization
The reference manual presents rules in the sequence they would be processed during a game turn.

The chapter headings are the phases from the following chart:

.Phase Chart
|===
|Phase|Description

|Fuel Allocation|In this phase, fuel is allocated to units.
Fuel allocations are prioritized: life support is first, followed by farms, mines, then factories.
The allocation algorithm is naive and simple.
It attempts to allocate 100% of a unit's needs before moving to the next unit.
It never allocates proportionately.
|Life Support|Population changes due to life supoort are calculated.
|Farming Production|The farming production phase todo...
|Mining Production|The mining phase is used to extract resources from deposits and refine them into materials that can be used in the manufacturing phase.
|Manufacturing Production|The manufacturing production phase todo...
|Combat|The combat phase is used to project force against other player's assets.
|Set up|The set up phase is used to assemble new colonies and ships.
|Disassembly|This phase is used to disassembly operational units and make them ready to put into storage.
|Retool|Change the manufacturing pipeline for existing factory groups.
|Mining Change|The mining change orders phase is used to todo...
|Transfer|Population and cargo are moved between ships and colonies in the same orbit using available transports.
|Assembly|The assembly phase is used to manufacture items, mine resources, and assemble units from storage.
|Trade|The market and trade station phase is used to process trade and barter orders at markets and trade stations.
|Survey|This phase surveys systems, planets, colonies, and ships.
|Survey Reports|This phase produces the probe and sensor reports.
Todo...
|Espionage|The espionage phase todo...
|Ship Movement|This is the only phase in which ships move.
|Draft|This phase applies draft orders to move workers between population unit types todo...
|Pay and Ration|This phase is used to pay the population and distribute food.
Pay is either gold (in the form of credits) or consumer goods.
The player may change the default pay and ration rates.
|Rebellion|Chances for rebel militias to engage in open rebellion are calculated and results checked.
Active militias will engage in combat starting the next turn.
|Control|In this phase, naming and control orders are todo...
|Birth|Population changes due to births are calculated.
|Training|Population changes due to training and apprenticeships are calculated.
|Retirement|Population changes due to retirement are calculated.
|Death|Population changes due to starvation and natural deaths are calculated.
|Research|Changes to the tech level for a colony or ship tech level are determined in this phase.
|News|In this phase, reports for the "news services" are created todo...
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

== Fuel Allocation Phase
The number of FUEL units available to every colony and ship is calculated.

FUEL allocations are prioritized:

. LIFE SUPPORT units
. FARM units
. MINE units
. FACTORY units

Remaining FUEL is immediately moved to STORAGE.
If there are not enough STORAGE available on the colony or ship,
excess FUEL is lost.

FUEL units in STORAGE are available for use in the remaining phases.

TIP: FUEL units are only produced via mining.
They are not available for use until the TURN after they've been mined.
There are some rather complicated exceptions to this rule.

== Life Support Phase
The number of LIFE SUPPORT units that are ACTIVE are counted.

.Life Support Chart
|===
|CODE|FUEL per UNIT per TURN|Population units supported per UNIT per TURN

|LFSP-1|1|1
|LFSP-2|2|4
|LFSP-3|3|9
|LFSP-4|4|16
|LFSP-5|5|25
|LFSP-6|6|36
|LFSP-7|7|49
|LFSP-8|8|64
|LFSP-9|9|81
|LFSP-10|10|100
|===

Population that isn't supported is killed off in this phase.
The only exception are units that have been placed into cryo-sleep.

Casualties are distributed uniformly across all population groups.

LFSP units must be ACTIVE for the entire turn to support population units.
If the units are shut down for any reason, the capacity will be recalculated and excess population killed off.
This includes sabotage, damage in combat, or a ship taking on too many passengers.

== Farming Production Phase
The number of FOOD units produced by active FARM units is calculated.
The food units are moved to local depots for temporary storage.

A FARM unit produces no FOOD units if it is INACTIVE.

A FARM unit produces no FOOD units the first TURN that it is ACTIVE.

=== Fuel
FARM units require FUEL to be ACTIVE.
If a FARM unit does not have a full allocation of FUEL,
it is INACTIVE for the current TURN.

.Farming Fuel Chart
|===
|CODE|FUEL per UNIT per TURN|Sunlight|Can use Solar Power?

|FARM-1 >|0.5|Natural|No
|FARM-2 >|1.0|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-3 >|1.5|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-4 >|2.0|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-5 >|2.5|Natural|Yes, if on Orbital Station in orbits 1..5
|FARM-6 >|6.0|Artificial|No
|FARM-7 >|7.0|Artificial|No
|FARM-8 >|8.0|Artificial|No
|FARM-9 >|9.0|Artificial|No
|FARM-10 >|10.0|Artificial|No
|===

If the FARM unit can use Solar Power, its FUEL cost drops to 0 FUEL units per TURN.

=== Labor
FARM units require labor to be ACTIVE.
If a FARM unit does not have a full allocation of labor,
it is INACTIVE for the current TURN.

.Farming Labor Chart
|===
|CODE|PROFESSIONAL Units|UNSKILLED WORKER Units

|FARM|1 per FARM unit|3 per FARM unit
|===

Farming automation units may replace a number of UNSKILLED WORKER units equal to their Tech Level.
For example, an AUTO-3 may replace 3 UNSKILLED WORKER units.

=== Shortages
Todo...

=== Production
If the FARM unit is ACTIVE this TURN and was active the prior TURN,
it will produce FOOD per the following chart.

.Farming Production Chart
|===
|CODE|Production per UNIT per YEAR

|FARM-1|100 FOOD
|FARM-2|40 FOOD
|FARM-3|60 FOOD
|FARM-4|80 FOOD
|FARM-5|100 FOOD
|FARM-6|120 FOOD
|FARM-7|140 FOOD
|FARM-8|160 FOOD
|FARM-9|180 FOOD
|FARM-10|200 FOOD
|===

1 FOOD unit will feed 4 population units and has a mass of 6 MASS units (MUs).
TODO: this is the wrong place for this information.

== Mining Phase
A MINE unit produces no raw material units if it is INACTIVE.

A MINE unit produces no raw material units the first TURN that it is ACTIVE.

=== Fuel
MINE units require FUEL to be ACTIVE.
If a MINE unit does not have a full allocation of FUEL,
it is INACTIVE for the current TURN.

.Mining Fuel Chart
|===
|CODE|Fuel per UNIT per TURN|Can use Solar Power?

|MINE|TL * 0.5|No
|===

If the MINE unit can use Solar Power, its FUEL cost drops to 0 FUEL units per TURN.

=== Labor
MINE units require labor to be ACTIVE.
If a MINE unit does not have a full allocation of labor,
it is INACTIVE for the current TURN.

.Mining Labor Chart
|===
|CODE|PROFESSIONAL Units|UNSKILLED WORKER Units

|MINE|1 per MINE unit|3 per MINE unit
|===

Note that mining automation units may replace UNSKILLED WORKER units at a TODO rate.

Mining automation units may replace a number of UNSKILLED WORKER units equal to their Tech Level.
For example, an AUTO-3 may replace 3 UNSKILLED WORKER units.

=== Shortages
Todo...

=== Production
If the MINE unit is ACTIVE this TURN and was active the prior TURN,
it will produce raw materials per the following chart.

.Mining Production Chart
|===
|CODE|Production per UNIT per YEAR

|MINE|100 * TL MASS UNITS (MU) of raw materials
|===

== Manufacturing Phase
The amount of finished goods produced by factory groups is calculated in this phase.

A FACTORY GROUP is a set of of FACTORY units assigned to work together to build a common finished good.

FACTORY units are the only units that can convert fuel and raw materials into finished goods.

A FACTORY unit produces no finished units if it is IDLE or INACTIVE.

FACTORY units that are not assigned to a FACTORY GROUP are INACTIVE (idle) - they will not manufacture any unit.

A FACTORY unit produces finished units the first TURN that it is ACTIVE.

A FACTORY unit produces finished units the last TURN that it is ACTIVE. 

FACTORY units manufacture (produce) all goods except

. Raw Materials -- GOLD, FUEL, METAL, and NON-METALLIC units
. FOOD units
. POPULATION units

If the FACTORY unit is ACTIVE this TURN and was active the prior TURN, it will produce finished goods per the production chart.
Otherwise, it will produce nothing.

=== Location
FACTORY units may be assembled only on COLONY units.
FACTORY units may not be assembled on SHIP units.
Players may not assemble FACTORY units anywhere other than a COLONY.

=== Groups
FACTORY units must be assigned to a FACTORY GROUP before they can be activated.
A FACTORY unit is INACTIVE if is it not assigned to a FACTORY GROUP.

=== Fuel
FACTORY units require fuel to be ACTIVE.
The fuel source may be solar power or FUEL units.

FACTORY units that are on orbiting colonies in orbits 1 through 5 use solar fuel.
These units require no other fuel source to operate at full capacity.

All other FACTORY units must use FUEL units per the following chart.

.Factory Fuel Chart
|===
|CODE|Fuel per UNIT per TURN|Can use Solar Power?

|FACT|TL * 0.5|Yes, if on Orbital Station in orbits 1..5
|===

Note: INACTIVE FACTORY units never consume FUEL units.

If a FACTORY GROUP does not have a full allocation of fuel, it will use the SHORTAGE rules for the current TURN.

=== Labor
FACTORY units require labor to be ACTIVE.
The amount of labor is determined by the total number of units in the FACTORY GROUP.

If a FACTORY GROUP does not have a full allocation of labor, it will use the SHORTAGE rules for the current TURN.

The efficiency of a FACTORY GROUP improves as more FACTORY units are added.
The following chart shows the number of labor units needed based on the total number of FACTORY units in the GROUP.

.Factory Group Labor Chart
|===
|CODE|Size|PROFESSIONAL units|UNSKILLED WORKER units

|FACTORY GROUP|1 - 4 FACTORY units|6 per FACTORY unit|18 per FACTORY unit
|FACTORY GROUP|5 - 49 FACTORY units|5 per FACTORY unit|15 per FACTORY unit
|FACTORY GROUP|50 - 499 FACTORY units|4 per FACTORY unit|12 per FACTORY unit
|FACTORY GROUP|500 - 4,999 FACTORY units|3 per FACTORY unit|9 per FACTORY unit
|FACTORY GROUP|5,000 - 49,999 FACTORY units|2 per FACTORY unit|6 per FACTORY unit
|FACTORY GROUP|50,000 - up FACTORY units|1 per FACTORY unit|3 per FACTORY unit
|===

TIP: factory automation units may replace UNSKILLED WORKER units at a TODO rate.

Note: the ratio of UNSKILLED WORKER to PROFESSIONAL units is 3 to 1.

Players may rely on the inverse of this chart.
For example,
if the player allocates 3 PROFESSIONAL units and 9 UNSKILLED WORKER units to a FACTORY GROUP,
up to 4,999 FACTORY units may be activated in the group.
All excess FACTORY units in the group are INACTIVE that TURN.

=== Raw Materials
The manufacturing pipeline is abstracted into MASS units (MU) of raw materials input and finished goods output.
This allows factory groups to produce different goods.

Each FACT in a FACTORY GROUP requires raw materials to produce finished goods.
Every type of finished good requires a set of raw materials per the following chart:

.Production Raw Materials Chart
|===
|CODE|METALLIC Units|NON-METALLIC Units|GOLD Units|FUEL Units

|AMSL|2 * TL|2 * TL >|0 >|0
|ATKC|3 * TL|2 * TL >|0 >|0
|ATKW|1 * TL|1 * TL >|0 >|0
|AUTO|2 * TL|2 * TL >|0 >|0
|CGDS >|0.20 >|0.40 >|0 >|0
|ENSH|25 * TL|25 * TL >|0 >|0
|ENWP|5 * TL|5 * TL >|0 >|0
|FACT|8 + TL|4 + TL >|0 >|0
|FARM|4 + TL|2 + TL >|0 >|0
|HDRV|25 * TL|20 * TL >|0 >|0
|LFSP|3 * TL|5 * TL >|0 >|0
|LSU >|0.01 >|0.04 >|0 >|0
|MILR|10 + TL|10 + TL >|0 >|0
|MILS >|0.02 >|0.02 >|0 >|0
|MINE|5 + TL|5 + TL >|0 >|0
|MSL|2 * TL|2 * TL >|0 >|0
|MSLT|15 * TL|10 * TL >|0 >|0
|SNSR|10 * TL|20 * TL >|0 >|0
|SDRV|15 * TL|10 * TL >|0 >|0
|SSU >|0.10 >|0.40 >|0 >|0
|TRNS|3 * TL|1 * TL >|0 >|0
|===

Each FACT in a FACTORY group can consume up to 5 MASS units (MUs) per TL per TURN in raw materials.

Example:
```
FACT-1 -> 1 TL * 5 MU/TL/turn ->  5 MU/turn
FACT-3 -> 3 TL * 5 MU/TL/turn -> 15 MU/turn
```

The FACTORY GROUP can consume the total of all FACT units in the group.

Example:
```
FG1098 has 123 FACT-1 and 318 FACT-3 units
  FACT-1 -> 123 units *  5 MU/turn/unit ->   615 MU/turn
  FACT-3 -> 318 units * 15 MU/turn/unit -> 4,770 MU/turn
FG1098 can consume a total of              5,385 MU/turn
```

If a FACTORY GROUP does not have a full allocation of raw materials, it will use the SHORTAGE rules for the current TURN.

=== Shortages
A FACTORY GROUP will be unable to produce its full output when there is a shortage of fuel, labor, or raw materials.

The FACTORY GROUP will use as much of its input fuel, labor, or raw materials as it can;
the excess units will be returned to the "central depot" for allocation in future turns.

Shortages always impact the first stage of the manufacturing pipeline.
The shortage will then flow into the following stages.

The shortage will be spread across all factory groups in the colony.
It will be assessed proportionatly.

NOTE: Players should be able to prioritize the resources per factory group
(or maybe by finished good).
"If there's a shortage of steel, make tanks before spoons."

=== Production
COLONY units are the only UNIT that may install FACT units and manufacture (produce) finished goods.
Players may not activate FACT units anywhere other than a COLONY.

Unless otherwise stated, it takes 4 TURNS (one YEAR) to manufacture a finished good.
Adding more FACT units to a FACTORY GROUP will consume more raw materials, which increases the amount of finished goods;
it will not reduce the amount of time needed to manufacture the finished goods.

== Combat Phase
All orders in the Combat phase are executed in the order that they're entered in the orders file.

Each colony or ship may be given a single combat order per turn.

NOTE: Future change to allow for attacks against multiple targets.

NOTE: Future change to create "fleets" if needed to help with combat orders.

Some units require FUEL to be used in combat.

.Combat Fuel Chart
|===
|CODE|FUEL use per UNIT per TURN|FUEL use per UNIT per COMBAT ROUND

|Assault Craft|0.1|N/A
|Energy Shield|N/A|TL * 4
|Energy Weapon|N/A|TL * 10
|Space Drive|N/A|TL^2^
|===

.Combat Thrust Factor (TF) Chart
|===
|CODE|Thrust Factor per UNIT per COMBAT ROUND

|Space Drive|TL^2^ * 1000
|===

The total thrust factors (TF) divided by the ship's total mass is the maximum number of space combat rings a ship may move in a single combat round.

The player has no control over any ship's movement in combat.

Soldiers consume MILITARY SUPPLY units at a rate of one MILITARY SUPPLY unit per SOLDIER unit per COMBAT ROUND.
If a SOLDIER unit runs out of MILITARY SUPPLY units, it will disengage and return to its origin.
If it can't, it will surrender.

MILITARY ROBOT units consume MILITARY SUPPLY units at a rate of one MILITARY SUPPLY unit per MILITARY ROBOT unit per COMBAT ROUND.
If a MILITARY ROBOT unit runs out of MILITARY SUPPLY units, it will disengage and return to its origin.
If it can't, it will self destruct to avoid capture.

Percentage of Commitment is an alias for perecentage of units the player will commit to combat with that order.

=== Bombard Order
The `bombard` order commits FUEL, ENERGY WEAPONS, MISSILE, and MISSILE LAUNCHER units to an attack against a colony or ship.
The objective is to destroy the target.

Format:
```
ColonyOrShipID bombard SpeciesID ColonyOrShipID Percentage
```

Examples:
```
S27 bombard SP18 C13 50%
```

=== Invade Order
The `invade` order commits FUEL, SOLDIER, MILITARY ROBOT, and TRANSPORT units to an attack against a colony or ship.
The objective is to destroy the target.

```
ColonyOrShipID invade SpeciesID ColonyOrShipID Percentage
```

Examples:
```
S27 invade SP18 C13 50%
```

=== Raid Order
The `raid` order commits FUEL, SOLDIER, MILITARY ROBOT, and TRANSPORT units to an attack against a colony or ship.
The objective is to sieze and retrieve an enemy asset.

```
ColonyOrShipID raid SpeciesID ColonyOrShipID PercentCommitted AssetID Percent
```

Examples:
```
S27 raid SP18 C13 assault-weapon-5 10%
```

NOTE: This is a peculiar order because it assumes that there are enough soldiers to carry the asset to the transport and that the transport is large enough to hold the asset.
It also requires you to specify a particular tech level when you have no way of knowing what a colony or ship is carrying.

=== Sabotage Order
The `sabotage` order commits FUEL, SOLDIER, MILITARY ROBOT, and TRANSPORT units to an attack against a colony or ship.
The objective is to destroy an enemy asset.

```
ColonyOrShipID sabotage SpeciesID ColonyOrShipID PercentCommitted AssetID Percent
```

Examples:
```
S27 sabotage SP18 C13 hyper-drive-5 10%
```

NOTE: This is a peculiar order because you specify a particular tech level when you have no way of knowing what a colony or ship is carrying.
It should probably be just `S27 sabotage SP18 C13 hyper-drive 10%`.

=== Support Order
The `support` order commits FUEL, SOLDIER, MILITARY ROBOT, and TRANSPORT units to a coordinated attack against a colony or ship.
The objective is to work with another player to achieve an objective.
It can also be used for defending.

```
ColonyOrShipID support SpeciesID ColonyOrShipID against SpeciesID Percent
ColonyOrShipID support SpeciesID ColonyOrShipID bombard SpeciesID ColonyOrShipID Percent
ColonyOrShipID support SpeciesID ColonyOrShipID invade  SpeciesID ColonyOrShipID Percent
```

NOTE: Using the `against` version of the order commits your units to defending your partner's colony or ship.

Examples:
```
S14 support SP12 S83 against SP18     100%
S14 support SP12 S83 bombard SP18 C13 100%
S14 support SP12 S83 invade  SP18 C13 100%
```

== Set Up Phase
The Set Up phase is used to build new colonies and ships.

All orders in the Set Up phase are executed in the order that they're entered in the orders file.

There are limitations on where colonies and ships may be built.
There are also limits on the number of colonies each player may build in a single orbit.

.Build Limits Chart
|===
|CODE|# per Player per Orbit|On Planet Surface|On Asteroid Belt|In Orbit|Life Support Required|Maximum Size

|Open Colony >|1 ^|Habitable Terrestrial ^|NO ^|NO ^|NO ^|unlimited
|Enclosed Colony >|1 ^|Any Terrestrial ^|YES ^|NO ^|YES ^|unlimited
|Orbital Colony >|1 ^|NO ^|NO ^|Any Planet ^|YES ^|unlimited
|Ship ^|unlimited ^|NO ^|NO ^|Any Planet ^|YES ^|unlimited
|===

Set up orders are used to assemble a new COLONY or SHIP.

The order includes the list of material units for the assembly.
(This list is also known as the "bill of materials", or BOM.)
All materials must be present at the site prior to starting.

This order will span multiple lines since it specifies the list of materials.
The player must use the `end` keyword to terminate the order.

The BOM must include CONSTRUCTION WORKER units.
These units will assemble the colony or ship and will be returned once the assembly is complete.
While working, these units will draw FOOD from the site
(meaning the ship or colony they were transferred from).

The CONSTRUCTION WORKER units will use STRUCTURAL units to build the "hull" of the colony or ship
(actually, it's the exostructure, but hull is easier to type).

The BOM must include the STRUCTURAL (or LIGHT STRUCTURAL) units for building the hull.
The CONSTRUCTION WORKER units will use the available units to enclose the largest space possible.
The amount should be enough to enclose the total number of Enclosed MASS units (EMUs) planned for the colony or ship.
EMUs don't include the mass of the SUs used to build the colony or ship
(in other words, the hull doesn't count towards enclosed mass but it does count for engines).
Items in storage are counted as 1/2 their mass for purposes of the EMU.

.Structural Unit Summary
|===
|CODE|Mass per UNIT|Open Colony|Enclosed Colony|Orbital Colony|Ship

|SSU|0.5 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|LSU|0.05 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|SLSU|0.005 MU|1 unit per MU|5 units per EMU|10 units per EMU|10 units per EMU
|===

Once the structure is complete, the CONSTRUCTION WORKER units will transfer the remainder of the BOM to the colony or ship.
Items like engines, life support, weapons, and sensors will be installed in the colony or ship.
The remaining items, like FOOD and CONSUMER GOODS, will be placed directly in storage or cargo holds.
Unless the orders transfer them to the new colony or ship, they will return to their original host.

The BOM should include POPULATION units.
These units will establish control of the colony or ship once complete.
(An unpopulated colony or ship can be claimed by any player.)

The BOM should include enough FOOD units to feed the included POPULATION units.
Unlike the CONSTRUCTION WORKER units, the POPULATION units will not draw FOOD from the site.

=== Build Colony Order
TIP: Use `build colony` to build a new colony.

```
build colony
  ; bill of materials used to assemble the colony
end
```

=== Build Ship Order
TIP: Use `build ship` to build a new ship.

```
build ship
  ; bill of materials used to assemble the ship
end
```


== Disassembly orders
All orders in the Disassembly phase are executed in the order that they're entered in the orders file.

=== Unassemble Construction Worker Order
An `unassemble` order disbands CONSTRUCTION WORKER units and returns their PROFESSIONAL and UNSKILLED WORKER units to the population.

Each unassembled CONW unit will return 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit to the idler's pool.

Format:
```
ColonyOrShipID unassemble Quantity construction-worker
```

Examples:
```
C13 unassemble 3 construction-worker ; disband 3 CONW by returning 3 PRO and 3 UKSW
```

=== Unassemble Operational Unit Order
An `unassemble` order instructs CONSTRUCTION WORKER units to take a unit apart and prepare it for storage.
This reduces the space required to store and transport the unit.

Only the unit in the <<Operational Units>> chart can be unassembled.
(You can't unassemble something that was never assembled!)

A CONSTRUCTION WORKER unit can unassemble up to 500 MASS units (MUs) per TURN.
10% of the units taken apart will be scrapped and lost as a result.

Format:
```
ColonyOrShipID unassemble Quantity UnitCodeTL
```

Examples:
```
S52 unassemble 200 life-support-3      ; take apart 200 units - 20 will be scrapped
C27 unassemble  71 missile-launcher-2  ; take apart  71 units -  8 will be scrapped
```

=== Unassemble Spy Order
An `unassemble` order disbands SPY units and returns their PROFESSIONAL and SOLDIER units to the population.

Each unassembled SPY unit will return 1 PROFESSIONAL unit and 1 SOLDIER unit to the idler's pool.

Format:
```
ColonyOrShipID unassemble Quantity spy
```

Examples:
```
S11 unassemble 16 spy  ; disband 16 SPY by returning 16 PRO and 16 SLDR
```

== Change Orders

== Retool Phase
Use construction worker units to change the manufacturing lines in existing factory groups.
The order may take up to four turns to complete since the crews must wait for all existing WIP to complete.

All orders in the Retool phase are executed in the order that they're entered in the orders file.

=== Retool Order
A `retool` order instructs CONSTRUCTION WORKER units to wait for the *WIP* to complete.
Once the production line is empty, the CONSTRUCTION WORKER units shut down all the factory units in the group.
Then they update the production line to build a new finished good and restart the FACTORY GROUP.
It takes one TURN to update and restart.

WARNING: If there are not enough construction worker units available to complete the update in a single turn,
they will continue the update in future turns until it is completed.
The entire group will be idle until the update has completed.

Format:
```
ColonyID FactoryGroupID retool UnitID
```

Examples:
```
C6  FG19 retool research         ; begin research when WIP is complete
C27 FG8  retool energy-weapon-4  ; build energy weapons when WIP is complete
```

Build locations restrictions apply for retool orders.
See <<Assemble Factory Group Order>> for those restrictions.

=== Mining change orders

== Transfer Phase
All orders in the Transfer phase are executed in the order that they're entered in the orders file.

=== Transfer Order
A `transfer` order instructs the crew of a transport to load cargo (people or units) onto a transport,
fly the transport to the destination (which must be in the same orbit),
offload the cargo,
and then return back to the origin.

Transports require FUEL and labor to operate.
1 PROFESSIONAL unit may operate up to 10 TRANSPORTS per TURN.
The amount of fuel used per turn depends on the total mass units of cargo.
It is equal to the total mass units times the Fuel Factor.

Format:
```
ColonyOrShipID transfer Quantity UnitID ColonyOrShipID
```

Examples:
```
S22 transfer 50 consumer-goods C29  ; move 50 consumer good units from S22 to C29
S22 transfer 10 spy            C29  ; move 10 spy           units from S22 to C29
```

.Transport Crew Chart
|===
|CODE|Crew

|TRNS|1 PROFESSIONAL per 10 TRANSPORTS
|===

.Transport Operations Chart
|===
|CODE|MUs transferred per TURN|Fuel Factor

|TRNS-1 >|200 >|0.0005
|TRNS-2 >|800 >|0.0005
|TRNS-3 >|1800 >|0.0005
|TRNS-4 >|3200 >|0.0005
|TRNS-5 >|5000 >|0.0005
|TRNS-6 >|7200 >|0.0005
|TRNS-7 >|9800 >|0.0005
|TRNS-8 >|12800 >|0.0005
|TRNS-9 >|16200 >|0.0005
|TRNS-10 >|20000 >|0.0005
|===

== Assembly Phase
All orders in the Assembly phase are executed in the order that they're entered in the orders file.

=== Assemble Construction Worker Order
An `assemble` order gathers PROFESSIONAL and UNSKILLED WORKER units and assembles them as CONSTRUCTION WORKER units.

Each CONW unit requires 1 PROFESSIONAL unit and 1 UNSKILLED WORKER unit.
You may not create CONW units if the required number of PROFESSIONAL and UNSKILLED WORKER units are not available.

Format:
```
ColonyOrShipID assemble Quantity construction-worker
```

Examples:
```
C13 assemble 3 construction-worker ; create 3 CONW by assembling 3 PRO and 3 UKSW
```

=== Assemble Factory Group Order
An `assemble` order creates a new FACTORY GROUP and assigns them a finished good to manufacture.
The factory group number will be displayed on the player's report at the end of the turn.

There are restrictions on where items can be built, per the following chart:

.Production Location Chart
|===
|CODE|Open Colony|Enclosed Colony|Orbital Colony|Ship

|AMSL ^|YES ^|YES ^|YES ^|NO
|ATKC ^|YES ^|YES ^|YES ^|NO
|ATKW ^|YES ^|YES ^|YES ^|NO
|AUTO ^|YES ^|YES ^|YES ^|NO
|CGDS ^|YES ^|YES ^|YES ^|NO
|ENSH ^|YES ^|YES ^|YES ^|NO
|ENWP ^|YES ^|YES ^|YES ^|NO
|FACT ^|YES ^|YES ^|YES ^|NO
|FARM ^|YES ^|YES ^|YES ^|NO
|HDRV ^|YES ^|YES ^|YES ^|NO
|LFSP ^|YES ^|YES ^|YES ^|NO
|LSU ^|NO ^|NO ^|YES ^|NO
|MILR ^|YES ^|YES ^|YES ^|NO
|MILS ^|YES ^|YES ^|YES ^|NO
|MINE ^|YES ^|YES ^|YES ^|NO
|MSL ^|YES ^|YES ^|YES ^|NO
|MSLT ^|YES ^|YES ^|YES ^|NO
|Research ^|YES ^|YES ^|YES ^|NO
|SNSR ^|YES ^|YES ^|YES ^|NO
|SDRV ^|YES ^|YES ^|YES ^|NO
|SSU ^|YES ^|YES ^|NO ^|NO
|TRNS ^|YES ^|YES ^|YES ^|NO
|===

Any order that violates a location restriction will be ignored.

Format:
```
ColonyID assemble Quantity FactoryTL UnitID
```

Examples:
```
C8  assemble  5,000 factory-2 assault-craft-6
C91 assemble 50,000 factory-6 consumer-goods
```

NOTE: This order creates a new factory group using a single tech level of factory.
Orders in later turns can add different tech levels to the group.
Future versions of this order should allow the player to mix the tech levels on creation.

=== Assemble Mining Group Order
An `assemble` order creates a new MINING GROUP and assigns them to work a deposit.
The mining group number will be displayed on the player's report at the end of the turn.

Format:
```
ColonyID assemble Quantity MineTL DepositID
```

Examples:
```
C91 assemble 50,000 mine-3 DP3
```

NOTE: This order creates a new mining group using a single tech level of mine.
Orders in later turns can add different tech levels to the group.
Future versions of this order should allow the player to mix the tech levels on creation.

=== Assemble Operational Unit Order
TODO: Operational is a hard to understand phrase.

An `assemble` order instructs CONSTRUCTION WORKER units to take a stored (disassembled) unit and make it operational (put it together).

An "operational item" is a unit that must be assembled to be useable.
Operational items can also be disassembled to save space when transporting them.

A CONSTRUCTION WORKER unit can assemble up to 500 MASS units (MUs) per TURN.

Only the items in the Operational Units chart can be assembled.

.Operational Units
|===
|CODE

|AUTO
|ENSH
|ENWP
|FACT
|FARM
|HDRV
|LFSP
|LSU
|MINE
|MSLT
|SLSU
|SNSR
|SDRV
|SSU
|===

Format:
```
ColonyOrShipID assemble Quantity UnitCodeTL
```

Examples:
```
C27 assemble 9,750 missile-launcher-2
S52 assemble   200 life-support-3
```

=== Assemble Spy Order
An `assemble` order gathers PROFESSIONAL and SOLDIER units and assembles them as SPY units.

Each SPY unit requires 1 PROFESSIONAL unit and 1 SOLDIER unit.
You may not create SPY units if the required number of PROFESSIONAL and SOLDIER units are not available.

Format:
```
ColonyOrShipID assemble Quantity spy
```

Examples:
```
C78 assemble 16 spy  ; create 16 SPY by assembling 16 PRO and 16 SLDR
```

=== Expand Factory Group Order
An `expand` order adds additional FACTORY units to an existing FACTORY GROUP.

Format:
```
ColonyID FactoryGroupID expand Quantity FactoryTL
```

Examples:
```
C91 FG2 expand 2,500 factory-2  ; add 2,500 FACT-2 units to the group
C91 FG2 expand 1,800 factory-6  ; add 1,800 FACT-6 units to the group
```

=== Expand Mining Group Order
An `expand` order adds additional MINE units to an existing MINING GROUP.

Format:
```
ColonyID MiningGroupID expand Quantity MineTL
```

Examples:
```
C91 MG2 expand 2,500 mine-2  ; add 2,500 MINE-2 units to the group
C91 MG2 expand 1,800 mine-6  ; add 1,800 MINE-6 units to the group
```

=== Manufacture Items
A `manufacture` order instructs a FACTORY GROUP to start producing units.
The type of unit and the tech level of the unit are specified in the command.
The number of units is not.

```
ColonyID FactoryGroupID manufacture Quantity UnitCodeTL
```

Examples:
```
C91 FG9 manufacture 50,000 missile-8
```

=== Mine Resources
A `mine` order instructs a MINING GROUP to start mining and refining resources from a deposit.

```
ColonyID MiningGroupID mine Quantity DepositID
```

Examples:
```
C16 MG27 mine 25,000 DP19
```

NOTE: This feels wrong.
Why include quantity here?

== Trade Activity Phase
NOTE: The market phase was removed because player's abused it.
Is there a way to monitor/prevent that?

All orders in the Trade Activity phase are executed in the order that they're entered in the orders file.

All transactions in a market or trade station require the buyer to pay a 1% commission.
The commission is paid to the controlling player of the trade station or kept by the market for its own use.

NOTE: All players must pay the same commission at markets and trade stations.
There should be a way to charge different commissions in different locations and for different players.

=== Establish Trade Station Order
An `establish` order changes the function of an existing Orbital Colony to Trade Station.
This order is valid only if the colony is an Orbital Colony,
no smaller than 3,000 EMUs,
and has no factories or mines installed.

When a new trade station is established,
all ships from the controlling player's race are granted trade rights.

Format:
```
establish trade-station ColonyID Percentage?
```

The Percentage in the order establishes the base commission rate.
It is optional and defaults to 1% (the standard commission rate).
If include, it must be 1% or the order will be rejected.

Examples:
```
establish trade-station S200     ; change S200 to a trade station charging the standard commission
establish trade-station S200 1%  ; change S200 to a trade station charging 1% commission
```

=== Grant Trade Rights Order
A `grant` order allows any ship belonging to a race to engage in trade at a market or trade station.
The permission remains in place until explicitly revoked.

Format:
```
grant trade-rights SpeciesID ColonyID
```

To grant trade rights to all players, issue the order with "*" as the species identifier.

To grant trade rights to all markets and trade stations, issue the order with "*" as the colony identifier.

Examples:
```
grant trade-rights SP138 S200  ; allow player SP138 to trade at station S200
grant trade-rights SP2   *     ; open up all markets to SP2
grant trade-rights *     S201  ; open up S201 to all players
grant trade-rights *     *     ; open up all markets to all players
```

=== Revoke Trade Rights Order
A `revoke` order prohibits any ship belonging to a race to engage in trade at a market or trade station.
The prohibition remains in place until the controlling player grants trade rights again.

Format:
```
revoke trade-rights SpeciesID ColonyID
```

To revoke trade rights from all players, issue the order with "*" as the species identifier.

To revoke trade rights from all markets and trade stations, issue the order with "*" as the colony identifier.

Examples:
```
revoke trade-rights SP138 S200  ; prohibit player SP138 from trading at station S200
revoke trade-rights SP2   *     ; close all markets to SP2
revoke trade-rights *     S201  ; close S201 to all players
revoke trade-rights *     *     ; close all markets to all players
```

== Survey Phase
All orders in the Survey phase are executed in the order that they're entered in the orders file.

=== Probe Order
A `probe` order instructs a ship to conduct a detailed survey of a planet.

Probes are not actual units;
they use the ship's sensors to actively scan and analyze orbits, planets, colonies, and ships.

.Probe Chart
|===
|CODE|Probes per SENSOR unit per TURN|FUEL units used per PROBE per TURN

|SNSR-1 >|1 >|0
|SNSR-2 >|2 >|0
|SNSR-3 >|3 >|0
|SNSR-4 >|4 >|0
|SNSR-5 >|5 >|0
|SNSR-6 >|6 >|0
|SNSR-7 >|7 >|0
|SNSR-8 >|8 >|0
|SNSR-9 >|9 >|0
|SNSR-10 >|10 >|0
|===

Format:
```
probe ShipID #Orbit #Orbit...
```

NOTE: This doesn't allow for systems with multiple stars.
Consider accepting Star#Orbit in those systems.

To probe all planets orbiting the current star
issue the order with "*" as the orbit number.
(This is not the same as "probe all orbits"!)

Examples:
```
probe S28 #6        ; probe the planet in the 6th orbit
probe S31 #2 #4 #5  ; probe the planets in the 2nd, 4th, and 5th orbits
probe S42 *         ; probe all the planets orbiting the current star
```

=== Survey Order
A `survey` order instructs 1 PROFESSIONAL unit to pilot 1 TRANSPORT to undertake a detailed survey of a planet.
The survey takes one turn to complete.

Because the survey requires a transport, it will use fuel.

.Survey Fuel Chart
|===
|CODE|FUEL units used per SURVEY per TURN

|TRNS-1 >|0.1
|TRNS-2 >|0.4
|TRNS-3 >|0.9
|TRNS-4 >|1.6
|TRNS-5 >|2.5
|TRNS-6 >|3.6
|TRNS-7 >|4.9
|TRNS-8 >|6.4
|TRNS-9 >|8.1
|TRNS-10 >|10
|===

Format:
```
survey ShipID TransportTL #Orbit
```

Examples:
```
survey S23 transport-5 #3  ; ship S23 will survey the planet in the 3rd orbit
```

NOTE: This should probably just automatically use the smallest transport available.

=== Report Step
A probe will report the following information for each planet:

. Habitability Number
. Natural Resource Deposits
.. DepositID
.. Resource Type
.. Approximate quantity
. Open Colonies
.. ColonyID
.. EMU
.. Presence of Market
. Enclosed Colonies
.. ColonyID
.. EMU
. Orbital Colonies
.. ColonyID
.. EMU
.. Presence of Trade Station
. Ships
.. ShipID
.. EMU

The "approximate" mass or quantity is the log~10~ (rounded down) of the true amount.

Each survey will report the following information:

. Natural Resource Deposits
.. DepositID
.. Resource Type
.. Quantity
.. Location
.. Mining Difficulty

== Espionage

== Ship Movement Phase
All orders in the Ship Movement phase are executed in the order that they're entered in the orders file.
After all orders have been executed, Sensor reports are generated.

There are three types of jumps.
Interplanetary jumps move the ship between orbits around the current star.
Intersystem jumps move the ship between orbits of the stars in the current system.
Interstellar jumps move the ship between systems.
In an interstellar jump, the ship will always arrive in the 11th orbit.
When jumping to a system that has multiple stars, the target coordinates must include the star.

=== Jump Order
A `jump` order instructs a ship to engage its hyper-drive engines and move to a new system or a new orbit around the current star.

The destination must be a system, an orbit around the current star, or an orbit in the current system.

The destination coordinates are specified as #Orbit for an interplanetary jump.
They're specified as StarID#Orbit for an intersystem jump.
And as the SystemID for an interstellar jump.

.Hyperdrive Range Chart
|===
|CODE|Maximum distance per JUMP|Maximum Capacity per UNIT per JUMP

|HDRV-1|1 light year|1,000 MUs
|HDRV-2|2 light years|2,000 MUs
|HDRV-3|3 light years|3,000 MUs
|HDRV-4|4 light years|4,000 MUs
|HDRV-5|5 light years|5,000 MUs
|HDRV-6|6 light years|6,000 MUs
|HDRV-7|7 light years|7,000 MUs
|HDRV-8|8 light years|8,000 MUs
|HDRV-9|9 light years|9,000 MUs
|HDRV-10|10 light years|10,000 MUs
|===

When calculating capacity for ships with multiple engines,
use the lowest Tech Level of all engines,
then multiply by the total number of engines.

NOTE: If the total MUs of the ship (including hull and engines!)
exceeds the capacity of the engines,
it will consume the fuel but not move from its current location.
This is borked.

NOTE: The system does not idle engines that are not needed to make a jump.
It should.

.Jump Fuel Chart
|===
|Kind|FUEL units per UNIT per JUMP

|Interplanetary|4
|Intersystem|8
|Interstellar|40 * distance (in light years) jumped
|===

Intersystem jumps require twice the fuel of interplanetary jumps because the ship must first jump to the 11th orbit before jumping to the final destination.

If the ship is already in the 11th orbit of a system with multiple stars (it just jumped in, for example),
the jump order must be in the intersystem format,
but the fuel will be used at the interplanetary rate.

NOTE: That's not implemented yet.

Format:
```
jump ShipID Coordinates
jump ShipID #Orbit
jump ShipID StarID#Orbit
```

Examples:
```
jump S79 #6        ; (interplanetary) move S79 to orbit 6 of the current star
jump S81 B#2       ; (intersystem)    move S80 to orbit 2 of star B in the current system
jump S77 4/6/10    ; (interstellar)   move S77 to system 4/6/10, orbit 11
jump S78 8/3/9B    ; (interstellar)   move S78 to system 8/3/9 , orbit 11 of star B
```

=== Sensor Report Step
Active sensors on a ship automatically report some basic information each turn.
The report is generated in this step, which always happens last in the Ship Movement Phase.

Active sensors consume fuel during this step each turn.

.Sensor Fuel Chart
|===
|CODE|FUEL units per UNIT per TURN

|Survey|TL / 20
|===

NOTE: There is no way to turn off sensors to save on fuel.

Ship sensors automatically report the following information:

. Orbit and Kind of Planets
. Number of ships in each orbit
.. Approximate mass of each ship
. Number of orbital colonies in each orbit
.. Approximate mass of each orbital colony
.. Approximate production (tonnage) of each orbital colony

The "approximate mass" is the log~10~ (rounded down) of the true quantity.

== Draft orders
1 PROFESSIONAL unit is required to train up to 100 trainee units.
5% of trainees graduate to ??? each TURN.
TODO: This is not the right phase.

The total number of UNSKILLED WORKER units drafted must not exceed the number of available SOLDIER units.

There is no limit on the number of SOLDIER units that may be disbanded per TURN.

== Pay and Ration Phase

=== Pay Order
A `pay` order changes the amount of pay (in consumer goods) each population unit receives per turn.

The base pay for populations units is per the following chart:

.Base Pay Chart
|===
|CODE|Pay per UNIT per TURN|Pay when SHIP CREW

|CONSTRUCTION WORKER|0.500 CONSUMER GOODS|N/A
|PROFESSIONAL|0.375 CONSUMER GOODS|0.01 GOLD
|SOLDIER|0.250 CONSUMER GOODS|0.005 GOLD
|SPY|0.625 CONSUMER GOODS|N/A
|UNEMPLOYABLE|0.000 CONSUMER GOODS|N/A
|UNSKILLED WORKER|0.125 CONSUMER GOODS|N/A
|===

Only crew members receive pay when on a ship.
The crew will be paid in gold credits instead of goods.
They will exchange the credits for goods when at a colony controlled by their place or a market where they have trade rights.

WARNING: This can cause gold to transfer to another player unexpectedly.
Unscrupulous merchants will keep over-priced consumer goods on hand to exchange for gold.

Passengers (or cargo if in cryo-sleep) are not paid - they receive food but forfeit their normal pay of consumer goods.

Format:
```
pay ColonyOrShipID PopulationUnitID Percentage
```

To change the rate for all units, regardless of location, issue the order with "*" as the ColonyOrShipID.

Examples:
```
pay S38 professional 100%  ; reset  pay to base rate
pay  *  soldier       50%  ; change pay for all soldiers
pay S38 unskilled     90%  ; change pay to  90% of base rate
pay C27 unskilled    110%  ; change pay to 110% of base rate
pay S38 spy          115%  ; change pay to 115% of base rate
```

In the example, the player is paying UNSKILLED WORKER units more on colony C27 than she is on ship S38.

==== Ship Population
The crew of a ship consists of PROFESSIONAL and SOLDIER units.
Non-crew are PASSENGERS (or, potentially, cargo if in cryo.)

.Ship Crew Pay
|===
|CODE|Pay per UNIT per TURN|FOOD per UNIT per TURN

|PROFESSIONAL|0.01 GOLD|Per rationing orders
|SOLDIER|0.005 GOLD|Per rationing orders
|PASSENGER|N/A/|Per rationing orders
|===

When the ship docks at its home planet or any trade station,
the crew will exchange their accumulated GOLD for CONSUMER GOODS.

Passengers are never paid while being transported,
but they do receive a ration of FOOD every TURN per the ship's orders.

==== General Population
.General Population Pay
|===
|CODE|People in UNIT|Pay per UNIT per TURN

|CONSTRUCTION WORKER|200|0.500 CONSUMER GOODS
|PROFESSIONAL|100|0.375 CONSUMER GOODS
|SOLDIER|100|0.250 CONSUMER GOODS
|SPY|200|0.625 CONSUMER GOODS
|UNEMPLOYABLE|100|0.000 CONSUMER GOODS
|UNSKILLED WORKER|100|0.125 CONSUMER GOODS
|===

NOTE: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

=== Ration Order

.Food Ration
|===
|CODE|People in UNIT|Base FOOD per UNIT per TURN|Minimum FOOD per UNIT per TURN

|CONSTRUCTION WORKER|200|0.5 FOOD units|0.125 FOOD units
|PROFESSIONAL|100|0.25 FOOD units|0.0625 FOOD units
|SOLDIER|100|0.25 FOOD units|0.0625 FOOD units
|SPY|200|0.5 FOOD units|0.125 FOOD units
|UNEMPLOYABLE|100|0.25 FOOD units|0.0625 FOOD units
|UNSKILLED WORKER|100|0.25 FOOD units|0.0625 FOOD units
|===

NOTE: This chart lies about spies and construction workers.
They are aggregates - their numbers are the sum of their components.

== Rebellion
REBEL units represent the number of rebels.
They are not treated as a separate group.

The rebel militia consists of 10% of the rebel population.
These are the members that are ready and willing to engage in open rebellion.

== Rebel Increase Step
People become rebels when under-paid and/or starving.

.Quality of Life Factors
|===
|Factor|Increase

|Starvation >|30%
|Under Fed >|15%
|Under Paid >|15%
|Foreign Influence|See the spy tables
|===

=== Rebel Decrease Step
Once a rebel, almost always a rebel.

TODO: Add chart showing how to pay off rebels to return to loyal members of the state.

=== Open Rebellion Step
Open rebellion must be checked for every turn using the following chart:

.Rebellion Chance
|===
|Ratio of Soldiers to Militia|Chance of open rebellion|Committment of rebellion

|6:1 >|0% >|0%
|5:1 >|5% >|5%
|4:1 >|10% >|10%
|3:1 >|25% >|30%
|2:1 >|50% >|75%
|1:1 >|100% >|90%
|===

A rebellion will end when the ratio of soldier to rebel militia units is greater than 6 to 1 (or vice versa).
(NB - based on the surrender logic in combat.)

NOTE: It is possible for both sides to surrender at the same time?

=== Independence Check Step
The colony or ship will declare its indepedence if the soldiers surrender.

An independent colony, if it has factories or mines, will seek out trade stations to sell their goods and purchase needed raw materials.

An idenpendent ship will support itself via raids or hiring out as mercenaries.

TODO: Details on what becomes of the winners and losers.

== Naming and Control orders

== Birth Phase
The changes to population due to births are calculated in this phase.

The birth rate ranges from 0.25% to 2.5% of the population.
The exact number is determined by quality of life.
Pay rates, food rations, open spaces, and civil strife are all factored in.

Births are computed each TURN.
The crew and passengers on a ship are ignored when calculating the population increase.
All birth increases accumulate to the UNEMPLOYABLE population.

NOTE: Future rules will consider cloning.
It is not currently an option.

== Training Phase
The changes to population due to training are calculated in this phase.

All orders in the Training phase are executed in the order that they're entered in the orders file.
After all orders have been executed, the Job Corp step is executed.

There are two types of training: training (apprenticeship) and Job Corps.

Attrition happens automatically; the player must issue orders to train workers.

=== Train Order
A `train` order instructs PROFESSIONAL units to begin training UNSKILLED WORKER units.

A PROFESSIONAL unit may train up to 100 UNSKILLED WORKER units per TURN.

The trainees are unavailable for use until they have graduated from training.
They graduate at a rate of 5% per TURN.
After graduation, they are moved to the PROFESSIONAL population.

Format:
```
train ColonyOrShipID Quantity professional
```

Examples:
```
train S13 15,400 professional  ; assign 16 PROF units to train 154 UNSK units
```

=== Job Corps Step
The Job Corps trains UNEMPLOYABLE units to become UNSKILLED WORKER units.
The Corps is activated automatically when the percentage of UNEMPLOYABLE units is reaches 30% of the total population.
At the end of each turn that it is active, the Corps will move 2% of the UNEMPLOYABLE units to UNSKILLED WORKER units.

== Retirement Phase
The changes to population due to retirement are calculated in this phase.

5% of SOLDIER units retire each YEAR.
(TODO: convert this to per TURN.)
Upon retirement, SOLDIER units become PROFESSIONAL units.
This happens automatically; the player can not control the number of retirees.

== Death Phase
The changes to population due to deaths from starvation and natural causes are calculated in this phase.

=== Starvation
Deaths from starvation are computed each TURN.

Starvation takes place when the rationed FOOD amount is less than 0.0625 of a FOOD unit per POPULATION unit.
When that happens, the following formula determines how many POPULATION units starve.

    S = (M - R) / M

Where M is the minimum ration from the Food Ration Chart,
R is the actual ration,
and S is the fraction of the population that starves.

TODO: Convert this to use percentages instead of fractions of FOOD units.

=== Natural Causes
Deaths from natural causes are computed each TURN.
They are computed after deaths from starvation.

.Death Rate Chart
|===
|CODE|Deaths from Natural Causes per TURN

|CONSTRUCTION WORKER|0.0700%
|PROFESSIONAL|0.0625%
|SOLDIER|0.0750%
|SPY|0.0775%
|UNEMPLOYABLE|0.0625%
|UNSKILLED WORKER|0.0625%
|===

TIP: Soldiering, spying, and construction are dangerous activities;
that's why the death rate is higher for those groups.

== Research Phase
Changes to the tech level for a colony or ship are determined in this phase.

=== Applied Research Step
.Research Chart
|===
|Technological Level|Research Points Required|Total Research Points Required
|1|N/A|N/A
|2|100,000|100,000
|3|200,000|300,000
|4|400,000|700,000
|5|800,000|1,500,000
|6|1,600,000|3,100,000
|7|3,200,000|6,300,000
|8|6,400,000|12,700,000
|9|12,800,000|25,500,000
|10|25,600,000|51,100,000
|===

WARNING: Applied Research happens before Transferred Research.

=== Transfered Research Step
In this step, changes to the tech level from research bought or shipped to the colony are applied.

Note that a ship can't transfer research from a higher tech level.
(This is weird.)
A SHIP-4 could transfer TECH-1, TECH-2, TECH-3, or TECH-4.
It could not transfer TECH-5 or higher.

A ship may never gain more than a single tech level in a turn.
It is not allowed to skip tech levels.

A colony may gain multiple tech levels in a single turn,
but it may never skip a level.
For example, a colony with TECH-2 is visited by a ship carrying TECH-4.
The colony will not be able to apply the TECH-4 nor can it store the TECH-4 for future use.

If the same colony were visited by a ship carrying TECH-3 and TECH-4,
it would be able to use the TECH-3 to raise its level,
then use the TECH-4.

== News Service Reports

== Players

=== Nations

=== States

=== Governments

== Cluster

=== Systems

=== Planets

=== Colonies

[appendix]
== Units

=== Anti-Missile
=== Assault Craft
=== Assault Weapon
=== Automation
AUTO units may replace UNSKILLED WORKER units.
Each AUTO unit may replace up to its TECH LEVEL in UNSKILLED WORKER units.
An AUTO unit may not be split between groups.

.Automation Summary
|===
|CODE|Replacements per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|AUTO|Up to TL UNSKILLED WORKER units|4 * TL MU|0 FUEL units
|===

=== Colony
=== Construction Worker
=== Consumer Goods
.Consumer Goods Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN

|CONSUMER GOODS|0.6 MU|0 FUEL units
|===

=== Energy Shield
=== Energy Weapon
=== Factory
=== Farm
=== Food
.Food Summary
|===
|CODE|Feeds per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|FOOD|4 POPULATION units (400 people)|6 MU|0 FUEL units
|===

=== Hyper-Drive
.Hyper-Drive Summary
|===
|CODE|Range per UNIT|Capacity per UNIT|Mass per UNIT|Fuel per UNIT per JUMP

|HYPERDRIVE|TL light years|1,000 * TL MU|45 * TL MU|40 FUEL units per LY travelled
|===

Jumps between orbits ("interplanetary travel") are treated as 0.1 light years for FUEL.
(In other words, each HYPERDRIVE unit consumes 4 FUEL units jumping in system.)

=== Life Support
LIFE SUPPORT units use FUEL to replenish air and water in ships and colonies.

.Life Support Summary
|===
|CODE|Sustains per UNIT|Mass per UNIT|Fuel per UNIT per TURN

|LIFE SUPPORT|TL^2^ POPULATION units|8 * TL MU|TL FUEL units
|===

=== Light Structural
.Light Structural Summary
|===
|CODE|Mass per UNIT|Capacity

|LIGHT STRUCTURAL|0.05 MU|todo
|===

=== Military Robots
=== Military Supplies
=== Mine
=== Missile
=== Population
=== Probe
See SENSOR.

=== Professional
=== Rebel
=== Sensor
.Sensor Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN

|SENSOR|40 * TL MU|TL / 20 FUEL units
|===

=== Ship
=== Soldier
=== Space-Drive
.Space-Drive Summary
|===
|CODE|THRUST FACTOR per UNIT|Mass per UNIT|Fuel per UNIT per COMBAT ROUND

|SPACEDRIVE|1,000 * TL^2^|25 * TL MU|TL^2^ FUEL units
|===

In combat, the SHIP may move a DISTANCE up to its MASS divided by the total THRUST FACTOR of its SPACEDRIVE units each COMBAT ROUND.

=== Spy
=== Structural
.Structural Summary
|===
|CODE|Mass per UNIT|Capacity

|STRUCTURAL|0.5 MU|todo
|===

=== Transport
.Transport Summary
|===
|CODE|Mass per UNIT|Fuel per UNIT per TURN|Capacity

|TRANSPORT|4 * TL MU|TL^2^ / 10 FUEL units|200 * TL^2^ MU
|===

Note: FUEL usage is prorated.
The actual amount used is the percentage derived from cargo mass divided by capacity.

=== Unemployable
=== Unskilled Worker

[appendix]
== Notes
=== Farming Notes
There are three types of farms in the game.

1. Organic Farm units (OFARM) are open air farms and ranches.
These can be built only on habitable planets in orbits 1 through 5.
The maximum number of units is the _habitability number_ (HN) times 100,000.
2. Hydroponic Farm units (HFARM) use natural sunlight to grow grains and proteins in controlled, enclosed areas.
These can be built only on planets or orbital colonies in orbits 1 through 5.
3. Vat Farm units (VFARM) use artificial sunlight to grow grains and proteins in controlled, enclosed areas.

Each farming unit requires 3 Unskilled Worker units (UNW) and 1 Professional Worker unit (PWU) to be productive.

Unskilled Worker units may be replaced by Farming Automation units (AUFARM).

.Farming Production
|===
|Farm Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Organic Farm|OFARM|TL2|100.0 * TL FOOD units|6.0 + TL MU|0.5 * TL FUEL units
|Hydroponic Farm|HFARM|TL5|IF(TL<2,0,20*TL) FOOD units|6.0 + TL MU|0.5 * TL FUEL units
|Vat Farm|VFARM|TL10|IF(TL<6,0,20*TL) FOOD units|6.0 + TL MU|1.0 * TL FUEL units
|===

Exception: HFARM units in orbiting colonies use solar power, so their Fuel Use Per TURN is 0.0.

.Farm Chart
|===
|CODE|Production per UNIT per YEAR|Mass per UNIT|Fuel per UNIT per TURN|Location|Orbits|Solar Power

|FARM-1|100 FOOD|7 MU|0.5 FUEL|Planets with HN > 0|1..5|No
|FARM-2|40 FOOD|8 MU|1.0 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-3|60 FOOD|9 MU|1.5 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-4|80 FOOD|10 MU|2.0 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-5|100 FOOD|11 MU|2.5 FUEL|Planets or Orbital Colonies|1..5|Yes, if on Orbital Station in orbits 1..5
|FARM-6|120 FOOD|12 MU|6.0 FUEL|Any, including Ships|Any|No
|FARM-7|140 FOOD|13 MU|7.0 FUEL|Any, including Ships|Any|No
|FARM-8|160 FOOD|14 MU|8.0 FUEL|Any, including Ships|Any|No
|FARM-9|180 FOOD|15 MU|9.0 FUEL|Any, including Ships|Any|No
|FARM-10|200 FOOD|16 MU|10.0 FUEL|Any, including Ships|Any||No
|===

=== Manufacturing Notes
Factory (FACTORY) units process the raw materials created by Mining (MINE) units and turn them into finished goods such as star drives, robots, weapons, and consumer goods.
Essentially, FACTORY units produce everything except population, fuel, gold, and food.

To allow factories to produce different goods, the production pipeline is abstracted into Mass Units (MUs) of raw materials input and finished goods output.

.Factory Production
|===
|Factory Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Factory|FACTORY|TL10|20.0 * TL MASS Units|12.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

Exception: FACTORY units in orbiting colonies in orbits 1 through 5 use solar power, so their Fuel Use Per TURN is 0.0.

The amount of raw materials that can be processed by a factory unit in

The MUs produced are divided by the MUs of the good is the number of units of the good produced (all results are rounded down).

Examples needed here.

=== Mining Notes
Assigning MINE units to a DEPOSIT establishes CONTROL of that DEPOSIT.

Raw resources are found on planets, moons, and asteroid belts.
Resources are extracted from deposits by Mining (MINE) units.
MINE units are capable of mining, drilling, quarrying, and refining the raw resources.
For game purposes, we'll call all of those "mining."
The mined resources are also known as "raw materials."

There are two types of resources that may be mined in the game - ores and fuels.
Ores can contain precious metals and crystals (GOLD), non-precious metals (METL) or non-precious minerals (MNRL).

MINE units are not allowed to be installed on orbiting colonies;
they must be installed only on surface colonies.

.Mining Production
|===
|Mining Unit|CODE|Maximum Tech Level|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|Mining Unit|MINE|TL10|100.0 * TL MU|10.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

.Mining Production Chart
|===
|CODE|Production per UNIT per YEAR|Mass per UNIT|Fuel Use per UNIT per TURN

|MINE|100.0 * TL MU|10.0 + (2.0 * TL) MU|0.5 * TL FUEL units
|===

=== Population Notes
. Ration orders: Limit food consumption of a ship/colony.
. Pay orders: Set pay rates, which remain constant until changed, for a ship/colony.
. Draft orders: Recruit soldiers or trainees.
. Assembly orders: Form construction or spy units. (Assembly orders have other functions as well.)

=== Weapon Notes
.Weapons Chart
|===
|UNIT|CODE|DESCRIPTION|FUEL USE PER UNIT|MASS UNITS PER UNIT

|ASSAULT WEAPONS||Assault weapons are used by soldiers on the surface of a planet.|0|2
|ASSAULT CRAFT||Assault craft are land/space vehicles used to invade colonies of ships.|.1 fuel unit per turn|5 * TL
|MILITARY ROBOTS||Military robots can be used to replace soldier units.
The number of soldier units that can be replaced is equal to the military robot unit's TL * 2.|0|(2 * TL) + 20
|MISSILES||Missile can be used in any kind of combat; they are not as accurate as energy weapons.|0|4 * TL
|MISSILE LAUNCHERS||Missile launchers launch the missiles; the accuracy of a missile depends on the T.L. of the missile launcher.|0|25 * TL
|ANTI-MISSILES||Anti-missiles are launched by missile launchers also and destroy attacking missiles.
The % of missiles destroyed depends on the TL of the anti-missile.|0|4 * TL
|ENERGY WEAPONS||Energy weapons can be used in all combat situations except that of a surface colony to destroy a surface colony.
An energy weapon projects a powerful beam of concentrated energy.|4 * TL per COMBAT ROUND (CR)|10 * TL
|ENERGY SHIELDS||Energy shields deflect energy beams.
The amount of energy deflected depends on the TL of the shields.|10 * TL per CR|50 * TL
|MILITARY SUPPLIES||Military supplies consist of ammunition, medicines, etc., used up during combat.|0|.04 per unit
|===

[appendix]
== Orders

This section details the *orders* that *players* may issue.

[glossary]
ColonyID:: _ColonyID_ is a unique identifier for a colony.
It must start with the letter "C" followed by an _integer_.
Examples are C1, C50, C100.

ColonyOrShipID:: _ColonyOrShipID_ is either a _ColonyID_ or _ShipID_.
This is only used when the _order_ accepts either a colony or ship.
For example, a player may order S27 to raid S35 or C22.

DepositID:: _DepositID_ is a unique identifier for a resource deposit.
It must start with the letters "DP" followed by an _integer_.
Examples are DP1, DP100, DP10001.

FactoryCodeTL:: _FactoryCodeTL_ is composed of two parts separated by a dash.
The first part is the code for factory units.
The second part is the *TechLevel* of the factory unit.
Examples are FACTORY-1, FACTORY-3, FACTORY-9.

FactoryGroupID:: _FactoryGroupID_ is a unique identifier for a factory group.
It must start with the letters "FG" followed by an _integer_.
Examples are FG1, FG100, FG10001.

Integer:: _Integer_ is a whole number.
Examples are 0, 50, 100.

LootID:: _LootID_ is the name of a resource to target during a raid.
Examples are gold, fuel.

Number:: _Number_ is a real number or a whole number.
Examples are 0, 0.0, 50.2, 100.

MineCodeTL:: _MineCodeTL_ is composed of two parts separated by a dash.
The first part is the code for mining units.
The second part is the *TechLevel* of the mining unit.
Examples are MINE-1, MINE-3, MINE-9.

MiningGroupID:: _MiningGroupID_ is a unique identifier for a mining group.
It must start with the letters "MG" followed by an _integer_.
Examples are MG1, MG100, MG10001.

Percentage:: _Percentage_ is an _integer_ between 0 and 100 followed by a percent sign.
Examples are 0%, 50%, 100%.

PercentCommitted:: _PercentCommitted_ is a _percentage_.
It is TODO...

Quantity:: _Quantity_ is a whole number.
It must be greater than zero.
Examples are 1, 5,000, and 3,000,142.

ShipID:: _ShipID_ is a unique identifier for a ship.
It must start with the letter "S" followed by an _integer_.
Examples are S1, S50, S100.

TargetID:: _TargetID_ is either a _ColonyID_ or _ShipID_.
For example, a player may order S50 to support S27 in its attack against C22.

TechLevel:: _TechLevel_ is an integer in the range of 1..10.

UnitCodeTL:: _UnitCodeTL_ is composed of two parts separated by a dash.
The first part is the code for the unit.
The second part is the *TechLevel* of the unit.
Examples are MISSILE-2, HYPERDRIVE-3, and ENERGYSHIELDS-9.

[appendix]
== To Do
Ships should have unskilled workers to move cargo and perform routine maintenance.

[index]
== Index

