= Wraith User Guide
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

WARNING: The Reference Manual is the source of truth for the rules.
If this document does not match, this document is wrong.

The Wraith User Guide is copyright &copy; 2022 by Michael D Henderson.
Please see the LICENSE file for copying details.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Introduction

=== History
The Ryxen League was created to facilitate trade and settle disagreements between member nations.
The League worked well for many generations but eventually became corrupt and installed a dictator.

Rebellions started.
The corrupt government was outnumbered, so it created an AI system, WRAITH, to wage war against the member nations.

WRAITH was effective and brutal and soon started destroying entire worlds.

With the future looking bleak, the nations built a fleet of world ships to move their people to safety.
They built the ships with as little technology as possible to avoid detection, essentially bio-domes bolted to massive hyper-drives.

The fleet kept jumping until they had almost depleted their fuel reserves.
The ships split up, each nation looking to establish itself in the cluster.

The game takes place about thirty generations (12,000 "standard years") after the nations establish new homeworlds in the cluster.

The nations have thrived in isolation.
They've rebuilt their industry, rediscovered many technologies, and started exploring their system.

The history of their flight and migration has mostly been forgotten or transformed into legends.

That changed when they detected a signal originating beyond the furthest planet in their system.

== Setup
Wraith can be played as an individual competition or with players cooperating.

=== Individual Competition
In individual competition, each player manages unique species, running his/her own nation.

==== Victory Conditions
The "winner" is the first player to control 100 planets for 4 consecutive turns WITH no other player controlling more than 50 planets in any of those turns.

=== Shared Species
When sharing species, each player runs his/her own nation, but teams of players share a common species and a common homeworld.

The players that share a homeworld must cooperate to build ships and start exploring the system, or they can battle each other.

==== Victory Conditions
The "winner" is the first species to control 200 planets for 4 consecutive turns WITH no other species controlling more than 100 planets in any of those turns. Within each species, the player with the strongest economy is the "winner."

== Turn
Players complete a turn in the game by submitting a set of orders.
After processing the orders, the game-master sends each player a report with the results of their orders.

== Orders
The heart of the game is order processing.
Orders change the state of the game;
they start an assembly line to create items,
transfer cargo between systems,
engage in diplomacy and spying,
or attack other nations.

Orders are processed in phases.

.Phase Chart
|===
|Phase|Description

|Fuel Allocation|In this phase, fuel is allocated to units.
Fuel allocations are prioritized: life support is first, followed by farms, mines, then factories.
The allocation algorithm is naive and simple.
It attempts to allocate 100% of a unit's needs before moving to the next unit.
It never allocates proportionately.
|Farming Production|The farming production phase todo...
|Mining Production|The mining phase is used to extract resources from deposits and refine them into materials that can be used in the manufacturing phase.
|Manufacturing Production|The manufacturing production phase todo...
|Combat|The combat phase is used to project force against other player's assets.
|Set up|The set up phase is used to assemble new colonies and ships.
|Disassembly|This phase is used to disassembly operational units and make them ready to put into storage.
|Build Change|The build change orders phase is used to todo...
|Minch Change|The mining change orders phase is used to todo...
|Transfer|The transfer phase is used to todo...
|Assembly|The assembly phase is used to manufacture items, mine resources, and assemble units from storage.
|Market|The market and trade station phase is used to todo...
|Survey|This phase surveys systems, planets, colonies, and ships.
Reports are todo...
|Survey Reports|This phase produces the probe and sensor reports.
Todo...
|Espionage|The espionage phase todo...
|Movement|The movement phase is the only phase in which ships move.
Todo...
|Draft|This phase applies draft orders to move workers between population unit types todo...
|Pay and Ration|This phase todo...
|Rebellion|This phase todo...
|Rebel Changes|In this phase, the rebel population changes are applied.
Todo...
|Control|In this phase, naming and control orders are todo...
|Birth|In this phase, population increases due to births are calculated.
|News|In this phase, reports for the "news services" are created todo...
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

.Processing order
====
We'll use the following to show processing order:
```
1: S23 survey     ; order Ship 23 to survey the system it is currently in
2: S24 move 9-9-9 ; order Ship 24 to move to system 9-9-9
3: S24 survey     ; order Ship 24 to survey the system it is currently in
```

Please note that the line numbers are not part of the order.
The semicolon treats the remainder of the line as a comment.

Lines `1` and `3` would process in Phase 9 (Surveys).
Line `1` would process before Line `3` because it occurs earlier in the file.

Line `2` would process in Phase 11 (Ship Movement).
Because Ship Movement happens after Survey, `Ship 24` would not perform the survey in system `9-9-9`.
====

[index]
== Index

