= Wraith User Guide
Michael D Henderson <mdhender@example.com>
v0.0.2, 2022-06-03
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith User Guide (c) 2022 by Michael D Henderson

Wraith User Guide is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: The Reference Manual is the source of truth for the rules.
If this document does not match, this document is wrong.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Introduction

=== History
The Ryxen League was created to facilitate trade and settle disagreements between member nations.
The League worked well for many generations but eventually became corrupt and installed a dictator.

Rebellions started.
The corrupt government was outnumbered, so it created an AI system, WRAITH, to wage war against the member nations.

WRAITH was effective and brutal and soon started destroying entire worlds.

With the future looking bleak, the nations built a fleet of world ships to move their people to safety.
They built the ships with as little technology as possible to avoid detection, essentially bio-domes bolted to massive hyper-drives.

The fleet kept jumping until they had almost depleted their fuel reserves.
The ships split up, each nation looking to establish itself in the cluster.

The game takes place about thirty generations (12,000 "standard years") after the nations establish new home planets in the cluster.

The nations have thrived in isolation.
They've rebuilt their industry, rediscovered many technologies, and started exploring their system.

The history of their flight and migration has mostly been forgotten or transformed into legends.

That changed when they detected a signal originating beyond the furthest planet in their system.

=== What is Wraith?
Wraith is a strategic turn based game where you explore a cluster of stars.
Your ships will discover planets and technology that will help you grow your nation.
As the ruler, you set policies and decide how best to allocate resources to meet your objectives.

You will meet other species in the game.
Most will be other players, but a few will be independent colonies or ships.
They can be cooperative and engage in trade or belligerent and engage in war.

=== How to Play
When you join a game, you'll receive a report showing the location of your home planet,
your population, the technologies you've mastered, the ships in your fleet,
and the farms, mines, and factories that support your world.

Each turn you will submit orders to the game master.
Your orders determine what goods are produced, how trade is carried out, and can even start wars.

A key to the game is keeping supplies flowing to the units that need them.
Ships need trained crews as well as fuel and maintenance.
Factories require labor, power, and raw materials to manufacture goods.

Every player's orders are processed at the same time,
which is usually just after the deadline for submitting them.

After the results are calculated, you'll receive an updated report.
It has the same format as the initial report.
Because the report can contain a lot of information,
you'll also get a summary of the changes from the prior turn.

== Getting Started
The game manager (GM) will grant you access to the game's website when you start a game.

You will find a table with all the systems in your cluster.
It lists the location (using X/Y/Z coordinates) for each system.

The table shows plus the number and types of stars in the system.
Additional information like  will be added when your ships visit the system

Your home system (the system that your home planet is in) will show the planets and their orbits.
You get a summary of the colonies, population, industry, and resources, too.

As your ships explore the cluster,
the table will be updated with similar summaries,
along with the turn that they visited.
If they've conducted surveys,
there will be a link to the detailed survey report.

TIP: The reports always use the most current information available to your nation.
Updates are made automatically if you have a colony in the system;
otherwise only when one of your ships visits.

Plan ahead to manage your population and natural resources,
and ensure the right quantity of materials are where they need to be,
when they are needed.

== The first turn
All players start on their own home planet with the same population, infrastructure, and inventory.

The cluster is generated randomly, so the amount of natural resources in the home system will vary.
Some systems will be close to other systems, making exploration easy;
some will be farther away, making exploration harder.

It all starts with food.
Farms, as long as they have sufficient labor and fuel, will produce food every turn.
They need ships to move the harvest to markets and to deliver fuel.

Labor comes in the form of managers (professionals) and workers (unskilled workers or robots).
Fuel is extracted and refined by mining units.
Like farms, if they have sufficient labor and fuel they'll produce raw materials like fuel, gold, and metal every turn.
(Unlike farms, the deposits worked by mines will eventually run out, but you don't need to worry about that just yet.)

Again, just like farms, the labor is managers (professionals) and workers (unskilled workers or robots).
They need ships to move the raw materials to markets, ships to deliver food to the workers,
and, if they're not making fuel themselves, ships to bring the fuel to power the heavy machinery.

All those ships are built in factories.
Factories that need managers (professionals) and workers (unskilled workers or robots) on the assembly lines.
The assembly lines take fuel and metals from the mines to build ships.
Not just ships, but everything
(well, everything except for food and raw materials, which are produced only by farms and mines.)
you'll use in the game.
That includes the farming and mining equipment used on all of those farms and mines.

Luckily, you'll start the game with farms, mines, and factories,
plus some ships and transports to keep things moving.
All you have to do is send out the orders that coordinate all the pieces.

((TODO)): suggestions for the first few turns...

== People
There are some things to know about people in the game.
They're born, they die from natural causes or combat injuries, and they're the only thing in the game that you can give orders to.

In game terms, the population is split into groups according to the skills that they have.
*Professionals* are the managers, bureaucrats, and pilots.
*Workers* are those that get things done.
They do the heavy lifting on the docks, operate machinery in the mines and factories, and tend the farms.
*Soldiers* secure the borders, fly assault craft, and wage wars.

The remainder is the *UNEMPLOYED* group.
This includes young people, old people, students, teachers, artists, and even convalescing soldiers.

There are two categories for the general population: *CONSTRUCTION CREW* and *SPY TEAM*.
A construction crew is composed of professionals and workers that are specially trained to build ships and colonies.
A spy team is composed of professionals and soldiers that are trained to conduct espionage and counter-espionage.

Finally, there is the *REBEL* contingent.
These are the people that are discontent with your governing or local conditions.
Rebels can come from any group (professional, soldier, worker, or unemployed).
They can even be a member of a special category (construction crew or spy team), too.
If they're really, really unhappy, they will try to overthrow your government.
Rebel soldiers and spy teams can be very disruptive!

Two of the basic orders for population are pay and rations.
You pay people with consumer goods produced by your factories.
You feed them with the food from your farms.
The "pay" order declares how much each group is paid per turn.
The "ration" order determines how much food is distributed per turn.
You start the game with pay and rations set to 100% of the base rate
(see Chart ??? for details on the base rate).

== Places

The game takes place in a small cluster that is packed with systems for you to explore.

Every system contains a star; some systems will have more than one star.
Each star has 10 orbits; the orbits can be empty or contain a "world."

NOTE: World is a generic term for a gas giant (Jupiter, Saturn),
a terrestrial planet (Mercury, Venus, Earth, Neptune),
or an asteroid belt (our asteroid belt, not the kind in movies).

Worlds are important because they are the only place you can build colonies
(either on the surface of the world or orbiting it).

Each system has one hyper-nexus, no matter how many stars it has.
The hyper-nexus is the arrival point for ships travelling from remote systems.
On the turn following their arrival,
ships can move to any star's orbit in the system.

=== Identifying Places
To keep things straight, all systems, stars, and worlds have unique identifiers.

A SystemID uses the X, Y, Z coordinates for the system.

NOTE: `15/14/12` is the system at 15, 14, 12.

A StarID is based on the system's SystemID and the number of stars in the system.
If there is just one star, the StarID is the same as the SystemID.

NOTE: `15/14/12` is the one (and only) star in system `15/14/12`.

If there are many stars, we use the SystemID with a letter appended to it.
The primary star uses "A," the secondary uses "B," the third "C," and so on.

NOTE: `9/18/6C` is the third star in system `9/18/6`.

WorldID uses the StarID followed by "#" and the orbit number.

NOTE: `15/14/12#5` is the world in the 5th orbit of star `15/14/12`.
`9/18/6C#3` is in the 3rd orbit of `9/18/6C`.

The identifiers can be hard to remember and type, so you have the option of naming stars and worlds.

== Things
Items that you can grow on a farm, extract from a mine, or build in a factory are called "units."

.Units Produced by Farms
|===
|Name|Description

|food|Farm fresh, dehydrated, grown in vats, anything that your people consume for caloric benefit.
|===

NOTE: There are two types of farms: open air and enclosed hydroponic.
Hydroponic farms can use natural sunlight (but only in the first five orbits)
or artificial sunlight (in any orbit).

[#unitsProducedByFactories]
.Units Produced by Factories
|===
|Name|Description

|anti-missile missile|Used to counter incoming missile barrages in combat.
|assault craft|Used in ground assault during combat. Crewed by soldiers or milbots.
|assault weapon|Used to augment soldiers during combat.
|consumer goods|Used to pay your people and in trade.
|energy shield|Absorbs and deflects damage from energy weapons in combat.
|energy weapon|Point to point energy beams used to destroy ships and colonies in combat.
|factory equipment|Machinery and tooling used by factories to build units.
|farming equipment|Machinery, fertilizers, and pesticides used to support farming.
|hyper-drive|Used to move ships between systems.
Ships using hyper-drives do not travel in normal space between systems.
|life support|Cleans, purifies, and recirculates air and water in enclosed systems like ships and some colonies.
|milbot|Robotic automation unit replacing soldiers in ship crews and combat operations.
|military supplies|Consumable equipment used by soldiers and milbots during every round of combat.
|mining equipment|Machinery and rigs used for mining, drilling, and refining.
|missile|Guided rockets with explosive warheads used to attack ships and colonies in combat.
|missile launch tube|Launch and guidance system for missiles and anti-missile missiles.
|orbital-drive|Engines used to move ships in orbit around a world.
Does double duty as impulse drives during combat.
|sensor|Active and passive scanning equipment.
|structure|Basic unit for constructing ships and colonies.
Framing and building kit using components that can survive the stresses of space and hostile, radioactive worlds.
|structure, light|A lighter structure unit.
|structure, super-light|A much lighter (some would say "super light") structure unit.
|transport|A shuttle used to move cargo between ships and colonies; also used in combat to transfer soldiers between ships and colonies.
Cargo flights are piloted by professionals; combat missions by soldiers or milbots.
|workbot|Robotic automation unit replacing workers on farms and in factories and mines.
|===

.Units Produced by Mines
|===
|Name|Description

|fuel|Fuel is used to power farms, factories, mines, and almost all other units.
It includes oil, nuclear compounds, and sci-fi elements like trilithium.
Anything and everything that powers industry or starships.
|gold|This represents all precious metals and crystals, not just gold.
It can be anything that is valued more for itself than its usefulness in manufacturing.
This is the standard unit accepted for trade between nations.
|metal|All non-precious metallic ores.
|non-metal|Anything that isn't fuel, gold, or a metal.
This is all non-precious non-metallic ores and organic compounds.
|===

NOTE: We use mines to harvest timber and oil, too.

== Colonies
We have three types of colonies: open, enclosed, and orbital.

Open colonies are built on the surface of habitable terrestrial planets.
They never use life support.
They're the only colony that supports open air farming.

Enclosed colonies are built on the surface of any terrestrial planet (habitable or not),
the moons of a gas giant,
and on large rocks in an asteroid belt.
They are enclosed, so they require life support.
You can build hydroponic farms in them.

Orbital colonies can be built in orbit around any world.
They are in space, so they require life support.
You can build hydroponic farms in them.
If the colony is in the first 5 orbits of the star,
the hydroponic farms can use solar power instead of regular fuel units.

== Ships
There are three types of ships in the game: space ships, transports, and assault craft.
All three are space worthy.
The main difference is that space ships are designed to move between systems,
transports to move between ships and colonies,
and assault craft for combat operations.

== Farms
Farms use fuel and labor to produce food.

.Farms Chart
|===
|Unit|Fuel used per TURN|Food produced per YEAR|Type|Sunlight|Notes

|FARM-1 >|0.5 >|100|Open air|Natural|The maximum number of FARM-1 units on a world is 100,000 times the habitability number.
|FARM-2 >|1.0 >|40|Hydroponic|Natural|These units are solar-powered and require no FUEL when installed in an orbital colony.
|FARM-3 >|1.5 >|60|Hydroponic|Natural|These units are solar-powered and require no FUEL when installed in an orbital colony.
|FARM-4 >|2.0 >|80|Hydroponic|Natural|These units are solar-powered and require no FUEL when installed in an orbital colony.
|FARM-5 >|2.5 >|100|Hydroponic|Natural|These units are solar-powered and require no FUEL when installed in an orbital colony.
|FARM-6 >|6.0 >|120|Hydroponic/Vat|Artificial|
|FARM-7 >|7.0 >|140|Hydroponic/Vat|Artificial|
|FARM-8 >|8.0 >|160|Hydroponic/Vat|Artificial|
|FARM-9 >|9.0 >|180|Hydroponic/Vat|Artificial|
|FARM-10 >|10.0 >|200|Hydroponic/Vat|Artificial|
|===

Each FARM unit requires 1 professional unit and 3 worker units (or the equivalent in workbot units).

.Farm Location Chart
|===
|Unit ^|Orbits ^|Open Colony ^|Enclosed Colony ^|Orbital Colony ^|Ship

|FARM-1 ^|1..5 ^|yes ^|no ^|no ^|no
|FARM-2 ^|1..5 ^|yes ^|yes ^|yes ^|no
|FARM-3 ^|1..5 ^|yes ^|yes ^|yes ^|no
|FARM-4 ^|1..5 ^|yes ^|yes ^|yes ^|no
|FARM-5 ^|1..5 ^|yes ^|yes ^|yes ^|no
|FARM-6 ^|any ^|yes ^|yes ^|yes ^|yes
|FARM-7 ^|any ^|yes ^|yes ^|yes ^|yes
|FARM-8 ^|any ^|yes ^|yes ^|yes ^|yes
|FARM-9 ^|any ^|yes ^|yes ^|yes ^|yes
|FARM-10 ^|any ^|yes ^|yes ^|yes ^|yes
|===

=== Production
Farm production is based on one rule:
if the FARM unit was active the prior three turns and it is active this turn,
it will produce FOOD units.
(Active just means that it had the required number of FUEL and labor units allocated to it.)

WARNING: There's a bug in the current rules - farms only output food once a year.
That should be changed to something more like "farms start producing food after a year."
But that feels wrong, too.

== Mines
Mines use fuel and labor to extract and refine natural resources into materials for factories or trade.

.Mines Chart
|===
|Unit|Fuel used per TURN|MASS Units produced per YEAR

|MINE-1 >|0.5 >|100 MUs
|MINE-2 >|1.0 >|200 MUs
|MINE-3 >|1.5 >|300 MUs
|MINE-4 >|2.0 >|400 MUs
|MINE-5 >|2.5 >|500 MUs
|MINE-6 >|3.0 >|600 MUs
|MINE-7 >|3.5 >|700 MUs
|MINE-8 >|4.0 >|800 MUs
|MINE-9 >|4.5 >|900 MUs
|MINE-10 >|5.0 >|1,000 MUs
|===

NOTE: MINE units may be installed in open or enclosed colonies, never in an orbital colony or ship.

Each MINE unit requires 1 professional unit and 3 worker units (or the equivalent in workbot units).

=== Production
Mines are slightly more complicated than farms:
if the MINE is in a mining group and the MINE unit was active the prior three turns and it is active this turn and the DEPOSIT is not empty,
it will produce refined material units.
(Active just means that it had the required number of FUEL and labor units allocated to it.)

== Factories
Factories use fuel, labor, and the refined metals and non-metals from mines to build the items listed in the
<<unitsProducedByFactories,Units Produced by Factories>> chart.

Factories benefit from the use of assembly lines and the economies of scale,
so the amount of labor used by each factory unit depends on the size of the factory group that it is in.

.Factory Group Labor Chart
|===
|Size (in factory units)|Professional units|Worker units

|1 to 4 >|6 per Factory unit >|18 per Factory unit
|5 to 49 >|5 per Factory unit >|15 per Factory unit
|50 to 499 >|4 per Factory unit >|12 per Factory unit
|500 to 4,999 >|3 per Factory unit >|9 per Factory unit
|5,000 to 49,999 >|2 per Factory unit >|6 per Factory unit
|50,000 or more >|1 per Factory unit >|3 per Factory unit
|===

.Factory Group Labor Chart
|===
|Size (in FACT units)|Professional units|Worker units

>|50,000 or more >|1 times number of FACT units >|3 times number of FACT units
>|5,000 or more >|2 times number of FACT units >|6 times number of FACT units
>|500 or more >|3 times number of FACT units >|9 times number of FACT units
>|50 or more >|4 times number of FACT units >|12 times number of FACT units
>|5 or more >|5 times number of FACT units >|15 times number of FACT units
>|4 or less >|6 times number of FACT units >|18 times number of FACT units
|===

The worker units can be replaced with the equivalent in workbot units.

.Factories Chart
|===
|Unit|Fuel used per TURN|MASS Units produced per YEAR

|FACT-1 >|0.5 >|20 MUs
|FACT-2 >|1.0 >|40 MUs
|FACT-3 >|1.5 >|60 MUs
|FACT-4 >|2.0 >|80 MUs
|FACT-5 >|2.5 >|100 MUs
|FACT-6 >|3.0 >|120 MUs
|FACT-7 >|3.5 >|140 MUs
|FACT-8 >|4.0 >|160 MUs
|FACT-9 >|4.5 >|180 MUs
|FACT-10 >|5.0 >|200 MUs
|===

NOTE: FACT units are solar-powered and require no FUEL when installed in an orbital colony in the first 5 orbits.

NOTE: FACT units may be installed in any colony, but never in a ship.

=== Production
Factories are the most complicated unit to manage in the game.

Turn 1, you order ??? construction crews to assemble 35,000 FACT-1 units.

Turn 2, you assign those units to factory group 1 (FG1) and order them to build LIFESUPPORT-1 units.
Each FACT-1 unit can ingest 20 MU of resources per YEAR, so FG1 can process up to 700,000 MU per year.
Each LIFESUPPORT-1 unit will require 1 year (4 turns) and 25 MU of METAL and 20 MU of NON-METAL to build.
With each life support unit using 45 MU total of resources,
and the factory group processing up to 700,000 per year,
the group will be able to build 17,500 engines per year.

Turn 3, 70,000 professional and 210,000 worker units report to FG-1 to start producing LIFESUPPORT-1 units.
Ships deliver 435,700 MU of METAL, 350,000 MU of NON-METAL, and 17,500 FUEL units.
At the end of the turn, 17,500 engines are in progress and your report will look something like:

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1  17,500       0       0         0

On Turn 4, we have the same labor and materials delivered.
At the end of the turn, your report will look something like:

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1  17,500  17,500       0         0

On Turn 5, we have the same labor and materials delivered.
At the end of the turn, your report will look something like:

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1  17,500  17,500  17,500         0

On Turn 6, we have the same labor and materials delivered.
At the end of the turn, you'll have 17,500 engines complete and ready to load out.
Your factories are operating at maximum capacity, so your report will look something like:

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1  17,500  17,500  17,500    17,500

On Turn 7, something terrible happens and the ship delivering the NON-METAL resources doesn't arrive.
You're missing a required input, so the factories can't start any new engines this turn.
The engines that are in work continue through the process, so you end up the turn with another 17,500 engines complete.

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1       0  17,500  17,500    17,500

On Turn 8, you receive your NON-METAL resources, but another ship is delayed and you only have 8,750 FUEL units available.
Fuel shortages are spread across the entire factory group,
so all units in the group will operate at 50% capacity
(8,750 / 17,500 = 50%).
Your report will look something like:

    Group  Unit___  Quantity  Build________     25%     50%     75%  Complete
    FG1    FACT-1     35,000  LIFESUPPORT-1   8,750   8,750  17,500     8,750

((TODO)): would this be clearer if we used an example that didn't track the fuel?
maybe life support at 3 + 8?

((TODO)): show storage?

((TODO)): this should be its own wiki.

== Rebellion
You want to avoid rebellion because the two outcomes are bad and worse.
If your government wins, you have to deal with the aftermath.
All the casualties were your people.
Your infrastructure was destroyed by sabotage and combat.
You need to move more soldiers or milbots into your colonies to "maintain the peace."

If the rebels win, they declare independence.
You've lost your troops, your infrastructure,
and now other nations have the opportunity to gain control of your colonies and ships.

During a rebellion, the game engine takes control of the rebel forces.
For the most part, rebels are untrained and unarmed civilians.
They know that your loyal soldier and milbots will win in open combat
so they'll sabotage factories and mines and engage in hit-and-run raids.
They like to eat, so farms are only a target if they're exporting food.
They'll wait until they significantly outnumber your troops before engaging them directly.

During the "guerilla tactics" phase,
you can use your spy units to convert, capture, or eliminate rebels.
Once open combat begins, only soldiers and milbots can be used.

[appendix]
== Bad Writing Ahead
=== The Circle of Supply Chains
The supply chain (to abuse a metaphor) is a circle that begins and ends with farms.

Farms produce food to feed factory workers.
Factory workers produce mining equipment.
Mine workers use the equipment produce fuel and metal.
The fuel and metal are transported to factories in ships crewed by people who consume food and air.
Factories consume the fuel and metal to produce farming equipment.
Ships transport the equipment to farm colonies, which use them to produce more food.

TIP: You must build ships to transport people, food, and materials to your colonies.
If you don't, the mines and factories will shut down.
Starving people will start a rebellion.

[appendix]
== Important Terms
We created a separate glossary because of the amount of jargon and the number of abbreviations in this.

((TODO)): should all this be moved to the glossary?

=== Cluster
The ((cluster)) is the area in the galaxy that the game takes place in.
It contains all the systems and planets that you'll work with.

=== System
A ((system)) in the game contains one or more stars.

The identifier (SystemID) for a system is its coordinates in the format "X/Y/Z".

TIP: ((SystemID)) is the system identifier.
For example `5/2/9`.

=== Star
A star in the game has exactly 11 orbits, numbered 1 through 11.

The identifier (StarID) for a star depends on the number of stars in the system.

If there is only one star, the star's ID is the same as the system's ID.

If there are multiple stars, the star's ID is the system's ID followed by a sequence letter.
The sequence letter will be "A" for the first star in the system, "B" for the second star, etc.
If system `1/2/3` had just one star, that star's ID would be `1/2/3`.
If there were four stars in that system, they would be identified as `1/2/3A`, `1/2/3B`, `1/2/3C`, and `1/2/3D`.

TIP: ((StarID)) is the star identifier.
For example `5/2/9` or `1/2/3D`.

=== Orbit
An ((orbit)) in the game can be empty, contain a planet, or be the connection between the stars in the system with multiple stars.

The identifier (OrbitID) for an orbit is an octothorpe ("#") followed by the orbit number.

The 11th orbit for a star serves two purposes.
. It is the entry point for hyper-drive jumps.
. In systems containing multiple stars, it is the nexus between the stars.

TIP: An OrbitID is `#4`.

=== Planet
"Planet(((planet)))" is a generic term for the occupant of an orbit that is not empty.
The occupant can be an asteroid belt, a gas giant, or a terrestrial.

NOTE: "Terrestrial" does not imply a habitable
https://en.wikipedia.org/wiki/Class_M_planet[Class M]
planet.
Mercury, Venus, and Neptune are all terrestrial.

The identifier (PlanetID) for a planet is its StarID with the OrbitID appended.

NOTE: Planets orbit a star in a system.
That is why the StarID is required to identify it.

TIP: ((PlanetID)) is the planet identifier.
For example `5/2/9#2` or `1/2/3D#4`.

==== Habitability Number
((Habitability Number)) in the game is a measure of the maximum population that a planet can comfortably sustain in an open colony.
The Habitability Number is usually abbreviated as "((HN))."
The value ranges from 0 to 25.

An ((uninhabitable planet)) has an HN of 0.
That means that it can not support any population at all.
You must build an enclosed colony with life support for people to survive on the surface of the planet.

A ((habitable planet)) has an HN between 1 and 25.
People may live on the surface without life support.

==== Natural Resource
Every planet contains up to 35 deposits of natural resources.
Resources include gold (an abstraction of precious metals and crystals),
fuel (an abstraction of organic and inorganic power sources),
metals (an abstraction of all metallic ores except gold),
non-metal (an abstraction of almost everything else).
Natural resources must be mined and refined,
turning them into raw materials,
before they can be used.

==== Asteroid Belt
An asteroid belt (or just "asteroid") in the game is a type of planet that is dispersed through the entire orbit.
It is composed of many small, irregular bodies ranging in size from particles of dust to 100's of kilometers in diameter.
These bodies (or "rocks") are composed of carbon, silicate, metals, non-metals, and ice.

Enclosed colonies may be built on the surface of larger rocks in an asteroid belt.

==== Gas Giant
A gas giant in the game is a type of planet with an atmosphere of mostly helium and hydrogen (like Jupiter).
The surface of a gas giant is inaccessible because of the high mass and temperatures,
so enclosed colonies may be built on the surface of moons orbiting the gas giant.

==== Terrestrial
A terrestrial in the game is a planet that isn't a gas giant or an asteroid belt.
It is large enough to be round and sweep its orbit clear.
It may have an atmosphere and a metal core like Mars,
no atmosphere like Mercury,
an ice giant like Neptune,
or a frozen ball of methane.

Colonies may be built on the surface of terrestrials
(or, in the case of ice giants, the surface of the moons orbiting them).

A terrestrial with a habitability number of zero is called an uninhabitable terrestrial.
With a value greater than zero, it is called a habitable terrestrial.

=== Colony
There are three types of colonies in the game: open, enclosed, and orbital.

Open colonies may be built on the surface of habitable terrestrials
(those with a habitability number greater than zero).
They don't require life support to sustain the population.

Enclosed colonies may be built on the surface of unihabitable terrestrials
(those with a habitability number of zero),
and in an asteroid belt.
They require life support to sustain the population.

Orbital colonies may be built in orbit around any planet.
They may not be built on the surface of a planet or in an empty orbit.
They require life support to sustain the population.

.Colony Location Chart
|===
||On Planet Surface|On Asteroid Belt|In Orbit|Life Support Required|Maximum Size

|Open Colony ^|Habitable Terrestrial ^|NO ^|NO ^|NO ^|UNLIMITED
|Enclosed Colony ^|Any Terrestrial ^|YES ^|NO ^|YES ^|UNLIMITED
|Orbital Colony ^|NO ^|NO ^|Any Planet ^|YES ^|UNLIMITED
|===

=== Ship
A ship in the game is built with a hull, engines, cargo holds, and weapons.

Ships require space-drives to move in a planet's orbit.
They require hyper-drives to move between systems.

NOTE: Ship building is discussed in detail in ((TODO)).

=== Turn
Players complete a turn in the game by submitting a set of orders.
After processing the orders, the game-master sends each player a report with the results of their orders.

=== Order
The heart of the game is order processing.
Orders change the state of the game;
they start an assembly line to create items,
transfer cargo between systems,
engage in diplomacy and spying,
or attack other nations.

Orders are processed in phases.
This helps players know when an order will be implemented.

.Phase Chart
|===
|Phase|Description

||((TODO)): sync this with the reference manual.
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

.Processing Sequence
====
To illustrate,
let's assume that S23 and S24 are both in system `8/8/8`
and that we have the following orders in our file:

[source]
----
1: survey S23        ; order Ship 23 to survey the system it is currently in
2: move   S24 9/9/9  ; order Ship 24 to move to system 9/9/9
3: survey S24        ; order Ship 24 to survey the system it is currently in
----

Please note that the line numbers are not part of the order.
The semicolon treats the remainder of the line as a comment.

Lines `1` and `3` would process in Phase 9 (Surveys).
Line `1` would process before Line `3` because it occurs earlier in the file.
S23 would survey its current location, system `8/8/8`.
S24 would survey the same location because it has not moved yet.

Line `2` would process in Phase 11 (Ship Movement).
S24 would move to system `9/9/9`.
Because Ship Movement happens after Survey,
the ship would not perform the survey in system `9/9/9`.
====

== Production
=== Farming
=== Mining
=== Manufacturing
== Diplomacy and Trade
=== Markets
== Combat
== Rebellion

== Winning
Wraith can be played as an individual competition or with players cooperating.

=== Open-Ended
In an open-ended game, there are no victory conditions.

((TODO)): support open-ended games

=== Individual Competition
In individual competition, each player manages unique species, running his/her own nation.

==== Victory Conditions
The "winner" is the first player to control 100 planets for 4 consecutive turns WITH no other player controlling more than 50 planets in any of those turns.

=== Shared Species
When sharing species, each player runs his/her own nation, but teams of players share a common species and a common home planet.

The players that share a home planet must cooperate to build ships and start exploring the system, or they can battle each other.

==== Victory Conditions
The "winner" is the first species to control 200 planets for 4 consecutive turns WITH no other species controlling more than 100 planets in any of those turns. Within each species, the player with the strongest economy is the "winner."

[appendix]
== Charts

.Unit Descriptions
|===
|CODE|Name|DESCRIPTION

|AMSL|Anti-Missile|Anti-missile units are used in combat to destroy incoming missiles.
|ATKC|Assault Craft|Assault craft units are small, highly manuverable ships used in combat for attacks and raids.
|ATKW|Assault Weapons|Assault weapons are used by soldiers in combat situations.
|AUTO|Automation|
|CONW|Construction Worker|A notational unit used to track the number of Professional and Unskilled Workers trained to build, assemble, and disassemble other units.
|CGDS|Consumer Goods|
|ENSH|Energy Shield|Energy shields absorb and disipate the damage from energy weapons.
|ENWP|Energy Weapon|Energy weapon units are line-of-sight beams of wanton destruction used to attack enemy colonies and ships in combat.
|FACT|Factory|
|FARM|Farm|
|FOOD|Food|A farmed resource used to feed people in the game.
|FUEL|Fuel|A mined resource used to power other units in the game.
|GOLD|Gold|A mined resource used as currency and also in manufacturing.
This represents all precious metals and crystals, not just gold.
It might morph into "credits" in the future.
|HDRV|Hyper Drive|
|LFSP|Life Support|
|LSU|Light Structure|A type of structural unit built only in orbiting colonies.
The mass of LSU units is 10% of SSU units, but each LSU can replace one SSU when building colonies, ships, and enclosed storage.
|MILR|Military Robot|Military robot units replace soldiers on combat missions.
|MILS|Military Supplies|Military supplies are the items used by soldiers in combat.
|MINE|Mine|
|MSL|Missile|Missile units are used in combat to attack enemy targets.
|MSLT|Missile Launcher|Missile tubes are used in combat to fire anti-missile and regular missiles.
|MTL|Metallic Resource|A mined resource used by factories to manufacture finished goods.
|NMTL|Non-Metallic Resource|A mined resource used by factories to manufacture finished goods.
|PROF|Professional Worker|A group of 100 people trained to manage people and projects.
|RBEL|Rebel|A notational unit used to track the number of potential rebels in the population.
|SLDR|Soldier|A group of 100 people trained for military operations.
|SLSU|Super Light Structure|A type of structural unit built only in high-tech factories on orbiting colonies.
The mass of SLSU units is 1% of SSU units, but each SLSU can replace one SSU when building colonies, ships, and enclosed storage.
|SPY|Spy|A notational unit used to track the number of Professional Workers and Soldiers trained in espionage and counter-espionage.
|SNSR|Sensor|
|SDRV|Space Drive|
|SSU|Standard Structure|The standard type of structural unit used for building colonies, ships, and enclosed storage.
|TRNS|Transport|
|UEMP|Unemployable|A group of 100 people that are not Unskilled Workers, Professional Workers, or Soldiers.
"Uenemployable" means that members of this group can not be drafted.
|USKW|Unskilled Worker|A group of 100 people trained as general labor.
|===

.Unit Mass Units
|===
|CODE|MASS Units (MUs) per UNIT

|AMSL|TL * 4
|ATKC|TL * 5
|ATKW|2
|AUTO|
|CONW|
|CGDS|
|ENSH|TL * 50
|ENWP|TL * 10
|FACT|TL * 2 + 12
|FARM|TL + 6
|FOOD|6
|FUEL|
|GOLD|
|HDRV|TL * 45
|LFSP|TL * 8
|LSU|0.05
|MILR|TL * 2 + 20
|MILS|0.04
|MINE|TL * 2 + 10
|MSL|TL * 4
|MSLT|TL * 25
|MTL|
|NMTL|
|PROF|
|RBEL|
|SLDR|
|SLSU|
|SPY|
|SNSR|TL * 40
|SDRV|TL * 25
|SSU|0.5
|TRNS|TL * 4
|UEMP|
|USKW|
|===

[index]
== Index
