= Wraith User Guide
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith User Guide (c) 2022 by Michael D Henderson

Wraith User Guide is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: The Reference Manual is the source of truth for the rules.
If this document does not match, this document is wrong.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Introduction

=== History
The Ryxen League was created to facilitate trade and settle disagreements between member nations.
The League worked well for many generations but eventually became corrupt and installed a dictator.

Rebellions started.
The corrupt government was outnumbered, so it created an AI system, WRAITH, to wage war against the member nations.

WRAITH was effective and brutal and soon started destroying entire worlds.

With the future looking bleak, the nations built a fleet of world ships to move their people to safety.
They built the ships with as little technology as possible to avoid detection, essentially bio-domes bolted to massive hyper-drives.

The fleet kept jumping until they had almost depleted their fuel reserves.
The ships split up, each nation looking to establish itself in the cluster.

The game takes place about thirty generations (12,000 "standard years") after the nations establish new homeworlds in the cluster.

The nations have thrived in isolation.
They've rebuilt their industry, rediscovered many technologies, and started exploring their system.

The history of their flight and migration has mostly been forgotten or transformed into legends.

That changed when they detected a signal originating beyond the furthest planet in their system.

== Important Terms
=== Cluster
The cluster is the area in the galaxy that the game takes place in.
It contains systems and planets.

=== System
A system in the game contains one or more stars.

The system is identified by its coordinates in the format "X/Y/Z".

=== Star
A star in the game has exactly 11 orbits, numbered 1 through 11.

The identifier (ID) for a star depends on the number of stars in the system.
If there is just one star, the star's ID is the same as the system's ID.
If there are multiple stars, the star's ID is the system's ID followed by a sequence letter.
The sequence letter will be "A" for the first star in the system, "B" for the second star, etc.
If system `1/2/3` had just one star, that star's ID would be `1/2/3`.
If there were four stars in that system, they would be identified as `1/2/3A`, `1/2/3B`, `1/2/3C`, and `1/2/3D`.

=== Orbit
An orbit in the game can be empty, contain a planet, or be the connection between two stars in the system.

The orbit is identified by its star's ID followed by an octothorpe ("#") and the orbit number.

The 11th orbit for a star serves two purposes.
It is the default entry point for hyper-drive jumps.
It is also the connection point between stars in systems with multiple stars.

=== Planet
In the game, "planet" is the generic term for the occupant of an orbit that is not empty.
The occupant can be an asteroid belt, a gas giant, or a terrestrial.

NOTE: "Terrestrial" does not imply
https://en.wikipedia.org/wiki/Class_M_planet[Class M].
Mercury is a terrestial.

The planet is identified by its orbit.

==== Habitability Number
The habitability number in the game is a measure of the maximum population that a planet can sustain in an open colony.

The value ranges from 0 to 25.
A value of 0 means that the population must live in an enclosed colony with life support.
Any other value means that the population can live in an open colony on the surface without life support.

==== Natural Resource
Every planet contains up to 35 deposits of natural resources.
Resources include gold (an abstraction of precious metals and crystals),
fuel (an abstraction of organic and inorganic power sources),
metals (all metallic ores except gold),
non-metal (everything else).
Natural resources must be mined and refined, turning them into raw materials, before they can be used.

==== Asteroid Belt
An asteroid belt (or just "asteroid") in the game is a type of planet that is dispersed through the entire orbit.
It is composed of many small, irregular bodies ranging in size from 100's of kilometers to particles of dust.
These bodies (or "rocks") are composed of carbon, silicate, metals, non-metals, and ice.

Enclosed colonies may be built in an asteroid belt.

==== Gas Giant
A gas giant in the game is a type of planet with an atmosphere of mostly helium and hydrogen.
The surface of the planet can't be reached because of the high mass and temperatures.

Enclosed colonies may be built on the surface of moons orbiting a gas giant.

==== Terrestrial
A terrestrial in the game is a type of planet that is smaller than a gas giant.
It is round and large enough to sweep its orbit clear.
It may have an atmosphere and a metal core, or it could be a frozen iceball with no atmosphere.

Colonies may be built on the surface of terrestrials.

A terrestrial with a habitability number of zero is called an unihabitable terrestrial.
With a value greater than zero, it it called a habitable terrestrial.

=== Colony
There are three types of colonies in the game: open, enclosed, and orbital.

Open colonies may be built on the surface of habitable terrestrials
(those with a habitability number greater than zero).
They don't require life support to sustain the population.

Enclosed colonies may be built on the surface of unihabitable terrestrials
(those with a habitability number of zero),
and in an asteroid belt.
They require life support to sustain the population.

Oribital colonies may be built in orbit around any planet.
They may not be built in an empty orbit.
They require life support to sustain the population.

=== Ship
A ship in the game is built with a hull, engines, cargo holds, and weapons.

Ships require space-drives to move in a planet's orbit.
They require hyper-drives to move between systems.

=== Turn
Players complete a turn in the game by submitting a set of orders.
After processing the orders, the game-master sends each player a report with the results of their orders.

=== Order
The heart of the game is order processing.
Orders change the state of the game;
they start an assembly line to create items,
transfer cargo between systems,
engage in diplomacy and spying,
or attack other nations.

Orders are processed in phases.
This helps players know when an order will be implemented.

.Phase Chart
|===
|Phase|Description

|Fuel Allocation|In this phase, fuel is allocated to units.
Fuel allocations are prioritized: life support is first, followed by farms, mines, then factories.
The allocation algorithm is naive and simple.
It attempts to allocate 100% of a unit's needs before moving to the next unit.
It never allocates proportionately.
|Farming Production|The farming production phase todo...
|Mining Production|The mining phase is used to extract resources from deposits and refine them into materials that can be used in the manufacturing phase.
|Manufacturing Production|The manufacturing production phase todo...
|Combat|The combat phase is used to project force against other player's assets.
|Set up|The set up phase is used to assemble new colonies and ships.
|Disassembly|This phase is used to disassembly operational units and make them ready to put into storage.
|Build Change|The build change orders phase is used to todo...
|Minch Change|The mining change orders phase is used to todo...
|Transfer|The transfer phase is used to todo...
|Assembly|The assembly phase is used to manufacture items, mine resources, and assemble units from storage.
|Market|The market and trade station phase is used to todo...
|Survey|This phase surveys systems, planets, colonies, and ships.
Reports are todo...
|Survey Reports|This phase produces the probe and sensor reports.
Todo...
|Espionage|The espionage phase todo...
|Movement|The movement phase is the only phase in which ships move.
Todo...
|Draft|This phase applies draft orders to move workers between population unit types todo...
|Pay and Ration|This phase todo...
|Rebellion|This phase todo...
|Rebel Changes|In this phase, the rebel population changes are applied.
Todo...
|Control|In this phase, naming and control orders are todo...
|Birth|In this phase, population increases due to births are calculated.
|News|In this phase, reports for the "news services" are created todo...
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

.Processing order
====
To illustrate,
let's assume that S23 and S24 are both in system `8/8/8`
and that we have the following orders in our file:
```
1: survey S23        ; order Ship 23 to survey the system it is currently in
2: move   S24 9/9/9  ; order Ship 24 to move to system 9/9/9
3: survey S24        ; order Ship 24 to survey the system it is currently in
```

Please note that the line numbers are not part of the order.
The semicolon treats the remainder of the line as a comment.

Lines `1` and `3` would process in Phase 9 (Surveys).
Line `1` would process before Line `3` because it occurs earlier in the file.
S23 would survey its current location, system `8/8/8`.
S24 would survey the same location because it has not moved yet.

Line `2` would process in Phase 11 (Ship Movement).
S24 would move to system `9/9/9`.
Because Ship Movement happens after Survey,
the ship would not perform the survey in system `9/9/9`.
====

== Setup
Wraith can be played as an individual competition or with players cooperating.

=== Individual Competition
In individual competition, each player manages unique species, running his/her own nation.

==== Victory Conditions
The "winner" is the first player to control 100 planets for 4 consecutive turns WITH no other player controlling more than 50 planets in any of those turns.

=== Shared Species
When sharing species, each player runs his/her own nation, but teams of players share a common species and a common homeworld.

The players that share a homeworld must cooperate to build ships and start exploring the system, or they can battle each other.

==== Victory Conditions
The "winner" is the first species to control 200 planets for 4 consecutive turns WITH no other species controlling more than 100 planets in any of those turns. Within each species, the player with the strongest economy is the "winner."

[appendix]
== Charts

[index]
== Index

