= Wraith User Guide
Michael D Henderson <mdhender@example.com>
v0.0.0, 2022-05-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Wraith User Guide (c) 2022 by Michael D Henderson

Wraith User Guide is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-nc/4.0/>.

WARNING: The Reference Manual is the source of truth for the rules.
If this document does not match, this document is wrong.

:sectnums:
== Foreword
Wraith is inspired by the play by mail and strategy games that preceded it,
most notably https://en.wikipedia.org/wiki/Empyrean_Challenge[Empyrean Challenge],
https://farhorizons.dev[Far Horizons],
and https://en.wikipedia.org/wiki/The_Campaign_for_North_Africa[The Campaign for North Africa].

== Introduction

=== History
The Ryxen League was created to facilitate trade and settle disagreements between member nations.
The League worked well for many generations but eventually became corrupt and installed a dictator.

Rebellions started.
The corrupt government was outnumbered, so it created an AI system, WRAITH, to wage war against the member nations.

WRAITH was effective and brutal and soon started destroying entire worlds.

With the future looking bleak, the nations built a fleet of world ships to move their people to safety.
They built the ships with as little technology as possible to avoid detection, essentially bio-domes bolted to massive hyper-drives.

The fleet kept jumping until they had almost depleted their fuel reserves.
The ships split up, each nation looking to establish itself in the cluster.

The game takes place about thirty generations (12,000 "standard years") after the nations establish new home planets in the cluster.

The nations have thrived in isolation.
They've rebuilt their industry, rediscovered many technologies, and started exploring their system.

The history of their flight and migration has mostly been forgotten or transformed into legends.

That changed when they detected a signal originating beyond the furthest planet in their system.

=== What is Wraith?
Wraith is a strategic turn based game where you explore a cluster of stars.
Your ships will discover planets and technology that will help you grow your nation.
As the ruler, you set policies and decide how best to allocate resources to meet your objectives.

You will meet other species in the game.
Most will be other players, but a few will be independent colonies or ships.
They can be cooperative and engage in trade or belligerent and engage in war.

=== How to Play
When you join a game, you'll receive a report showing the location of your home planet,
your population, the technologies you've mastered, the ships in your fleet,
and the farms, mines, and factories that support your world.

Each turn you will submit orders to the game master.
Your orders determine what goods are produced, how trade is carried out, and can even start wars.

A key to the game is keeping supplies flowing to the units that need them.
Ships need trained crews as well as fuel and maintenance.
Factories require labor, power, and raw materials to manufacture goods.

Every player's orders are processed at the same time,
which is usually just after the deadline for submitting them.

After the results are calculated, you'll receive an updated report.
It has the same format as the initial report.
Because the report can contain a lot of information,
you'll also get a summary of the changes from the prior turn.

== Getting Started
The game manager (GM) will grant you access to the game's website when you start a game.

You will find a table with all the systems in your cluster.
It lists the location (using X/Y/Z coordinates) for each system.

The table shows plus the number and types of stars in the system.
Additional information like  will be added when your ships visit the system

Your home system (the system that your home planet is in) will show the planets and their orbits.
You get a summary of the colonies, population, industry, and resources, too.

As your ships explore the cluster,
the table will be updated with similar summaries,
along with the turn that they visited.
If they've conducted surveys,
there will be a link to the detailed survey report.

TIP: The reports always use the most current information available to your nation.
Updates are made automatically if you have a colony in the system;
otherwise only when one of your ships visits.

Plan ahead to manage your population and natural resources,
and ensure the right quantity of materials are where they need to be,
when they are needed.

== The first turn
All players start on their own home planet with the same population, infrastructure, and inventory.

The cluster is generated randomly, so the amount of natural resources in the home system will vary.
Some systems will be close to other systems, making exploration easy;
some will be farther away, making exploration harder.

It all starts with food.
Farms, as long as they have sufficient labor and fuel, will produce food every turn.
They need ships to move the harvest to markets and to deliver fuel.

Labor comes in the form of managers (professionals) and workers (unskilled workers or robots).
Fuel is extracted and refined by mining units.
Like farms, if they have sufficient labor and fuel they'll produce raw materials like fuel, gold, and metal every turn.
(Unlike farms, the deposits worked by mines will eventually run out, but you don't need to worry about that just yet.)

Again, just like farms, the labor is managers (professionals) and workers (unskilled workers or robots).
They need ships to move the raw materials to markets, ships to deliver food to the workers,
and, if they're not making fuel themselves, ships to bring the fuel to power the heavy machinery.

All those ships are built in factories.
Factories that need managers (professionals) and workers (unskilled workers or robots) on the assembly lines.
The assembly lines take fuel and metals from the mines to build ships.
Not just ships, but everything
(well, everything except for food and raw materials, which are produced only by farms and mines.)
you'll use in the game.
That includes the farming and mining equipment used on all of those farms and mines.

Luckily, you'll start the game with farms, mines, and factories,
plus some ships and transports to keep things moving.
All you have to do is send out the orders that coordinate all the pieces.

((TODO)): suggestions for the first few turns...

== People
The people in your nation are split into groups and each group has a set of skills that only they can use.

People in the *PROFESSIONAL* group are trained to manage farms, mines, and factories.
They can also pilot space-going ships (not all at the same time, of course).

There are also *SOLDIER* group.
These are the people trained to wage war, pilot assault crafts, and secure the peace.
(There is no separate group for police.)

The people in the *WORKER* group engage in the trades.
They wield hammers and wrenches, operate heavy machine,
move the heavy things, drive the big rigs and tractors,
and keep the assembly lines going.

The remainder is the *UNEMPLOYED* group.
This includes young people, old people, students, teachers, artists, and even convalescing soldiers.

There are two categories for the general population: *CONSTRUCTION CREW* and *SPY TEAM*
A construction crew is composed of professionals and workers that are specially trained to build ships and colonies.
A spy team is composed of professionals and soldiers that are trained to conduct espionage and counter-espionage.

Finally, there is the *REBEL* contingent.
These are the people that are discontent with your governing or local conditions.
Rebels can come from any group (professional, soldier, worker, or unemployed).
They can even be a member of a special category (construction crew or spy team), too.
If they're really, really unhappy, they will try to overthrow your government.
Rebel soldiers and spy teams can be very disruptive!

Two of the basic orders for population are pay and rations.
You pay people with consumer goods produced by your factories.
You feed them with the food from your farms.
The "pay" order declares how much each group is paid per turn.
The "ration" order determines how much food is distributed per turn.
You start the game with pay and rations set to 100% of the base rate
(see Chart ??? for details on the base rate).


[appendix]
== Bad Writing Ahead
=== The Circle of Supply Lines
The supply line (to abuse a metaphor) is a circle that begins and ends with farms.

Farms produce food to feed factory workers.
Factory workers produce mining equipment.
Mine workers use the equipment produce fuel and metal.
The fuel and metal are transported to factories in ships crewed by people who consume food and air.
Factories consume the fuel and metal to produce farming equipment.
Ships transport the equipment to farm colonies, which use them to produce more food.

TIP: You must build ships to transport people, food, and materials to your colonies.
If you don't, the mines and factories will shut down.
Starving people will start a rebellion.

[appendix]
== Important Terms
We created a separate glossary because of the amount of jargon and the number of abbreviations in this.

((TODO)): should all this be moved to the glossary?

=== Cluster
The ((cluster)) is the area in the galaxy that the game takes place in.
It contains all the systems and planets that you'll work with.

=== System
A ((system)) in the game contains one or more stars.

The identifier (SystemID) for a system is its coordinates in the format "X/Y/Z".

TIP: ((SystemID)) is the system identifier.
For example `5/2/9`.

=== Star
A star in the game has exactly 11 orbits, numbered 1 through 11.

The identifier (StarID) for a star depends on the number of stars in the system.

If there is only one star, the star's ID is the same as the system's ID.

If there are multiple stars, the star's ID is the system's ID followed by a sequence letter.
The sequence letter will be "A" for the first star in the system, "B" for the second star, etc.
If system `1/2/3` had just one star, that star's ID would be `1/2/3`.
If there were four stars in that system, they would be identified as `1/2/3A`, `1/2/3B`, `1/2/3C`, and `1/2/3D`.

TIP: ((StarID)) is the star identifier.
For example `5/2/9` or `1/2/3D`.

=== Orbit
An ((orbit)) in the game can be empty, contain a planet, or be the connection between the stars in the system with multiple stars.

The identifier (OrbitID) for an orbit is an octothorpe ("#") followed by the orbit number.

The 11th orbit for a star serves two purposes.
. It is the entry point for hyper-drive jumps.
. In systems containing multiple stars, it is the nexus between the stars.

TIP: An OrbitID is `#4`.

=== Planet
"Planet(((planet)))" is a generic term for the occupant of an orbit that is not empty.
The occupant can be an asteroid belt, a gas giant, or a terrestrial.

NOTE: "Terrestrial" does not imply a habitable
https://en.wikipedia.org/wiki/Class_M_planet[Class M]
planet.
Mercury, Venus, and Neptune are all terrestrial.

The identifier (PlanetID) for a planet is its StarID with the OrbitID appended.

NOTE: Planets orbit a star in a system.
That is why the StarID is required to identify it.

TIP: ((PlanetID)) is the planet identifier.
For example `5/2/9#2` or `1/2/3D#4`.

==== Habitability Number
((Habitability Number)) in the game is a measure of the maximum population that a planet can comfortably sustain in an open colony.
The Habitability Number is usually abbreviated as "((HN))."
The value ranges from 0 to 25.

An ((uninhabitable planet)) has an HN of 0.
That means that it can not support any population at all.
You must build an enclosed colony with life support for people to survive on the surface of the planet.

A ((habitable planet)) has an HN between 1 and 25.
People may live on the surface without life support.

==== Natural Resource
Every planet contains up to 35 deposits of natural resources.
Resources include gold (an abstraction of precious metals and crystals),
fuel (an abstraction of organic and inorganic power sources),
metals (an abstraction of all metallic ores except gold),
non-metal (an abstraction of almost everything else).
Natural resources must be mined and refined,
turning them into raw materials,
before they can be used.

==== Asteroid Belt
An asteroid belt (or just "asteroid") in the game is a type of planet that is dispersed through the entire orbit.
It is composed of many small, irregular bodies ranging in size from particles of dust to 100's of kilometers in diameter.
These bodies (or "rocks") are composed of carbon, silicate, metals, non-metals, and ice.

Enclosed colonies may be built on the surface of larger rocks in an asteroid belt.

==== Gas Giant
A gas giant in the game is a type of planet with an atmosphere of mostly helium and hydrogen (like Jupiter).
The surface of a gas giant is inaccessible because of the high mass and temperatures,
so enclosed colonies may be built on the surface of moons orbiting the gas giant.

==== Terrestrial
A terrestrial in the game is a planet that isn't a gas giant or an asteroid belt.
It is large enough to be round and sweep its orbit clear.
It may have an atmosphere and a metal core like Mars,
no atmosphere like Mercury,
an ice giant like Neptune,
or a frozen ball of methane.

Colonies may be built on the surface of terrestrials
(or, in the case of ice giants, the surface of the moons orbiting them).

A terrestrial with a habitability number of zero is called an uninhabitable terrestrial.
With a value greater than zero, it is called a habitable terrestrial.

=== Colony
There are three types of colonies in the game: open, enclosed, and orbital.

Open colonies may be built on the surface of habitable terrestrials
(those with a habitability number greater than zero).
They don't require life support to sustain the population.

Enclosed colonies may be built on the surface of unihabitable terrestrials
(those with a habitability number of zero),
and in an asteroid belt.
They require life support to sustain the population.

Orbital colonies may be built in orbit around any planet.
They may not be built on the surface of a planet or in an empty orbit.
They require life support to sustain the population.

.Colony Location Chart
|===
||On Planet Surface|On Asteroid Belt|In Orbit|Life Support Required|Maximum Size

|Open Colony ^|Habitable Terrestrial ^|NO ^|NO ^|NO ^|UNLIMITED
|Enclosed Colony ^|Any Terrestrial ^|YES ^|NO ^|YES ^|UNLIMITED
|Orbital Colony ^|NO ^|NO ^|Any Planet ^|YES ^|UNLIMITED
|===

=== Ship
A ship in the game is built with a hull, engines, cargo holds, and weapons.

Ships require space-drives to move in a planet's orbit.
They require hyper-drives to move between systems.

NOTE: Ship building is discussed in detail in ((TODO)).

=== Turn
Players complete a turn in the game by submitting a set of orders.
After processing the orders, the game-master sends each player a report with the results of their orders.

=== Order
The heart of the game is order processing.
Orders change the state of the game;
they start an assembly line to create items,
transfer cargo between systems,
engage in diplomacy and spying,
or attack other nations.

Orders are processed in phases.
This helps players know when an order will be implemented.

.Phase Chart
|===
|Phase|Description

||((TODO)): sync this with the reference manual.
|===

All _orders_ for a given _phase_ are executed before the next _phase_ begins.
Within a phase, _orders_ are executed in the order they were issued.

.Processing Sequence
====
To illustrate,
let's assume that S23 and S24 are both in system `8/8/8`
and that we have the following orders in our file:

[source]
----
1: survey S23        ; order Ship 23 to survey the system it is currently in
2: move   S24 9/9/9  ; order Ship 24 to move to system 9/9/9
3: survey S24        ; order Ship 24 to survey the system it is currently in
----

Please note that the line numbers are not part of the order.
The semicolon treats the remainder of the line as a comment.

Lines `1` and `3` would process in Phase 9 (Surveys).
Line `1` would process before Line `3` because it occurs earlier in the file.
S23 would survey its current location, system `8/8/8`.
S24 would survey the same location because it has not moved yet.

Line `2` would process in Phase 11 (Ship Movement).
S24 would move to system `9/9/9`.
Because Ship Movement happens after Survey,
the ship would not perform the survey in system `9/9/9`.
====

== Production
=== Farming
=== Mining
=== Manufacturing
== Diplomacy and Trade
=== Markets
== Combat
== Rebellion

== Winning
Wraith can be played as an individual competition or with players cooperating.

=== Open-Ended
In an open-ended game, there are no victory conditions.

((TODO)): support open-ended games

=== Individual Competition
In individual competition, each player manages unique species, running his/her own nation.

==== Victory Conditions
The "winner" is the first player to control 100 planets for 4 consecutive turns WITH no other player controlling more than 50 planets in any of those turns.

=== Shared Species
When sharing species, each player runs his/her own nation, but teams of players share a common species and a common home planet.

The players that share a home planet must cooperate to build ships and start exploring the system, or they can battle each other.

==== Victory Conditions
The "winner" is the first species to control 200 planets for 4 consecutive turns WITH no other species controlling more than 100 planets in any of those turns. Within each species, the player with the strongest economy is the "winner."

[appendix]
== Charts

.Unit Descriptions
|===
|CODE|Name|DESCRIPTION

|AMSL|Anti-Missile|Anti-missile units are used in combat to destroy incoming missiles.
|ATKC|Assault Craft|Assault craft units are small, highly manuverable ships used in combat for attacks and raids.
|ATKW|Assault Weapons|Assault weapons are used by soldiers in combat situations.
|AUTO|Automation|
|CONW|Construction Worker|A notational unit used to track the number of Professional and Unskilled Workers trained to build, assemble, and disassemble other units.
|CGDS|Consumer Goods|
|ENSH|Energy Shield|Energy shields absorb and disipate the damage from energy weapons.
|ENWP|Energy Weapon|Energy weapon units are line-of-sight beams of wanton destruction used to attack enemy colonies and ships in combat.
|FACT|Factory|
|FARM|Farm|
|FOOD|Food|A farmed resource used to feed people in the game.
|FUEL|Fuel|A mined resource used to power other units in the game.
|GOLD|Gold|A mined resource used as currency and also in manufacturing.
This represents all precious metals and crystals, not just gold.
It might morph into "credits" in the future.
|HDRV|Hyper Drive|
|LFSP|Life Support|
|LSU|Light Structure|A type of structural unit built only in orbiting colonies.
The mass of LSU units is 10% of SSU units, but each LSU can replace one SSU when building colonies, ships, and enclosed storage.
|MILR|Military Robot|Military robot units replace soldiers on combat missions.
|MILS|Military Supplies|Military supplies are the items used by soldiers in combat.
|MINE|Mine|
|MSL|Missile|Missile units are used in combat to attack enemy targets.
|MSLT|Missile Launcher|Missile tubes are used in combat to fire anti-missile and regular missiles.
|MTL|Metallic Resource|A mined resource used by factories to manufacture finished goods.
|NMTL|Non-Metallic Resource|A mined resource used by factories to manufacture finished goods.
|PROF|Professional Worker|A group of 100 people trained to manage people and projects.
|RBEL|Rebel|A notational unit used to track the number of potential rebels in the population.
|SLDR|Soldier|A group of 100 people trained for military operations.
|SLSU|Super Light Structure|A type of structural unit built only in high-tech factories on orbiting colonies.
The mass of SLSU units is 1% of SSU units, but each SLSU can replace one SSU when building colonies, ships, and enclosed storage.
|SPY|Spy|A notational unit used to track the number of Professional Workers and Soldiers trained in espionage and counter-espionage.
|SNSR|Sensor|
|SDRV|Space Drive|
|SSU|Standard Structure|The standard type of structural unit used for building colonies, ships, and enclosed storage.
|TRNS|Transport|
|UEMP|Unemployable|A group of 100 people that are not Unskilled Workers, Professional Workers, or Soldiers.
"Uenemployable" means that members of this group can not be drafted.
|USKW|Unskilled Worker|A group of 100 people trained as general labor.
|===

.Unit Mass Units
|===
|CODE|MASS Units (MUs) per UNIT

|AMSL|TL * 4
|ATKC|TL * 5
|ATKW|2
|AUTO|
|CONW|
|CGDS|
|ENSH|TL * 50
|ENWP|TL * 10
|FACT|TL * 2 + 12
|FARM|TL + 6
|FOOD|6
|FUEL|
|GOLD|
|HDRV|TL * 45
|LFSP|TL * 8
|LSU|0.05
|MILR|TL * 2 + 20
|MILS|0.04
|MINE|TL * 2 + 10
|MSL|TL * 4
|MSLT|TL * 25
|MTL|
|NMTL|
|PROF|
|RBEL|
|SLDR|
|SLSU|
|SPY|
|SNSR|TL * 40
|SDRV|TL * 25
|SSU|0.5
|TRNS|TL * 4
|UEMP|
|USKW|
|===

[index]
== Index
